### ISSUE TITLE
Process Manager: setting cluster size to 1 puts strong-pm record in bad state

### ISSUE THREAD

**Issue by altsang** [strongloop/strong-arc#1003]
steps to reproduce:

1. initialize Process Manager with 1 host to set application
2. add second host with strong-pm running with cluster size defaulted to number of cpus
3. activate second host
4. set `Count` field to 1
5. second host record deactivates with `Problem ?` icon, the ? says that the app is running - strong-pm is still running - verified by going directly to API endpoint (e.g. http://localhost:4802/explorer)
6. tried using `start` on host drop down menu  - activates and then goes back to problem state
7. tried clicking the socket/plug icon - same thing, tries to activate and then goes back to problem state
8. tried deleting and re-adding the record - same thing

I suspect backend is reporting app status incorrectly for whatever reason if the cluster is set to 1

**Comment by seanbrookes** [comment]
I thnk the 'single' process was the supervisor with zero child processes which was the source of the 'bad state'

- We are filtering out the supervisor pid now so the count and display should be accurate to actual working processes.
- I also added a check to make sure the count doesn't go below 1 .

Theoretically the combination of the above should have resolved this.

**Comment by chandadharap** [comment]
Should be assigned to @cgole and not Albert! re-assigning.

**Comment by cgole** [comment]
verified
