### ISSUE TITLE
Process Manager: need number spinner from for PID count

### ISSUE THREAD

**Issue by altsang** [strongloop/strong-arc#1004]

**Comment by stacy-hunt** [comment]
This card is included in 1007 so will remove it

**Comment by stacy-hunt** [comment]
Al, is this card a todo for the design or development? There is another card for adding a spinner design to the style guide which I've already done, so I could move this card to done if it is meant to relate to that. However, if this card is meant for development perhaps I should assign it to Anthony instead?

**Comment by stacy-hunt** [comment]
Hey Al, is this card meant for design or development? There is another card 1027 for adding a spinner design to the style guide, which I've already done. If this card (1024) relates to that, I could move it to "done", but if it's meant for development then perhaps I should assign it to Anthony instead?
