### ISSUE TITLE
arc manager : Windows - sl nginx controller fails to start

### ISSUE THREAD

**Issue by cgole** [strongloop/strong-arc#1011]
This must be a windows path format issue. 

![screen shot 2015-02-08 at 9 42 11 am](https://cloud.githubusercontent.com/assets/991632/6097548/07116462-af77-11e4-896b-d797296d4b71.png)
C:\Users\Administrator\nginx\.strong-nginx-controller\nginx/logs/error.log" failed (3: The system cannot find the path specified)

**Comment by kraman** [comment]
@chandadharap @cgole Nginx is not currently supported on Windows. 

@crandmck Perhaps that needs to be documented.

**Comment by crandmck** [comment]
I added a note to http://docs.strongloop.com/display/SLC/Configuring+Nginx+load+balancer.

**Comment by chandadharap** [comment]
closing.
