### ISSUE TITLE
Polish Manager Visual Comp

### ISSUE THREAD

**Issue by stacy-hunt** [strongloop/strong-arc#1013]
- [x] Change "Processes" column header to "Count" and "PIDs"
- [x]  Standardise Help icon
- [ ] Plug icon should go dark green on hover instead of blue (+ discuss principle behind this)
- [ ] Activated socket icon grey is too light
- [x] Some slides show "+Add Host" link as blue when there is no mouseover
- [ ] Add App header to slides once the first host has been activated
- [ ]  Add Number spinners to PID column

**Comment by altsang** [comment]
Also need darker socket plug icon displayed after activation.  The current gray is too light.
