### ISSUE TITLE
process manager: make delete icon more readily accessible

### ISSUE THREAD

**Issue by altsang** [strongloop/strong-arc#1020]
please make (x) accessible when you hover highlight over the row

**Comment by altsang** [comment]
related - pls see #1198 - Composer needs to be retrofitted as well

**Comment by anthonyettinger** [comment]
as per @altsang, make the default icon the same icon as the hover.

**Comment by anthonyettinger** [comment]
this has been fixed

**Comment by altsang** [comment]
verified on master, looks good
