### ISSUE TITLE
metrics missing titles

### ISSUE THREAD

**Issue by seanbrookes** [strongloop/strong-arc#1023]
for some reason the navigation titles on the metrics view are missing now and there is an exception about index of 1

**Comment by seanbrookes** [comment]
I tightened up some logic around how things are handled when there are no metrics but hte basic issue here is actually working by design.

Originally the call was for the left navigation to be independent of the charts in the main view but it was confusing to have to scroll to the chart controls and then back to the chart if they were not aligned on the left.

So I set the chart nav to stay with the chart itself - which led to a redundancy where the nav title was the same as the chart title right beside it - it looked unnecessary so I removed it from the nav column and left it on the chart itself.

We can revert if needed but IMO the ux is better when the nav controls are connected to the charts themselves.

**Comment by altsang** [comment]
yeah agreed on the point of having the nav controls on the charts, I'm coming around to that.  I think originally the nav was there to be consistent with composer for anchoring
I'll review with @stacy-hunt this Wednesday and anyone else who can still attend the 3pm

**Comment by altsang** [comment]
@stacy-hunt is done with a proposal to move chart controls to the chart itself, he was going to meet with Sean to consolidate behavior on Tracing and Metrics because of how Concurix was implemented and with differences in constraints

**Comment by altsang** [comment]
@stacy-hunt do you have the updated comp for Metrics where you move the chart controls onto the chart itself getting rid of the nav bar?

**Comment by stacy-hunt** [comment]
Yep, at this link
<https://drive.google.com/open?id=0B1FTzkB7697GRFhMSkd1dGhuNm8&authuser=0>
