### ISSUE TITLE
process manager: env get/set implementation

### ISSUE THREAD

**Issue by altsang** [strongloop/strong-arc#1025]
need to  implement per UX and VD

**Comment by chandadharap** [comment]
@altsang Link to UX/VD here?

**Comment by altsang** [comment]
haven't covered yet, going to discuss at 3 PM today (3/23) as one of the items

**Comment by altsang** [comment]
wireframes are in this folder - http://bit.ly/1I0usy5

**Comment by jtary** [comment]
@altsang this is merged into master now, can you verify the functional UX?

**Comment by altsang** [comment]
UX functionality looks good, assigning to @cgole for testing

**Comment by cgole** [comment]
verified
