### ISSUE TITLE
Capturing heap snapshot from Windows 8 on demo app takes too long

### ISSUE THREAD

**Issue by jakerella** [strongloop/strong-arc#1026]
I was attempting to capture a heap snapshot from the demo app (appdemo.strongloop.com:7000) in Arc running on a Windows 8.1 machine (latest strongloop installed, latest Chrome, Node 0.10.35) and it took over 3 minutes for the heap snapshot to process and appear in the left sidebar. It reads as 28.8 MB and looks fine once ready, but the process takes over 3 minutes from the time I click the "Take Snapshot" button. Sitting right next to me (same wifi network), Ryan was able to take a snapshopt on the same demo app from his Mac in about 15 seconds.

The Chrome dev tools show no errors and local CPU and memory never went above 50% usage during the process (usually much less).

**Comment by cgole** [comment]
@ben is working on profiler performance issues. Will revisit this once that is fixed. https://github.com/strongloop/strong-arc/issues/1183

**Comment by cgole** [comment]
cannot fix. details in #1183

**Comment by jakerella** [comment]
sad :panda_face:

**Comment by chandadharap** [comment]
@jakerella, hope you read the comments on #1183

**Comment by jakerella** [comment]
I did... but seems like Windows in particular takes much longer than my Linux machine.
