### ISSUE TITLE
Profile tree files  links don't load.

### ISSUE THREAD

**Issue by cgole** [strongloop/strong-arc#1028]
Profile tree files  links dont load. They load as http://localhost:56497/usr/local/lib/node_modules/strongloop/node_modules/strong-supervisor/lib/targetctl.js
should be something like file:///usr/local/lib/node_modules/strongloop/node_modules/strong-supervisor/lib/targetctl.js
![screen shot 2015-02-11 at 11 49 10 am](https://cloud.githubusercontent.com/assets/991632/6154912/1eac9f78-b1e4-11e4-9cbc-fe16ef5d1f82.png)

**Comment by anthonyettinger** [comment]
I don't think we can browse these links as they aren't local. Can someone confirm?

**Comment by anthonyettinger** [comment]
@altsang ^

**Comment by altsang** [comment]
I've been meaning to log this bug for the longest time.  Correct - cannot be loaded locally unless you happen to have source and would have to match up in the right location.  Worse case can we disable the links via CSS?

**Comment by anthonyettinger** [comment]
probably not with css, but I may be able to find where its creating the link and make it a span instead.

**Comment by altsang** [comment]
nice - that sounds good to me!

**Comment by cgole** [comment]
get strongloop from staging regitsry

**Comment by cgole** [comment]
this looks good now
