### ISSUE TITLE
Help link in Arc should bring up contextually-appropriate doc / help page

### ISSUE THREAD

**Issue by crandmck** [strongloop/strong-arc#1031]
Currently the help link opens the old genetric Arc doc page (http://docs.strongloop.com/display/ARC/StrongLoop+Arc), which is no longer part of the main docs, since we have made them task-oriented.  
![arc help btn](https://cloud.githubusercontent.com/assets/2925364/6196072/a7151b32-b389-11e4-9f9d-bd9cda76fef5.png)

The URL should depend on which module you are in: Composer, Build & Deploy, etc.

**Comment by crandmck** [comment]
Here are the article IDs:
 - Build & Deploy - 6096288	
 - Composer - 6096284	
 - Metrics - 6096290	
 - Profiler - 6096286	
 - Process Manager	- 6096292	

 @anthonyettinger Let me know if you need more from me.  Many of these are very brief now, but I can add more if we think they need more...

**Comment by chandadharap** [comment]
Assigning to Anthony for a quick check. Reserving Chandrika for functional ones.
