### ISSUE TITLE
retrofit tabs (composer) from styleguide

### ISSUE THREAD

**Issue by anthonyettinger** [strongloop/strong-arc#1054]
![image](https://cloud.githubusercontent.com/assets/1924932/6474292/60c8f5d4-c1b4-11e4-9086-74323c073bfb.png)

**Comment by altsang** [comment]
@jtary and @anthonyettinger - would like to review before we close these - please confirm this is in master?

**Comment by altsang** [comment]
@stacy-hunt does the VD for composer need to be updated?  looks like the tabs are highlighted blue text only instead of the entire tab per the styleguide

**Comment by stacy-hunt** [comment]
Hmm, thanks I wasn't aware of that. I'll look into it.

S

**Comment by stacy-hunt** [comment]
Al, I might need a bit of clarification on this. Here's what the VD for
composer looks like:

[image: Inline images 1]

and here's what the styleguide (Visual, not live) looks like:

[image: Inline images 2]
It looks like the Close Icon (x) is visible on mouseout in the styleguide
and not in the composer comp, but I can't see what you mean about the
highlighted blue text.

I can see a couple of tweaks to make, such as adding the x on mouseout and
perhaps seeing if the rollover_selected state should be different from
mouseout_selected. So once I understand your question, maybe we should make
a new card to review and polish the Tabs component - and sync up the visual
styleguide, live styleguide and product as far as the tabs go.

This also relates to my question about our workflow: how we want changes to
the visual styleguide to flow on to the live styleguide and the product. If
we could discuss how we want to manage that at the next meeting we can use
this as an example.

S

**Comment by altsang** [comment]
hey @stacy-hunt no this was my bad - I thought the tab itself was highlighted blue - only the entry is highlighted in the nav bar, closing this out, good to go

verified on master
