### ISSUE TITLE
Spike: Identify short term integration plan of Concurix Traces with Arc

### ISSUE THREAD

**Issue by chandadharap** [strongloop/strong-arc#1062]
Adding @ritch for help. This is a Spike based on @seanbrookes evaluation. Discuss an immediate approach to understanding how to integrate Browserify approach with Angular based Arc. 

This is not a story for long term. As part of Spike, implement a simple end-to-end integration and create stories in Top of Backlog for integrating Traces and Flamegraph view only. (Not other the other charts)

Known 'work'
## Misc
- [x] establish 'integration vector'
- [x] initial LB api prototype
- [x] prototype UX in Arc
- [ ] reconcile overlapping dependencies (moment, d3, etc)
- [ ] finalize integration plan
- [ ] visual design
- [ ] implement v1 (post prototyping and integration)

## Monitor View
 - [ ] Host/PID selector
 - [x] CPU timeseries chart  (Its not the chart per say, its a navigational element to drill down to Trace View.)
 - [x] Memory timeseries chart. (Its not the chart per say, its a navigational element to drill down to Trace View.)
 - [x] Transaction history
 - [x] Transaction item histogram

## Trace View:
 - [ ] Summary Pie charts
 - [x] Waterfall list
 - [x] Flame  summary

## Detail View
 - [x] Waterfall 'navigator'
 - [x] Flame Chart
 - [x] Trace Tree
 - [x] Inspector

**Comment by seanbrookes** [comment]
we have to be carefull not to open too big a can of worms here.  It's like a wool sweater with a loose thread...don't pull too hard.

Any solution will need to not introduce friction to the development process (pre-build/excessive page load time) 

Options to explore:
- use same principles as Process Manager to integrate the relevant Concurix elements.  There are currently some performance concerns with the existing PM implementation that would need to be worked out
- re-architect Arc to be more 'browserfied' .  This is potentially the best mid/long term strategy but would need some time to plan and design the transition
- server side rendering of the native Concurix code using Phantom.js and then serving the markup over http.  This 
- reverse engineer the relevant UI components into Arc directives.  for me this is the least risky of the options in the short term but would create more work if we decide to move in the browserify

**Comment by seanbrookes** [comment]
Components to deal with
Monitor View:
1) Host/PID selector
2) CPU timeseries chart
3) Memory timeseries chart
4) Transaction history
Trace View:
5) Summary Pie charts
6) Waterfall list
7) Flame  summary
Detail View
8) Waterfall 'navigator'
9) Flame Chart
10) Trace Tree
11) Inspector

**Comment by seanbrookes** [comment]
We also need at least one story to sort out the API/LB interface

**Comment by chandadharap** [comment]
Approach: Tactical, short-term, least risky  and predictable.
Reverse engineer the relevant UI components into Arc directives. for me this is the least risky of the options in the short term but would create more work if we decide to move in the browserify

**Comment by seanbrookes** [comment]
I think we're in pretty good shape here.  

I suggest we call this complete after the demo on Monday

**Comment by chandadharap** [comment]
I agree. Please move to verify for now. I'm satisfied with the stories we
created and identified dependencies.

On Friday, March 6, 2015, Sean Brookes <notifications@github.com> wrote:

> I think we're in pretty good shape here.
>
> I suggest we call this complete after the demo on Monday
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/strongloop/strong-arc/issues/1062#issuecomment-77665234>
> .
>


-- 
Chanda Dharap
Director, Engineering
@StrongLoop Inc
(510) 304-3924
chanda@strongloop.com

*StrongLoop <http://strongloop.com/>** makes it easy to **develop APIs
<http://strongloop.com/mobile-application-development/loopback/>** in Node,
plus get DevOps capabilities
<http://strongloop.com/node-js-performance/strongops/> like monitoring,
debugging and clustering**.*

**Comment by chandadharap** [comment]
I moved it. Reviewed the stories you and I created on Friday and feel confident that we have a decent plan with coverage for middleware API and backend to support front-end.
closing.
