### ISSUE TITLE
Integrating Auth API for Registration/Entitlement

### ISSUE THREAD

**Issue by chandadharap** [strongloop/strong-arc#1064]
Needs to interact with @raymondfengs API. Dependency on Raymond.

**Comment by chandadharap** [comment]
Checklist please.

**Comment by raymondfeng** [comment]
I'm providing the apis to:

1. Get subscriptions for a given user from auth.strongloop.com
2. Push a list of usage records to auth.strongloop.com

**Comment by raymondfeng** [comment]
Sample apis:

http://localhost:3000/api/users/:id/subscriptions?access_token=*access_token*
http://localhost:3000/api/users/*username|email|id*/getSubscriptions?access_token=*access_token*

**Comment by anthonyettinger** [comment]
- [ ] landing page for licensing

**Comment by anthonyettinger** [comment]
pseudo code for license renewal:

```
licenses = get user licenses
for each license in licenses
  if expired
    renew license
    return ok
  
  if page in features
    return ok
  
  if page not in features
    renew/request access to feature
    return ok
end
```

**Comment by chandadharap** [comment]
status update?

**Comment by anthonyettinger** [comment]
I just got VD and went over the requirements with Raymond and Al yesterday. I'm integrating with Raymond's new api and VD.
