### ISSUE TITLE
Tar file build fails occasionally through arc

### ISSUE THREAD

**Issue by cgole** [strongloop/strong-arc#1067]
When I try tar build the first time it fails. On retrying, I can build successfully.

**Comment by cgole** [comment]
I noticed this on the version of slc on npmjs and staging

**Comment by cgole** [comment]
This happens almost everytime I try. ie in the first attempt to build it always fails

**Comment by chandadharap** [comment]
This has existed for so long that I would not hold up an interim release. But we should fix.

**Comment by cgole** [comment]
surprisingly, I did not run into this issue yesterday
