### ISSUE TITLE
Licensing Page: UX and VD

### ISSUE THREAD

**Issue by altsang** [strongloop/strong-arc#1068]
need discussion on where the licensing page hangs off in Arc (top level)

**Comment by altsang** [comment]
@sean, @stacy-hunt discussed with @anthonyettinger:

here's my proposal to hack up:
include it in the `app selector` drop down when you are in the licensing page itself - this gives our user a way out other than clicking the StrongLoop logo and the selection is there purely to be consistent

optional:  include in drop down menu of button button as dual way to get there
optional: if you are NOT in the license page itself the option will not be presented in the app selector - as it's not really an `app`

**Comment by stacy-hunt** [comment]
OK, assuming this will be on the table for today's meeting
