### ISSUE TITLE
Implement local keystore for Arc to store license keys retrieved from auth.strongloop.com

### ISSUE THREAD

**Issue by chandadharap** [strongloop/strong-arc#1069]

**Comment by altsang** [comment]
if Arc is retrieving keys, it's assumed that the `strongloop` package is installed globally and properly

we should consider having the keystore be stored centrally in the strongloop package instead of Arc on the filesystem

- [ ] if I download and install a commercial connector - it should work because the connector will check to see if the key is installed in the kesytore via the licensing module
(OR i'm running the loopback connector and in production using strong-pm and the key is being passed to me via ENV var and magic string mechanism via Arc)
- [ ] Arc must "distribute" the key as an environment variable for all connected instances with the Process Manager

**Comment by chandadharap** [comment]
@rmg @sam-github for more input here.

- AFAIK the license module does not install a key. It decrypts a given license and returns the credentials. Please see here: https://github.com/strongloop/strong-license
- An api to pm is exposed so that Arc can get/set the env variable.

What was discussed: @ijroth @altsang 
In  the "easy" case of using commercial connectors using Arc, Arc will use the license module to validate the key (where ever it is stored)

In  the "hard" case of commercial connectors being used outside of Arc, the user is expected to set the license as a env variable or using slc --license (current Sprint)

**Comment by rmg** [comment]
In this context, Arc _is_ the central strongloop store, and it is responsible for passing out licenses by setting environment variables in processes it is controlling via strong-pm.

Users not wanting to use Arc for this will need to set the environment variables themselves.

**Comment by sam-github** [comment]
arc already has a store (its where it persists the Process Manager data), I don't think we should create another. I agree that it should be moved out of arc's CWD, and into the user's home directory.

Note that it couldn't literally be "in the strongloop package", because packages have no persistent storage, and aren't installed on a writeable FS location (by default). The store would go in `~/.strongloop/`, or in `~/.strong-arc` (bike shed alert!).

I can see some point to having the connectors, in the absence of an environment variable, look for a `~/.strongloop/` directory to see if there is a license there. Could be useful for dev mode, when running your app directly via `node`.

But... this is only useful if "lack of license" is going to lead to a "hard disable of the connector". Is that the intention? Because if the connector merely prints a warning message, or auto-stops in 2 hours, then it will work fine in dev mode.

Also ***scope creep alert***, this was not in the current plan, AFAICT. I think it should be pushed to next sprint, so we can finish the docker-based installation of strong-pm we need for "phoenix".

**Comment by altsang** [comment]
Cool.  I'm fine with re-using the JSON config for now and agree that it should be in some central location.
FYI - I wasn't literally thinking the sl package itself but a .strongloop dir under the strongloop package in node_modules globally or some place where we could easily reference it.  `~/.strongloop` makes sense and we can put in a story for that at a later point.

I wasn't aware of docker based install of strong-pm.  So this is strong-pm running within a docker container and will be part of the first iteration of phoenix?  If so I'll update my Mini-Mesh to Mesh progression.

**Comment by sam-github** [comment]
docker based install:

https://github.com/strongloop-internal/scrum-nodeops/issues/310  (details TBD, but not overall goal)

**Comment by chandadharap** [comment]
This is a duplicate story of one in the LB scrum board that was created last week. I'll consolidate and close this one.

**Comment by chandadharap** [comment]
Docker comment not related to this issue. FYI @raymondfeng

**Comment by chandadharap** [comment]
Where is this local file stored? TBD.

**Comment by altsang** [comment]
per our discussion yesterday the keystore will be implemented under ~/.strongloop (or something similar) and the wrapper that Ryan is building will check this default location, presumably be able to pass parameters for a path to the keystore
@raymondfeng, @rmg please confirm

**Comment by rmg** [comment]
I'm not sure what you mean by key store in this context. Normally that implies some sort of vault with encryption and/or access control with an API for storing and retrieving. Something like ssh-agent or a keychain daemon/service. 

My intention was for it to only check against a predefined set of environment variables that are set by Arc (via pmctl) or by the user (via pmctl or their own means). That was my understanding of the easy vs. hard paths. 

It could do files as well if what you mean by key store is actually just a human editable text file in a predefined location. Though in that case I'm not sure how the "key store" is a thing that needs to be "done".

I have a philosophical preference for information to be passed into a system explicitly, not implicitly via global state, in case anyone is wondering where I'm coming from. See also: immutable infrastructure, functional programming.

**Comment by altsang** [comment]
"Keystore" for now being human editable file in ~/.strongloop.  If it evolves into something like what ssh has in the future, it'll be more of a bonfide "keystore".  We don't want to have an extra step of  of the user having to set environment variables as the de-facto MO, unless necessary.  I view registering, logging in and downloading a key as "explicit" and I'm fine with being transparent on what and where it is storing that license key.  If they download a key in Arc, the embedded strong-pm and other commercial modules should work through the wrapper without adding more steps to the experience.

Note for production purposes - we can most certainly have a more explicit flow.  What I'm describing above is the default behavior for new users of Arc admittedly biased toward less friction in a getting started experience and needing to understand details they may not even care about beyond initial trial.

**Comment by rmg** [comment]
@altsang I think you misread. The only time the use would have to set an environment variable is if they are opting out of using Arc **and** opting out of using strong-pm.

My explicit vs. implicit was only about the behind-the-scenes implementation, not about the user's actions.

Both of the following scenarios have the **exact** same user experience, other than one having more places for bugs to creep in:

Explicit: Arc & PM set env var, agent/connector in App reads it.

1. Arc downloads a license from auth.
1. Arc stores the license somewhere (doesn't matter where, only Arc cares).
1. Arc gives the licenses to it's internal PM via `svc.setEnv()`
1. Arc gives the licenses to any remote PM instances via `svc.setEnv()`
1. agent/connector in App reads licenses from environment set via PM

Implicit: Arc & PM both read/write file at "globally accessible location", agent/connector in App reads from it (hope the contents don't change!)

1. Arc downloads a license from auth.
1. Arc stores the license in a very specific, "globally accessible location" that can't change.
1. Arc gives the licenses to it's internal PM via `svc.setEnv()`?
1. Arc assumes internal PM will read it via "globally accessible location"?
1. Arc gives the licenses to any remote PM instances via `svc.setEnv()`
1. PM sets environment variable?
1. PM writes to a local version of the "globally accessible location"?
1. agent/connector in App reads licenses from environment if set via PM
1. agent/connector in App reads licenses from hard-coded, presumably accessible, "globally accessible location"

Just to make sure it wasn't missed: Both of the above are the desired flow for our users, I'm only talking about the nitty gritty of the implementation.

**Comment by rmg** [comment]
The above details won't impact Arc users (UX is the same for both). It will impact the UX of people using the modules without running their app under PM. For that I'll defer to Sumitha for which of the above scenarios sounds easier to triage over email.

**Comment by altsang** [comment]
Ahhh - regarding the nitty gritty - I was thinking of what you have as the explicit flow and agree with it.  The only one difference is if you run a LB app with a commercial connector outside of strong-pm while on your de machine.

I was hoping for something like this...
1. Licensing module wrapper checks license env by default.
2. If not there, licensing module wrapper will check default keystore location - ~/.strongloop OR location specified by user if it was moved via optional path parameter passed by user

That way for the new user developing locally on Arc but not using strong-pm when running while performing dev would still be running.

For non-Arc and non-Strong-pm, their only recourse would be the flow you outlined.
