### ISSUE TITLE
Can't login to arc

### ISSUE THREAD

**Issue by rubentorresbonet** [strongloop/strong-arc#1070]
Since this morning, I get this error message when trying to login as usual through arc:

XMLHttpRequest cannot load https://auth.strongloop.com/api/users/login?include=user&. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:53950' is therefore not allowed access. The response had HTTP status code 502.

Any ideas? Thanks

**Comment by jlgallego** [comment]
Hello,

You are not alone. Same problem here. I even resetted password twice. 

Regards.

**Comment by yassineaouadi** [comment]
hello ,
same problem, resetted password , i can login  to strongloop website but not to  arc  with my application: Authentication attempt failed. Please check your username (email) and password and try again.

**Comment by seanbrookes** [comment]
please try again.  things should be fixed now.

**Comment by rubentorresbonet** [comment]
Thanks, it's now working.
