### ISSUE TITLE
Implement API analytics as a new module in Arc

### ISSUE THREAD

**Issue by chandadharap** [strongloop/strong-arc#1073]
Based on previous spike;

**Comment by chovy** [comment]
Here's the spec:

https://strongloop.atlassian.net/wiki/pages/viewpage.action?spaceKey=SL&postingDay=2015%2F3%2F9&title=API+Usage+Metrics+-+Arc+UX

**Comment by anthonyettinger** [comment]
Here's the spec: https://strongloop.atlassian.net/wiki/pages/viewpage.action?spaceKey=SL&postingDay=2015%2F3%2F9&title=API+Usage+Metrics+-+Arc+UX

**Comment by altsang** [comment]
updated yesterday with two distinct interactions - counts and trends
MVP is to implement counts with bars

**Comment by anthonyettinger** [comment]
- See https://github.com/strongloop/strong-mesh-models/pull/39 for samples
 - histogram example: http://bl.ocks.org/mbostock/1283663
 - @anthonyettinger added a mock server with 1 days worth of data
            `node test/mock-express-usage-record.js`
 - VC mockup: https://drive.google.com/folderview?id=0B1FTzkB7697Gd09PclJkZVNueFk&usp=sharing
 - Stacy's prototype: https://drive.google.com/folderview?id=0B1FTzkB7697GWHJOWXFWbXpTcTQ&usp=sharing

**Comment by chandadharap** [comment]
Note: Graphs and final designs came in Thursday. There are changes. Some scope increase.

**Comment by chandadharap** [comment]
Please update and re-estimate

**Comment by anthonyettinger** [comment]
Things to do

 - breadcrumb nav
- stacked bar chart

**Comment by chandadharap** [comment]
As of Friday, i believe this was functionally done? And the VD integration in Progress?
If so, we should move to Done, because we'll use the integration story to QA/Verify.
