### ISSUE TITLE
slc arc --licenses

### ISSUE THREAD

**Issue by altsang** [strongloop/strong-arc#1076]
If you run a commercial module (e.g. a LB app with loopback-connector-oracle) and the license module wrapper detects that you do not have a license either set by env var or not present in default keystore, there will be message printed out that you need to register/login to arc.

if you were told to simply run `slc  arc` you could startup where you last left off in the application by CTRL+C and it would be confusing.

Would be better if there was an explicit way to make sure you go straight to the login/register screen by telling the user to run `slc arc --login`

**Comment by chandadharap** [comment]
After due discussion, this means: redirect user to the exact point of "login" in Arc when you run "slc arc"

**Comment by altsang** [comment]
this has been supseded by strongloop/strong-arc#1078, it is now slc arc --licenses

**Comment by altsang** [comment]
chatted with @anthonyettinger - will wait till this is merged on master to verify once

**Comment by chandadharap** [comment]
Chandrika: wait for it to get on master,

**Comment by altsang** [comment]
@anthonyettinger - I can do `slc arc --licenses`, but is the fix in master so that after logging in it redirects to /licenses?

**Comment by altsang** [comment]
looks like there's a bug

steps to reproduce:
* run Arc, make sure you logout explicitly
* re-run from command line using `slc arc --licenses`
* prompted to login - but notice URL does not have `?ref=licenses`
* re-login but goes to landing page

**Comment by altsang** [comment]
verified on master
