### ISSUE TITLE
Process Manager: add license push capabilities to existing commands and add license push command

### ISSUE THREAD

**Issue by altsang** [strongloop/strong-arc#1080]
As a devops user using Process Manager, Process Manager is the only Arc module where licenses are pushed from Arc to strong-pm, and I would like to push licenses to my strong-pm instances.

The following strong-pm host commands on the drop down menu need a license push action preceeded before invoking the API:
- [ ] start
- [ ] restart

e.g. if the user chooses to restart the app within a strong-pm instance - then a license push is done first by setting an env var through the strong-pm API call with the concatenated license keys (lic1:lic2:lic3...), when setting env vars - the app is automatically restarted so no further command needs to ensue

e.g. if the app is already stopped on strong-pm, you can push the license, and then issue a command to start the app

e.g. cluster restart ***will not be able*** to pull down new licenses because setting the env var does a hard restart of the supervisor

a fourth menu option needs to be added that is the same as restart - `license-push`
- [ ] add license-push menu option, functionally it will do the same thing as restart

cc: @anthonyettinger, @rmg, @raymondfeng

**Comment by rmg** [comment]
The start, restart, and cluster restart behaviours described are consistent with how strong-pm currently behaves. :+1:

**Comment by altsang** [comment]
fantastic, thx @rmg 
i've emphasized the exception on cluster-restart just for good housekeeping

**Comment by anthonyettinger** [comment]
@rmg, @raymond @altsang -- i need some example api calls for this.

I was under the impression that start/restart automatically pushed a new license. But I may be wrong.

**Comment by rmg** [comment]
@anthonyettinger I'm not sure how you are accessing the API, but it is a remote method on Service instances called `setEnv`, so via HTTP by POST to `/api/Services/1/setEnv/STRONGLOOP_LICENSE` with a string or via JS api using something like `svcInstance.setEnv('STRONGLOOP_LICENSE', licenses.join(':'), ...);`

**Comment by anthonyettinger** [comment]
@rmg thanks. i'll take a look.

**Comment by altsang** [comment]
@raymondfeng I think you're back end is already intercepting these.  Should Anthony's front end simply call the restart API and you'll do the `setEnv` call on the Arc backend?

**Comment by altsang** [comment]
@anthonyettinger - assigning back to you per our conversation with @ritch and @raymondfeng on where the array of  host.action is coming from

**Comment by anthonyettinger** [comment]
working on a fix for --licenses bug

**Comment by altsang** [comment]
verified on master
