### ISSUE TITLE
Auth Service: need additional fields for product and feature friendly labels

### ISSUE THREAD

**Issue by altsang** [strongloop/strong-arc#1082]
As an Arc user, I would want to see what product and features I have licenses to with friendly names not the actual values for the Product and Feature fields

Please add additional field for Product and Features to have friendly names - 

e.g. metrics = feature, Metrics = label for metrics

cc: @anthonyettinger

**Comment by chandadharap** [comment]
This would be a good time to rename Metrics to Monitoring, the docs already
reflect that, the UI would change eventually,

does it make sense here as well?

On Wednesday, March 11, 2015, Al Tsang <notifications@github.com> wrote:

> As an Arc user, I would want to see what product and features I have
> licenses to with friendly names not the actual values for the Product and
> Feature fields
>
> Please add additional field for Product and Features to have friendly
> names -
>
> e.g. metrics = feature, Metrics = label for metrics
>
> cc: @anthonyettinger <https://github.com/anthonyettinger>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/strongloop/strong-arc/issues/1082>.
>


-- 
Chanda Dharap
Director, Engineering
@StrongLoop Inc
(510) 304-3924
chanda@strongloop.com

*StrongLoop <http://strongloop.com/>** makes it easy to **develop APIs
<http://strongloop.com/mobile-application-development/loopback/>** in Node,
plus get DevOps capabilities
<http://strongloop.com/node-js-performance/strongops/> like monitoring,
debugging and clustering**.*

**Comment by altsang** [comment]
think it would be better to create a separate story and have it referenced
by this one, but agree that we can change it now


On Wed, Mar 11, 2015 at 5:42 PM, chandadharap <notifications@github.com>
wrote:

> This would be a good time to rename Metrics to Monitoring, the docs already
> reflect that, the UI would change eventually,
>
> does it make sense here as well?
>
> On Wednesday, March 11, 2015, Al Tsang <notifications@github.com> wrote:
>
> > As an Arc user, I would want to see what product and features I have
> > licenses to with friendly names not the actual values for the Product and
> > Feature fields
> >
> > Please add additional field for Product and Features to have friendly
> > names -
> >
> > e.g. metrics = feature, Metrics = label for metrics
> >
> > cc: @anthonyettinger <https://github.com/anthonyettinger>
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/strongloop/strong-arc/issues/1082>.
> >
>
>
> --
> Chanda Dharap
> Director, Engineering
> @StrongLoop Inc
> (510) 304-3924
> chanda@strongloop.com
>
> *StrongLoop <http://strongloop.com/>** makes it easy to **develop APIs
> <http://strongloop.com/mobile-application-development/loopback/>** in
> Node,
> plus get DevOps capabilities
> <http://strongloop.com/node-js-performance/strongops/> like monitoring,
> debugging and clustering**.*
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/strongloop/strong-arc/issues/1082#issuecomment-78403787>
> .
>



-- 
Al Tsang
Co-Founder and CTO @ StrongLoop, Inc.

*StrongLoop <http://strongloop.com/>** makes it easy to **develop APIs
<http://strongloop.com/mobile-application-development/loopback/>** in Node,
plus get DevOps capabilities
<http://strongloop.com/node-js-performance/strongops/> like monitoring,
debugging and clustering**.*
