### ISSUE TITLE
styleguide retrofit: alignment is off after text input retrofit

### ISSUE THREAD

**Issue by altsang** [strongloop/strong-arc#1085]
As an Arc user I'm looking for consistency of alignment because it makes for a product to feel polished.

Composer: `Is Id`, `Required` and `Index` labels and checkboxes seems to be aligned differently.

![image](https://cloud.githubusercontent.com/assets/2261105/6670957/2bb9c30e-cbbf-11e4-9bfd-dc6a34a18bb0.png)

Build and Deploy: labels on top of input field boxes are flush with input field on the left, but I believe they should be slightly indented as in the Composer? or maybe the other way around?

![image](https://cloud.githubusercontent.com/assets/2261105/6671012/9405025c-cbbf-11e4-9067-287c5fdb2864.png)

Process Manager: `Load Balancer` link button is not aligned when no row is present

![image](https://cloud.githubusercontent.com/assets/2261105/6671043/daf3b19a-cbbf-11e4-89ed-27eab313036d.png)

after row insertion the `Load Balancer` link looks fine but the `PIDs` label is flush against the border

![image](https://cloud.githubusercontent.com/assets/2261105/6671053/ec148f80-cbbf-11e4-8287-32529efc5fc9.png)

Metrics: `Hostname`, `Port`, `Load` button, labels on top of input field boxes are flush to the left, not sure if it should be slightly indented as in the Composer?  `Load` button seems not vertically aligned with the input field boxes

![image](https://cloud.githubusercontent.com/assets/2261105/6671140/93e6cbba-cbc0-11e4-9332-f8d343256ba3.png)

Profiler: same as above in Metrics on the PID selector

![image](https://cloud.githubusercontent.com/assets/2261105/6671165/c126a8fc-cbc0-11e4-88f2-2759531eedda.png)

**Comment by altsang** [comment]
@jtary - would like to review before we close these - please confirm this is in master?

**Comment by altsang** [comment]
![image](https://cloud.githubusercontent.com/assets/2261105/6884627/5bde7b5a-d5b1-11e4-924a-b5f350001a5e.png)

![image](https://cloud.githubusercontent.com/assets/2261105/6884680/bc82f4b8-d5b1-11e4-9bc6-c4cd47256ec3.png)

@stacy-hunt @anthonyettinger add new table row - is this a button now? pls confirm I see the same thing on Process Manager which is consistent which is good, but the style has changed?

**Comment by altsang** [comment]
@jtary pls see below 

- [ ] PID selector component (on Metrics and Profiler) text labels are not aligned the same as Composer, they are still flush left aligned with the textboxes underneath instead of just slightly indented, vertical alignment is good now
- [ ] radio buttons within Properties table in Composer should be center aligned in the cell, table header labels are good now

**Comment by jtary** [comment]
@altsang fixed up the issues with the alignment on the checkboxes and labels on the PID selector.

**Comment by altsang** [comment]
:+1: woohoo!  nice work @jtary thx
