### ISSUE TITLE
app controller: play button

### ISSUE THREAD

**Issue by altsang** [strongloop/strong-arc#1087]
As an Arc user I would want to know that centralized controls are somewhat intuitive to identify and recognize so that I can use them productively.

Have heard now on 2 accounts that the app control play button is not intuitive or recognizable and not prominent.

**Comment by stacy-hunt** [comment]
I'd like some more detail about what the users said if possible. Al, do you have more info - in which case I'd like to talk to you (text isn't suitable) or to the users if you can put me in touch with them.

**Comment by altsang** [comment]
Issac - copied you on the latest one, you can chat with @dashby3000 on the context, but it sounded like it he was going over Arc in a demo or something and folks are lost on what he's referring to on the screen?

![image](https://cloud.githubusercontent.com/assets/2261105/6715755/e1d029fe-cd5d-11e4-8fbe-fcc44e468ecb.png)

Jorem, a Swedish user of LB, when I asked first impression of what that button is or does - he had no clue.  When I showed him the YouTube button he immediately knew what it would do - 
![image](https://cloud.githubusercontent.com/assets/2261105/6715797/2ceb9662-cd5e-11e4-8857-776dffc3f225.png)

suggestion would be to leave it as just `play` and not worthy about `stop`

**Comment by stacy-hunt** [comment]
Al, I can't find Dennis in the Strongloop Slack pool. How do you normally
chat with him? Do you have a Skype username or something?

**Comment by chandadharap** [comment]
Add to the list here, there are some internal devs who also got confused
when we were debugging something else.
Sam, Miroslav are a couple I know first hand.

I agree with Al. The YouTube play button is unambiguous, has a universal
meaning thats well accepted..


On Fri, Mar 20, 2015 at 10:30 AM, stacy-hunt <notifications@github.com>
wrote:

> Al, I can't find Dennis in the Strongloop Slack pool. How do you normally
> chat with him? Do you have a Skype username or something?
>
> On 18 March 2015 at 11:02, Al Tsang <notifications@github.com> wrote:
>
> > Issac - copied you on the latest one, you can chat with @dashby3000
> > <https://github.com/dashby3000> on the context, but it sounded like it
> he
> > was going over Arc in a demo or something and folks are lost on what he's
> > referring to on the screen?
> >
> > [image: image]
> > <
> https://cloud.githubusercontent.com/assets/2261105/6715755/e1d029fe-cd5d-11e4-8fbe-fcc44e468ecb.png
> >
> >
> > Jorem, a Swedish user of LB, when I asked first impression of what that
> > button is or does - he had no clue. When I showed him the YouTube button
> he
> > immediately knew what it would do -
> > [image: image]
> > <
> https://cloud.githubusercontent.com/assets/2261105/6715797/2ceb9662-cd5e-11e4-8857-776dffc3f225.png
> >
> >
> > suggestion would be to leave it as just play and not worthy about stop
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/strongloop/strong-arc/issues/1087#issuecomment-83100503
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/strongloop/strong-arc/issues/1087#issuecomment-84080852>
> .
>



-- 
Chanda Dharap
Director, Engineering
@StrongLoop Inc
(510) 304-3924
chanda@strongloop.com

*StrongLoop <http://strongloop.com/>** makes it easy to **develop APIs
<http://strongloop.com/mobile-application-development/loopback/>** in Node,
plus get DevOps capabilities
<http://strongloop.com/node-js-performance/strongops/> like monitoring,
debugging and clustering**.*

**Comment by stacy-hunt** [comment]
We have a UX meeting at 3pm today, so I guess we can put it on the agenda

**Comment by stacy-hunt** [comment]
How's this?

![image](https://cloud.githubusercontent.com/assets/1924932/7193652/fb951726-e4f7-11e4-9e52-c6d06beb68e9.png)

**Comment by seanbrookes** [comment]
I like

On Thu, Apr 16, 2015 at 4:50 PM, stacy-hunt <notifications@github.com>
wrote:

> How's this?
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/1924932/7193652/fb951726-e4f7-11e4-9e52-c6d06beb68e9.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/strongloop/strong-arc/issues/1087#issuecomment-93863861>
> .
>



-- 
*StrongLoop <http://strongloop.com/>** makes it easy to **develop APIs
<http://strongloop.com/mobile-application-development/loopback/>** in Node,
plus get DevOps capabilities
<http://strongloop.com/node-js-performance/strongops/> like monitoring,
debugging and clustering**.*

**Comment by altsang** [comment]
this looks great, thx @stacy-hunt, do we have a story to implement?
