### ISSUE TITLE
Spike on API Metrics: store API metrics in browser for hour and day usage

### ISSUE THREAD

**Issue by altsang** [strongloop/strong-arc#1090]
As an business analyst or devops engineer, I want to be able to see at least 1 hour worth of api invocation data in Arc, so that I can get an idea of  usage per endpoint at the model level.

This is currently considered to be in a separate module from Metrics for full UX - https://strongloop.atlassian.net/wiki/display/SL/2015/03/09/API+Usage+Metrics+-+Arc+UX
The strong-pm collector will store and aggregate metric counts every 5 minutes.  This will yield 12 points per hour.  This will be kept in memory.  

- [ ] If Arc connects to the strong-pm and there is an hour of data - we want to go ahead and display this if Arc's local store is empty
- [ ] if Arc connects to strong-pm and there is an hour of data - we want to consolidate this with Arc's local store if there is data already there - i.e. a diff and display what is new
- [ ]  if the agent goes away, then it is at _LEAST_ 5 minutes before the next interval to avoid this - we would want to be able to show Metrics data for API without having to wait for 5 minutes.
- [ ] we want Arc to aggregate 1 day's worth of data and store on browser

@chandadharap - I put @jtary for now because @seanbrookes is on Tracing, pls assign an owner when appropriate

**Comment by chandadharap** [comment]
Thanks @altsang Assigned back to Anthony, who was original assignee.

**Comment by altsang** [comment]
based on last discussion with @kraman - storing this will purely be cached, @kraman will aggregate at 5min, 1 hr, and 1 day, we will dump the raw metric data for Level 3 if the memory consumption because too high

**Comment by Setogit** [comment]
1 day aggregation is tricky because it depends on timezone.  Customers in Europe wouldn't appreciate if we aggregate their data based on US Pacific Time.  What's about daylight saving time?  Concurix implemented world-wide timezone/daylight saving time-based aggregation in their Cassandra implementation.  We need to coordinate with the APM Central project.

**Comment by altsang** [comment]
This has been cancelled.  The aggregation will happen on the server, we can discuss thx
