### ISSUE TITLE
Verification of all use cases for Entitlement

### ISSUE THREAD

**Issue by chandadharap** [strongloop/strong-arc#1091]

**Comment by chandadharap** [comment]
Add use cases here from Al's doc (to do for Chanda)

**Comment by cgole** [comment]
Features -

New user - 

   * Default subscriptions
   * Add subscriptions
   * Change subscription
   * Expired subscription
   * Cancel subscription
   * Automatic subscription update
   * Renew subscription

Existing user -

   * Default subscriptions 
   * Add subscription - 
   * Change subscription
   * Expired subscription
   * Cancel subscription
   * Automatic subscription update
   * Renew subscription

PM on remote server -

     Publish license through arc - FAILING (https://github.com/strongloop/strong-arc/issues/1154) 
   * Valid license
   * Invalid license
   * Expired license

     Environment variable STRONGLOOP_LICENSE 
   * Valid license
   * Invalid license
   * Expired license

Products & features -
Studio - 
   * studio
Agent
   * metrics
   * watchdog
Admin
   * admin
Arc
   * composer
   * build-deploy
   * process-manager
   * metrics
   * profiler
   * advisor
Softlayer
   * softlayer
Gateway
   * oauth2
   * rate-limiting
   * proxy
   * metrics
Connectors
   * oracle
   * mssql
   * soap

**Comment by cgole** [comment]
@raymondfeng, @rmg, let me know if I am missing any test cases.

**Comment by rmg** [comment]
Looks reasonably complete to me.

**Comment by sam-github** [comment]
@kraman says that @cgole verified this - closing.
