### ISSUE TITLE
Spike: Figure out the graphing needs for a new API metrics module in Arc

### ISSUE THREAD

**Issue by chandadharap** [strongloop/strong-arc#1093]
API metrics did not fit into the paradigm of the existing metrics module on arc, which makes the assumption that the data coming is is all the same form. 

Needs icon etc @altsang,

**Comment by anthonyettinger** [comment]
@kraman need those example API calls and responses.

**Comment by stacy-hunt** [comment]
Visual Comp:

![Uploading image.png . . .]()

**Comment by chandadharap** [comment]
status please?

**Comment by chandadharap** [comment]
Spoke with Al, everyone in sync.. closing the Spike.
