### ISSUE TITLE
Spike: To detect local pm (via slc start)

### ISSUE THREAD

**Issue by chandadharap** [strongloop/strong-arc#1098]
Is it possible to detect that slc start was used to start a local pm in the current project? 

If is absolutely small effort, check in with  the group and implement. If its not, then identify what are the missing pieces and create stories to break it down further.

Front-end use case:
If Arc detects that a local PM is running (via ‘slc start’) it will automatically add this to the list of local PMs. This will allow the local-pm to be easily selected for metrics and tracing, and automatically show it on the PM selection widget.

**Comment by jtary** [comment]
Preliminary investigation shows this should be possible using existing API. All the required information is available via ./strong-pm/pmctl (current used for slc ctl status).

For implementation we'll need to modify our UX slightly to accommodate the various other factors surrounding using a full-pm, and to avoid conflicts and user-confusion with the build app-runner.

I'll create new stories for the UX changes and full implementation.

**Comment by jtary** [comment]
#1161 - Story for UX Changes
#1162 - Story for implementation

**Comment by chandadharap** [comment]
The two stories are a bit empty. The result of the Spike should have some details of implementation. And the UX story needs details. Maybe something like in the Description.

**Comment by sam-github** [comment]
Also, the stories need time estimates, and if there are options, then time estimates per option.

**Comment by chandadharap** [comment]
Commented on #1162 - Story for implementation, PTAL.

**Comment by chandadharap** [comment]
Created #1185, #1186, #1187
