### ISSUE TITLE
Process Manager: delete icon needs to be more prominent

### ISSUE THREAD

**Issue by altsang** [strongloop/strong-arc#1107]
As a SL Arc user using Process Manager, it's not intuitive how I can delete a row, I would want a more intuitive UX to have the control available to delete a row but not clutter the UI.

- current hover behavior shows "x", suggest turning into "(x)" with the circle upon hover, not just highlighted row

- [ ] UX and VD needs to be updated
- [ ] change needs to be implemented to Process Manager row - suggest checking for consistency behavior in our table rows like Composer Model Properites

this is a subset of related #1058 retrofit tables

/cc: @anthonyettinger, @stacy-hunt

**Comment by stacy-hunt** [comment]
I really like the way this is presented as a description of the problem
followed by a suggestion. That format really facilitates the design
process, thanks.

**Comment by stacy-hunt** [comment]
Proposed design change to the delete icon:

**Comment by altsang** [comment]
LGTM implementation in styleguide and retrofit in #1198

**Comment by altsang** [comment]
any other comments @anthonyettinger, @seanbrookes, @jtary? closing out to mark done in sprint
