### ISSUE TITLE
styleguide add error state and update default color for help icons

### ISSUE THREAD

**Issue by anthonyettinger** [strongloop/strong-arc#1119]

**Comment by stacy-hunt** [comment]
![image](https://cloud.githubusercontent.com/assets/1924932/6933243/18b99f08-d881-11e4-863b-14c6ba921f85.png)

Help icons currently use fontIcons, and have to be solid colour. Eventually We'll replace them with SVG graphics, at which time I'd like to move back to the outlined ones which are more lightweight.

**Comment by stacy-hunt** [comment]
I think that the help icons currently in the style guide look a little small. They seem to be about 16pt wide, but I'd try bumping them up to 20. Also, check the font for the error label against this comp, it seems a little small and the value of the red might not be quite right:

![image](https://cloud.githubusercontent.com/assets/1924932/6956233/4d4518c6-d947-11e4-9af0-2b5ab5ba09b3.png)

**Comment by altsang** [comment]
looks good to me, @stacy-hunt pls verify

**Comment by stacy-hunt** [comment]
It still looks the same to me, I think I must not have the latest though I followed instructions for updating. Troubleshooting with Anthony.

**Comment by altsang** [comment]
@stacy-hunt did you get this squared away?

**Comment by stacy-hunt** [comment]
Yep we got it sorted. The icing on the cake would be to have the icon centre-aligned horizontally with the label (currently it's bottom aligned). Anthony said it might not be too easy but he'll have a go. It's not critical so we can tick this card off as complete.
