### ISSUE TITLE
arc process manager status shows incorrect status

### ISSUE THREAD

**Issue by cgole** [strongloop/strong-arc#1129]
Connect to strongloop/strong-arc#1199

Always shows as "Problem" even when app is deployed and running. 

![screen shot 2015-04-01 at 4 04 18 pm](https://cloud.githubusercontent.com/assets/991632/6954686/51b7bb0c-d889-11e4-80d9-03829fd0f4ae.png)

**Comment by cgole** [comment]
closing this. something I did earlier was wrong. It seems to be working now

**Comment by cgole** [comment]
This is an issue with slc on staging - 

$ slc --version
strongloop v3.0.10 (node v0.10.38)
├── strong-arc@1.1.104 (8e3582a)
├── strong-build@1.0.7 (2e6d0b3)
├── strong-deploy@1.1.29 (771309d)
├── strong-pm@3.1.37 (e6bb4a2)
├── strong-registry@1.1.6 (6283ba9)
├── strong-start@1.0.14 (a90857d)
├─┬ strong-supervisor@1.4.53 (2c388d9)
│ └── strong-agent@1.3.19
├── generator-loopback@1.9.1 (b90e9cd)
├── node-inspector@0.7.4
└── nodefly-register@0.3.3

**Comment by chandadharap** [comment]
Chandrika confirms this is still a bug.

**Comment by seanbrookes** [comment]
I have seen it as well

**Comment by jtary** [comment]
It looks like the problem is that the 'app' value returned by the API call to ManagerHosts is null, even though there is an app running

**Comment by jtary** [comment]
Put a work around into arc and mesh-client so that the status shows correctly again. A more proper fix is need in the PM, which will go in as part of https://github.com/strongloop-internal/scrum-nodeops/issues/497

**Comment by cgole** [comment]
verified
