### ISSUE TITLE
Watchdog: finalize UX and VD watchdog in Profiler

### ISSUE THREAD

**Issue by altsang** [strongloop/strong-arc#1139]
As a SL devops user of Arc using profiler, I would like to be able to define and create watchdogs on PIDS to auto-profile based on threshold.

last time this feature was visited...
VD: https://drive.google.com/drive/folders/0B1FTzkB7697GYm9HdVNxOFIzVzg/0B1FTzkB7697GUTBfbWpOak5HcGc/0B1FTzkB7697GOFhvSGgzb2Rickk/0B1FTzkB7697GZ3duVXdRVWFmVkE/0B1FTzkB7697GVlh2Mnd0bEdDczQ/0B1FTzkB7697GOGU4UFQxRDFWZUk

UX: https://drive.google.com/drive/folders/0B1FTzkB7697GYm9HdVNxOFIzVzg/0B1FTzkB7697GUTBfbWpOak5HcGc/0B1FTzkB7697GOFhvSGgzb2Rickk/0B1FTzkB7697GZ3duVXdRVWFmVkE/0B1FTzkB7697GVlh2Mnd0bEdDczQ/0B1FTzkB7697GTl9nVUZkYkd1anM

related:
backend - #1141
frontend - #1139

**Comment by stacy-hunt** [comment]
I assume this will come up for discussion in today's standup meeting right? I know what the feature is, just not sure what the design requirements are at this stage.

**Comment by altsang** [comment]
yeah we can cover in the next meeting, it's been a while since the last
time we visited this

On Thu, Apr 2, 2015 at 1:40 PM, stacy-hunt <notifications@github.com> wrote:

> I assume this will come up for discussion in today's standup meeting
> right? I know what the feature is, just not sure what the design
> requirements are at this stage.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/strongloop/strong-arc/issues/1139#issuecomment-89039863>
> .
>



-- 
Al Tsang
Co-Founder and CTO @ StrongLoop, Inc.

*StrongLoop <http://strongloop.com/>** makes it easy to **develop APIs
<http://strongloop.com/mobile-application-development/loopback/>** in Node,
plus get DevOps capabilities
<http://strongloop.com/node-js-performance/strongops/> like monitoring,
debugging and clustering**.*

**Comment by altsang** [comment]
@stacy-hunt according to NodeOps team you would want to probably default setting watchdog globally rather than by PID unless you were reacting to something in Metrics

**Comment by stacy-hunt** [comment]
OK - but we still want to have the functionality to adjust settings by PID
if the user wants to as well, right?

**Comment by altsang** [comment]
Yes- definitely

**Comment by chandadharap** [comment]
Should this be assigned to Al?

**Comment by stacy-hunt** [comment]
Possibly assign it to Joe for now. We finished the design this week without Al, but he had approved of where we were going with it. Joe's building it already.
