### ISSUE TITLE
UX: Ability to define CPU thresholds on Arc

### ISSUE THREAD

**Issue by chandadharap** [strongloop/strong-arc#1142]
As a SL devops user of Arc using profiler, I would like to be able to define and create CPU thresholds on PIDS  which will automatically trigger a CPU profile.

UX: https://drive.google.com/drive/folders/0B1FTzkB7697GYm9HdVNxOFIzVzg/0B1FTzkB7697GUTBfbWpOak5HcGc/0B1FTzkB7697GOFhvSGgzb2Rickk/0B1FTzkB7697GZ3duVXdRVWFmVkE/0B1FTzkB7697GVlh2Mnd0bEdDczQ/0B1FTzkB7697GTl9nVUZkYkd1anM

**Comment by altsang** [comment]
this is actually already been considered, closing
