### ISSUE TITLE
Add targeted-dialog component to styleguide

### ISSUE THREAD

**Issue by chandadharap** [strongloop/strong-arc#1144]
Integrate UX and finalized VD

**Comment by chandadharap** [comment]
As a SL devops user of Arc using profiler, I would like to be able to define and create CPU thresholds on PIDS which will automatically trigger a CPU profile.

UX: https://drive.google.com/drive/folders/0B1FTzkB7697GYm9HdVNxOFIzVzg/0B1FTzkB7697GUTBfbWpOak5HcGc/0B1FTzkB7697GOFhvSGgzb2Rickk/0B1FTzkB7697GZ3duVXdRVWFmVkE/0B1FTzkB7697GVlh2Mnd0bEdDczQ/0B1FTzkB7697GTl9nVUZkYkd1anM

**Comment by altsang** [comment]
@stacy-hunt this is in the style guide now, assigning to you to verify...

per @jtary
>I guess maybe that would be more of a Stacy thing. It’s in styleguide for master, so he can check it out now and drill-down into it a bit.

**Comment by chandadharap** [comment]
@stacy-hunt Can we please close?

**Comment by stacy-hunt** [comment]
Yep, just made a few tweaks to it with Anthony and checked consistency with the other dialogs. It's good to go now.
