### ISSUE TITLE
Ability to "smart" CPU profiling based on defined threshold and cycle count

### ISSUE THREAD

**Issue by chandadharap** [strongloop/strong-arc#1145]
Ability to auto-trigger Profiling based on defined CPU threshold. 
- [ ] This will require integration with existing pm models api.

**Comment by jtary** [comment]
- [] square off the corners of the dialog components

**Comment by stacy-hunt** [comment]
Visual Comp
- The popup dialog shown will be added to the styleguide in card 1209
![image](https://cloud.githubusercontent.com/assets/1924932/7402509/b4bdac72-ef20-11e4-9cd8-5adfbe1abc63.png)

![image](https://cloud.githubusercontent.com/assets/1924932/7402515/c93e6826-ef20-11e4-91d5-80ff895e38ff.png)

**Comment by altsang** [comment]
thx @stacy-hunt!

@jtary we will want the "pop-up" box as a augmentation of the existing component for drop down box dialoges or something new for the styleguide per our discussion

**Comment by altsang** [comment]
@stacy-hunt we'll want to be consistent on the labels and messaing:

`Smart` and `Full`

can you please change the choice slider to `Full`? and the border less button that says `Limited Profile 1000ms` to `Smart Profile 1000ms`
thx!

**Comment by stacy-hunt** [comment]
I'm going to be making a card for that new dialog today - but Al, just to
confirm, when you say "drop down" you mean "pop-up" right?

**Comment by stacy-hunt** [comment]
Yeah good catch thanks Al. I should have noticed that myself... I've
updated the comps.

**Comment by altsang** [comment]
sorry - bad bad terminology - yes "pop-up", thx

**Comment by cgole** [comment]
Tested this once and it did work.  
To test this 
run the trace memory leak app
Run load - for ((i=1;i<=10000000;i++)); do   curl -v --header "Connection: keep-alive" -d "content"="Test" http://localhost:3001/api/Documents/content;done

install statsd
start pm and write metrics to statsd
Observer the loop count max for serveral loops as the data comes in to statsd
lets say, the loop count is over 20 consistently
IN smart profiling UI set the number to 10. and run profiling. This means, whenever the loop count is more than 10  profiling is run..

**Comment by chandadharap** [comment]
Will need Rand's help to QA.

**Comment by crandmck** [comment]
Here is a summary of the QA procedure I followed: https://strongloop.atlassian.net/wiki/display/SL/Smart+Profiling+QA+procedure

At this point, it seems to generate profiles inconsistently, which may be due to   https://github.com/strongloop-internal/scrum-nodeops/issues/753.  Currently, verification of this feature is blocked by that.

**Comment by sam-github** [comment]
passing back to @cgole

**Comment by cgole** [comment]
verified this works, but keeping this story open  for full QA for smart profiling.
