### ISSUE TITLE
Doc updates for Smart Profiling

### ISSUE THREAD

**Issue by chandadharap** [strongloop/strong-arc#1146]
This is watchdog (aka "Threshold based profiling", "Triggered profiing") being added to Arc.

**Comment by crandmck** [comment]
When ready to document, add to http://docs.strongloop.com/display/SLC/Triggered+CPU+profiling+with+Arc (hidden draft).

**Comment by crandmck** [comment]
NOTE: I already renamed the existing feature (as used with `slc`) in the docs.

**Comment by crandmck** [comment]
This is done and ready for review.

**Comment by kraman** [comment]
Description of how smart profiling works looks fine.
