### ISSUE TITLE
Dev blog on Threshold based profiling

### ISSUE THREAD

**Issue by chandadharap** [strongloop/strong-arc#1147]
Perhaps you can use the profiler demo app as an example.

**Comment by chandadharap** [comment]
@jtary Is this ready? i don't  have a link. Please add here.

**Comment by jtary** [comment]
https://docs.google.com/document/d/1MHLEJBTaA_9QQ8d8NqeyDzdfXRYSjC6DeArwsz1ajC8/edit#heading=h.qbgc9wxdgn0o

**Comment by chandadharap** [comment]
Jimmy has queued it up for 8/4. we can close. (and we can release code when we are ready)
