### ISSUE TITLE
Metrics charts dont load at all

### ISSUE THREAD

**Issue by cgole** [strongloop/strong-arc#1148]
![screen shot 2015-04-02 at 1 45 55 pm](https://cloud.githubusercontent.com/assets/991632/6973326/db9a5c48-d93e-11e4-90c0-c58abd7564a2.png)

I can  get metrics to report to statsd so license is valid and working

**Comment by jtary** [comment]
@cgole what is the host you're connecting to? It seems to work fine for me when I connect to my local PM.

**Comment by cgole** [comment]
@jtary app controller is broken for me because of #1138. My app is deployed to a remote pm (ec2 vm)

**Comment by cgole** [comment]
cannot repro
