### ISSUE TITLE
Integrate Traces module with Entitlement workflow in Arc

### ISSUE THREAD

**Issue by chandadharap** [strongloop/strong-arc#1149]
- [ ] First time Traces user might land on Traces and see no data. Does this need appropriate messaging?
- [x] Need traces license for auth.sl to be published by Raymond

**Comment by altsang** [comment]
@anthonyettinger make sure that tracing is part of the path

**Comment by chandadharap** [comment]
https://github.com/strongloop-internal/scrum-nodeops/issues/431

**Comment by chandadharap** [comment]
@altsang strong-trace already uses license module, a sprint or more ago. And it works as expected. Sean created this story for front-end messaging. Hope thetre isnt any confusion.

**Comment by seanbrookes** [comment]
I used the same component / service as the metrics notification and things seem to work ok but I commented out the validation check as I don't know how to generate a valid license

**Comment by altsang** [comment]
@chandadharap, @jtary , @sam-github , @anthonyettinger @sumitha, @crandmck 

same caveats for Tracing

please see - https://github.com/strongloop/strong-arc/issues/1216#issuecomment-98582359

**Comment by seanbrookes** [comment]
seems this story still has some legs.
- we still need some messaging to the user for the case where they have a valid license key but still don't see traces data
- could be exception
- traces turned off
- app is not sending data
- very first time the user hits the module

**Comment by altsang** [comment]
yep, @seanbrookes - https://github.com/strongloop-internal/scrum-nodeops/issues/547 FYI

**Comment by chandadharap** [comment]
@seanbrookes The above list you pointed out is basic Failure handling in teh app. Lets make a new story.

**Comment by chandadharap** [comment]
I created a new story for basic failure handling  that is not related to licensing,

**Comment by chandadharap** [comment]
Done.
