### ISSUE TITLE
Implement finalized VD into Traces

### ISSUE THREAD

**Issue by chandadharap** [strongloop/strong-arc#1150]
Link to Specs needed here.

**Comment by altsang** [comment]
VD: http://bit.ly/19SOUp7

**Comment by chandadharap** [comment]
@altsang  Just to be clear, this is for the first release Im assuming.

**Comment by altsang** [comment]
correct - first iteration/release, VD only, no UX applied, don't need to spend cycles on this until we have a strategy for how API usage, Metrics and Tracing should be trued up

**Comment by seanbrookes** [comment]
notes from UX meeting to settle UX / VD loose threads
- header needs white background
- add heap to chart
- small chart to start
- cursor on chart
- select a timeframe to view available traces (label)
- transactions become traces string change
- traces from (on trace view)
- pointer open close on toggle views
- click to drill down
- triangle to open/close on trace view
- click to drill down on transaction sequence (on hover)
- breadcrumb - including app name

**Comment by chandadharap** [comment]
This was incorrectly estimated. Took between 8 to13 points.

**Comment by altsang** [comment]
ouch, thx for heads up

**Comment by altsang** [comment]
should this be assigned to @stacy-hunt to verification?

**Comment by chandadharap** [comment]
For this one I'm doing functional review because of how the pre-alpha implementation story was structured last Sprint. I'm also working with a few others for perf tuning, so yes, it  is me.

But to your point, I'll ask @seanbrookes to review with Stacy for VD during the UX meetings. I am ofcourse not reviewing Visual Design. Thanks for pointing that part out!

**Comment by chandadharap** [comment]
I had several difficulties with the  interaction with the UI and also understanding your list. 
Probably need a hangout and a screenshare so I can understand what these refer to:

What does selecting a timeframe refer to?
>select a timeframe to view available traces (label)

Below means what exactly?
>transactions become traces string change
> traces from (on trace view)

If  this is what I thin it is, its extremely buggy
>pointer open close on toggle views

I don't see any triangle
>triangle to open/close on trace view

Don't see a hover behavior either
>click to drill down on transaction sequence (on hover)

Moving back to make sure we circle back on this.

**Comment by seanbrookes** [comment]
we should review this together so I can explain but here is an attempt:
```
What does selecting a timeframe refer to?

select a timeframe to view available traces (label)
```
it is some label text to help the user know to click on the chart (as per Issac)

```
Below means what exactly?

transactions become traces string change
```
this is just a string change to move from 'transactions' to 'trace' terminology in the ui

```
traces from (on trace view)
If this is what I thin it is, its extremely buggy
```
this was the summary text when you start to drill down but has been replaced with the breadcrumb component to save vertical space on the trace view

```
pointer open close on toggle views
```
this is just the cursor style on the charts so they appear to be clickable

```
I don't see any triangle

triangle to open/close on trace view
```
the implementation is actually a plus sign/minus sign on the trace view - transaction sequence list

```
Don't see a hover behavior either

click to drill down on transaction sequence (on hover)
```
it's in the header of the component you are hovering on in the transaction sequence view

**Comment by chandadharap** [comment]
okay, got it. ill move to to close. but will make sure I review the sticky-ness of  the cursor with you later today.

**Comment by seanbrookes** [comment]
I'll give you a tour
