### ISSUE TITLE
Sync Tracing V1 with live styleguide

### ISSUE THREAD

**Issue by chandadharap** [strongloop/strong-arc#1151]

**Comment by seanbrookes** [comment]
this has started and will take a couple of sprints to work out the details with Anthony and Joe.  I can happen in parallel and shouldn't be considered a show stopper

**Comment by sam-github** [comment]
@chanda I pushed back into planning so we talk about it in planning. It looks like its an ongoing refactor that will happen as UI work goes on.

**Comment by chandadharap** [comment]
@altsang is this priority for a release?

**Comment by altsang** [comment]
not for release - but we need to true these up

**Comment by chandadharap** [comment]
@seanbrookes I have no comments to know if this was completed and closed or is there work still ongoing? Please add a comment before closing.

**Comment by seanbrookes** [comment]
Tracing was released using primarily components from the styleguide.  Not sure how much effor we want to spend working out what is 'one off' vs. what needs to be brought back into the styleguide from the ui
