### ISSUE TITLE
Create landing page icon-badge for the Traces module in Arc

### ISSUE THREAD

**Issue by chandadharap** [strongloop/strong-arc#1152]

**Comment by stacy-hunt** [comment]
![image](https://cloud.githubusercontent.com/assets/1924932/7210945/2a13272a-e5aa-11e4-814e-14f671e18b43.png)

![image](https://cloud.githubusercontent.com/assets/1924932/7210948/3546b512-e5aa-11e4-822d-42a9fa5fd78a.png)
