### ISSUE TITLE
Implementation of Context based help for Traces.

### ISSUE THREAD

**Issue by chandadharap** [strongloop/strong-arc#1153]
https://drive.google.com/drive/folders/0B7cRRPpbtkFKflBybVZfOXEtSUpPTG44d2J1WW1MMmVDejlWSG44Rmhwc0R5REhkR25tMTA/0B7cRRPpbtkFKfmU5LXY1Q2o4NHowUUlzOTQzTTNMZnBibjVrYXpWUFlIVmxNdEUxZ21WbE0

**Comment by crandmck** [comment]
Here are the IDs you will need: http://docs.strongloop.com/display/ARC/User+assistance+pages#Userassistancepages-Traces

**Comment by seanbrookes** [comment]
initial feedback on the topic list:
- CPU and memory consumption	6718806 - this is really a 'trace timeline navigation' component that happens to show memory and cpu metrics so we might want to adjust the title/context of this topic
- Event loop summary statistics	6718810 - this should be broken into 2 distinct topics:
    - Event Loop is a specific compoent of the module
    - Trace Summary is a section in the second level with a table and pie charts to help contextualize the particular trace the user has clicked on

**Comment by seanbrookes** [comment]
I'm thinking there should be a top-level topic describing the tracing feature and IA - is that baked in somewhere else?

**Comment by crandmck** [comment]
> I'm thinking there should be a top-level topic describing the tracing feature and IA - is that baked in somewhere else?

Not sure what IA is (information architecture?), but the docs will have a general description of tracing and the UA (help) will link to that.

**Comment by seanbrookes** [comment]
1) yes there will be 2 different icons in the UI
2) ok, I think there is still outstanding work to be done to contextualize the 'global' help link. probably should be a separate story

**Comment by chandadharap** [comment]
By contextualize if you mean: add content to Document Traces, there is a
story for documenting Traces in docs.*.
You should just create an icon for this global link and not need another
story.



On Wed, Apr 22, 2015 at 11:40 AM, Sean Brookes <notifications@github.com>
wrote:

> 1) yes there will be 2 different icons in the UI
> 2) ok, I think there is still outstanding work to be done to contextualize
> the 'global' help link. probably should be a separate story
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/strongloop/strong-arc/issues/1153#issuecomment-95296225>
> .
>



-- 
Chanda Dharap
Director, Engineering
@StrongLoop Inc
(510) 304-3924
chanda@strongloop.com

*StrongLoop <http://strongloop.com/>** makes it easy to **develop APIs
<http://strongloop.com/mobile-application-development/loopback/>** in Node,
plus get DevOps capabilities
<http://strongloop.com/node-js-performance/strongops/> like monitoring,
debugging and clustering**.*

**Comment by crandmck** [comment]
> 2) ok, I think there is still outstanding work to be done to contextualize the 'global' help link. probably should be a separate story

Ah, I think I understand what you're talking about now.  The "global" help link for each module, e.g. for PM:  http://screencast.com/t/th5pDJkmuK
There should be one for Traces as well, of course.  I would think that would be covered by this story, but you could create a separate one if you wish.

**Comment by seanbrookes** [comment]
I don't think the 'global help' link in Arc has been mofied to provide links specific to the current module you have open.  That is work that needs to be done

**Comment by seanbrookes** [comment]
I stand corrected.  the global documentation link in Arc is wired up to the current module.  great news
