### ISSUE TITLE
entitlement bug - license publish through arc process manager not working

### ISSUE THREAD

**Issue by cgole** [strongloop/strong-arc#1154]
Looks like arc is sending the license keys and pm is receiving it, but the environment variable STRONGLOOP_LICENSE is not getting set

console  log from arc - 
 https://gist.github.com/cgole/85bdcef55c372a6b58c6

**Comment by kraman** [comment]
Took a look at the instance you were using and looks like the env is being passed down correctly.

**Comment by cgole** [comment]
@kraman, but agent still doesnt seem to pick it up. 
I still see "strong-agent agent metrics license not found, local reporting disabled."

**Comment by rmg** [comment]
strong-agent's licensing code was written before we added multiple license support. To be added in strongloop/strongops#258

**Comment by rmg** [comment]
Fix has been merged. @cgole you should be able to verify from staging shortly.

**Comment by cgole** [comment]
verified
