### ISSUE TITLE
Metrics: UX tune up, remove nav bar, and move controls to chart

### ISSUE THREAD

**Issue by altsang** [strongloop/strong-arc#1156]
As a SL Arc user using Metrics, the nav bar and the titles are now separated and not intuitive, I would like to see a better way of correlating the two.

enhanced UX and VD: https://drive.google.com/open?id=0B1FTzkB7697GRFhMSkd1dGhuNm8&authuser=0

**Comment by chandadharap** [comment]
This was not discussed during +1, I'll prefer to move it to next SPrint.

**Comment by stacy-hunt** [comment]
Design Review Feedback:

There are some alignment issues with the PID selector

**Comment by chandadharap** [comment]
@stacy-hunt  Can this be verified before Monday morning please, I'd like to close out Sprint on Monday.

**Comment by stacy-hunt** [comment]
Yeah it's good to go.
