### ISSUE TITLE
Arc-Start: Implementation

### ISSUE THREAD

**Issue by jtary** [strongloop/strong-arc#1162]
Makes the required changes to integrate Arc with the strong-mesh API to pmctl, and make the required UX changes to properly expose the functions to the user.

**Comment by jtary** [comment]
- Run "slc start" when user clicks run from the app controller
 - Auto-attach the running PM to the app controller when starting Arc
 - Add limited information from "slc ctl status" to app controller info window
 - Auto-detect running PM, and auto populate into the PM list
 - Change defaults for metrics and tracing to use local PM
 - Prompt user when logining out of Arc if PM is still running the app

**Comment by chandadharap** [comment]
Lets create as three stories as follows. If you can review  the break up and tell me if that makes sense or not, i can create.

Integrate with slc start:
- [ ] Run "slc start" when user clicks run from the app controller
- [ ] Auto-attach the running PM to the app controller when starting Arc
- [ ] Add limited information from "slc ctl status" to app controller info window

Populate PM
- [ ] Auto-detect running PM, and auto populate into the PM list

Update metrics module:
- [ ] Change defaults for metrics and tracing to use local PM
- [ ] Prompt user when logining out of Arc if PM is still running the app

**Comment by jtary** [comment]
@chandadharap Looks pretty good, though the "prompt" when exiting Arc isn't metrics specific, so it should probably be part of the first story. Updating the default probably should be changed in the profiling, metrics and tracing -- though tracing would require that the slc-start PM is added to the strong-mesh host list, so that could be a bit more complicated. I'll have to ask @seanbrookes about it when he gets back.

**Comment by chandadharap** [comment]
Captured in #1185, #1186, #1187
