### ISSUE TITLE
API Usage: UX

### ISSUE THREAD

**Issue by altsang** [strongloop/strong-arc#1166]
As a SL developer, I need to understand the UX so that I can prototype the interaction with Arc.

**Comment by altsang** [comment]
requirements: https://docs.google.com/a/strongloop.com/document/d/1xTHn-GC29yTiPjtKeM2HK4IaBla8YvoImU9PwUgD5bA/edit

@stacy-hunt to refine UX

**Comment by stacy-hunt** [comment]
I think this is covered by 1167 right?
