### ISSUE TITLE
Arc: menu item  fixes

### ISSUE THREAD

**Issue by altsang** [strongloop/strong-arc#1173]
As an Arc user, when I select a drop down menu, it should consistent casing and diction so that I understand what the option means without having to look up documentation.

Arc Process Manager:
- [x] change `cluster-restart` to `restart cluster`
- [x] change `license-push` to `push license`
- [x] change `Edit Host Environment` to `edit host environment`

standardizing on verb + noun(s)

Login/Power Button
- [x] change `Licenses` under power button to `licenses`
- [x] reorder - `login`, `logout`, `register`, `licenses`

/cc: @stacy-hunt, @anthonyettinger on UX

**Comment by altsang** [comment]
looks like we have a team decision on deprecating the direct usage of `host.action` called from the UI, we'll create a static list on the front end that does the mapping to the actions, this issue fixes the bifurcation of the front end item display

**Comment by chandadharap** [comment]
This isn't technically a bug, but a UX re-do. Removing the bug label.

**Comment by chandadharap** [comment]
assigning to @altsang

**Comment by altsang** [comment]
OSSM!  verified on master
