### ISSUE TITLE
Replace license check in strong-agent with license wrapper module

### ISSUE THREAD

**Issue by chandadharap** [strongloop/strong-arc#1179]
(Need for Entitlement release) For metrics and watchdog.

**Comment by rmg** [comment]
@chandadharap shouldn't this should be on strongloop-internal/scrum-nodeoops or strongloo/strongops instead of strongloop/strong-arc?

**Comment by chandadharap** [comment]
Whoops. I'll move/redo.

On Friday, April 10, 2015, Ryan Graham <notifications@github.com> wrote:

> @chandadharap <https://github.com/chandadharap> shouldn't this should be
> on strongloop-internal/scrum-nodeoops or strongloo/strongops instead of
> strongloop/strong-arc?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/strongloop/strong-arc/issues/1179#issuecomment-91754771>
> .
>


-- 
Chanda Dharap
Director, Engineering
@StrongLoop Inc
(510) 304-3924
chanda@strongloop.com

*StrongLoop <http://strongloop.com/>** makes it easy to **develop APIs
<http://strongloop.com/mobile-application-development/loopback/>** in Node,
plus get DevOps capabilities
<http://strongloop.com/node-js-performance/strongops/> like monitoring,
debugging and clustering**.*
