### ISSUE TITLE
Licensing: VD review

### ISSUE THREAD

**Issue by altsang** [strongloop/strong-arc#1181]
@stacy-hunt please review licensing key secondary action, I've already tested functionality

you must sync to master, gulp build and then run arc against myapp

**Comment by stacy-hunt** [comment]
DIALOG:
- The padding is too small
- The heading in the comp should not be bold; it's correct in the app, I'll amend the comp.
- The text area (that contains the key string) shouldn't have rounded corners
- The "Copy" and "OK" buttons should both be the same width
- "OK" should be all caps
- Remove the resize handle from the text area if possible. It's not needed and can get some screwed up appearances if you use it.
- The drop shadow is a little too intense. Try making it less opaque and / or increase the blur

TABLE:
- The padding at the top and the bottom of each row should be equal:
![image](https://cloud.githubusercontent.com/assets/1924932/7127909/1c2583be-e29f-11e4-954a-ee086b2505b9.png)
- The vertical line spacing is too small (compare to the comp)
![image](https://cloud.githubusercontent.com/assets/1924932/7127917/3f3c2268-e29f-11e4-9fd1-d3383979fafc.png)

**Comment by chandadharap** [comment]
@anthonyettinger to true this up
