### ISSUE TITLE
Integrate final VD comps for API Analytics

### ISSUE THREAD

**Issue by chandadharap** [strongloop/strong-arc#1187]

**Comment by chandadharap** [comment]
Is this an 8 point story?

**Comment by chandadharap** [comment]
Depending  on final VD comp,

**Comment by anthonyettinger** [comment]
- See https://github.com/strongloop/strong-mesh-models/pull/39 for samples
 - histogram example: http://bl.ocks.org/mbostock/1283663
 - @anthonyettinger added a mock server with 1 days worth of data
            `node test/mock-express-usage-record.js`
 - VC mockup: https://drive.google.com/folderview?id=0B1FTzkB7697Gd09PclJkZVNueFk&usp=sharing
 - Stacy's prototype: https://drive.google.com/folderview?id=0B1FTzkB7697GWHJOWXFWbXpTcTQ&usp=sharing

**Comment by anthonyettinger** [comment]
added icon to landing page.

**Comment by chandadharap** [comment]
I'm creating a separate story for QA with details on the spec @altsang created which outlines expected behavior. @anthonyettinger I'll tag you in it so you can be informed.

This is merged, so I'll close after demo.

**Comment by chandadharap** [comment]
Closing, as VD comps are integrated into functional code.
