### ISSUE TITLE
app controller: implement new play button icon

### ISSUE THREAD

**Issue by altsang** [strongloop/strong-arc#1197]
As an Arc user I would the app controller icon to be as intuitive as possible based on what it does.

- [ ] implement new icon in #1087 in styleguide
- [ ] retrofit in Arc

**Comment by anthonyettinger** [comment]
@stacy-hunt can you link the SVG icon here?

**Comment by stacy-hunt** [comment]
https://drive.google.com/folderview?id=0B1FTzkB7697GaFl6QnlFUDh3Z2c&usp=sharing
I replaced the old appController SVG assets with the new ones.
Note that this folder also contains SVG assets for the new menu button (replaces the power button)

**Comment by altsang** [comment]
looks sweet, verified on master
