### ISSUE TITLE
Delete Icon: retrofit tables in Composer and Process Manager

### ISSUE THREAD

**Issue by altsang** [strongloop/strong-arc#1198]
As a SL Arc user using the Process Manager, it wasn't intuitive how to delete a row when I was using the GUI for the first time.  I would want a more intuitive UX to know how to delete a row.

- [ ] implement #1107 in styleguide
- [ ] retrofit in process manager and composer

**Comment by anthonyettinger** [comment]
@altsang is this done? Seem to recall having a couple of tickets on this.

**Comment by seanbrookes** [comment]
I think PM view has been updated (the delete icon is darker than before)
but not sure about model properties

On Wed, Jun 24, 2015 at 12:26 PM, Anthony Ettinger <notifications@github.com
> wrote:

> @altsang <https://github.com/altsang> is this done? Seem to recall having
> a couple of tickets on this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/strongloop/strong-arc/issues/1198#issuecomment-114986486>
> .
>



-- 
*StrongLoop <http://strongloop.com/>** makes it easy to **develop APIs
<http://strongloop.com/mobile-application-development/loopback/>** in Node,
plus get DevOps capabilities
<http://strongloop.com/node-js-performance/strongops/> like monitoring,
debugging and clustering**.*

**Comment by altsang** [comment]
model properties is good, verified on master
