### ISSUE TITLE
Watchdog: detect when new profile data is available, and notify the user

### ISSUE THREAD

**Issue by altsang** [strongloop/strong-arc#1203]
As a devops user using Arc or slc to profile an active PID, we would like to set default limits for profiling in either regular or "smart" (watchdog) mode so that we don't exhaust system resources.

please see - https://docs.google.com/a/strongloop.com/document/d/1igoR3uav1xxrhhaoGGumsLnMPKscBzzAzy0KOpBx18o/edit#heading=h.acevxexo7vt7 for proposed first iteration

- [x] on the front end, we should pass a parameter that will limit the profile by cycle counts or by size when sending back to Arc
- [x] on the front end, the `start` command may be issued and the `stop` command may be issued as well, but the server may `stop` because the limit has been exceeded so need a way for the client to be notified - this is a similar use case for how Process Manager receives updates from the server

**Comment by ritch** [comment]
So the conclusion from the offline discussion was essentially:

 - we'll poll from the browser for `Profile` state updates
 - `pm` should keep the `Profile` up to date including `currentlyRunning` and `completed` (or similar)

**Comment by altsang** [comment]
cool - and that there will be multiple smart profiling PIDs at the same time, therefore for each PID that exceeds the cycle count number - we want to collect the profiles as they are ready

**Comment by cgole** [comment]
blocked on https://github.com/strongloop-internal/scrum-loopback/issues/330
