### ISSUE TITLE
Arc: add new component for pop-up dialogue to styleguide

### ISSUE THREAD

**Issue by altsang** [strongloop/strong-arc#1209]
As a SL developer, I need to be able to bring up a more information and options to a user while not leaving the full context of the screen so I would like an component to be able to optionally bring up a set of options on demand.

@stacy-hunt to append specs to be reviewed by team and implemented in styleguide

**Comment by stacy-hunt** [comment]
I think that Joe has already built this and added it to the style guide, hasn't he?

![image](https://cloud.githubusercontent.com/assets/1924932/7624858/19089e5c-f9a4-11e4-8ed3-97aef54a8f48.png)

**Comment by altsang** [comment]
@jtary - this is already added?

**Comment by jtary** [comment]
@altsang yes, it's complete in the branch.

**Comment by altsang** [comment]
fantastic - verified on master, looks great
