### ISSUE TITLE
Add System Notification Message to Styleguide

### ISSUE THREAD

**Issue by stacy-hunt** [strongloop/strong-arc#1210]
Part of the messaging framework, this message is for important system-wide events that require the user to acknowledge they have seen it, but shouldn't stop them from carrying on with their work.

![image](https://cloud.githubusercontent.com/assets/1924932/7624797/1a0fc42a-f9a3-11e4-94d8-1b5cf6a4bb55.png)

Link to Bell.svg in Google Drive: https://drive.google.com/open?id=0B1FTzkB7697GOThtNFZ0VDBpTk0&authuser=0

**Comment by altsang** [comment]
/cc: @chandadharap

assigning to @anthonyettinger per instructions

**Comment by altsang** [comment]
LGTM, @seanbrookes, @jtary - please provide comments ASAP, thx

**Comment by seanbrookes** [comment]
- The dimensions need to be relative, not finite as different screen sizes and resolutions with throw fixed size demensions off.
- should the button reflect primary action (color)?

**Comment by altsang** [comment]
@stacy-hunt pls see above

**Comment by stacy-hunt** [comment]
The software I use to design doesn't have rems as a measurement option. I'm not sure how I could give the values in rems without actually building the component; I can talk to Anthony about how we might do this, but I thought that it would be possible for the developer to do the conversion from pts to rems.

**Comment by seanbrookes** [comment]
- this gets to heart of the paradigm shift we need to make wrt our design approach so we should definitly discuss in our meeting.
- In this particular case the width and spacing dimensions could be shown in ratio to 100% width.
- combined with a working code prototype to demonstrate desired design/behaviour across different resolutions

**Comment by stacy-hunt** [comment]
OK, image has been updated with rem as the units instead of pts

**Comment by altsang** [comment]
@seanbrookes, @jtary, @anthonyettinger - feedback? all good?

**Comment by altsang** [comment]
@seanbrookes, @jtary, @anthonyettinger - feedback? all good?

**Comment by seanbrookes** [comment]
LGTM

**Comment by altsang** [comment]
next step - implementation - putting back into TOB

**Comment by altsang** [comment]
ready for review - nvm

**Comment by altsang** [comment]
reviewed on master, all good :+1:
