### ISSUE TITLE
Add System Defcon Message to Styleguide

### ISSUE THREAD

**Issue by stacy-hunt** [strongloop/strong-arc#1212]
This message appears when there is critical information about the app that requires the user to acknowledge they know about it before proceeding. It is a modal dialog which greys out the background.

![image](https://cloud.githubusercontent.com/assets/1924932/7624873/8c2c6bca-f9a4-11e4-9054-d1a5683f77f4.png)

**Comment by seanbrookes** [comment]
I know I sound like a broken record here but the dimensions should be relative to account for different resolutions and screen sizes

**Comment by seanbrookes** [comment]
Also, can we either define what defcon means or come up with a different way of communicating what context the message applies to?

**Comment by stacy-hunt** [comment]
The description says "This message appears when there is critical information about the app that requires the user to acknowledge they know about it before proceeding." I'm not sure how I can define it any better than that... suggestions?

**Comment by seanbrookes** [comment]
is there a key or legend that defines the different versions of defcon?  i.e how many levels of defcon are there?  what criteria must be met to be a 'defcon' ? etc.

**Comment by stacy-hunt** [comment]
Let's discuss this in the next UX meeting.

**Comment by seanbrookes** [comment]
what does the word 'defcon' even mean?  is it a ux\ui term?

**Comment by stacy-hunt** [comment]
![image](https://cloud.githubusercontent.com/assets/1924932/7421450/94c05e84-efd8-11e4-9612-c7388ed6ee75.png)

**Comment by seanbrookes** [comment]
ok thanks.  It will be important to codify these terms and definitions in the styleguide with these components

**Comment by stacy-hunt** [comment]
Spec updated with relative dimensions

**Comment by altsang** [comment]
@seanbrookes, @jtary, @anthonyettinger - are we good here?  if so  I'll put to TOB to be assigned for implementation

**Comment by chandadharap** [comment]
@altsang Can we close this and I'm sure you have a new story for implementation thats not titled "adding to style guide".

**Comment by altsang** [comment]
implementation in #1252

**Comment by anthonyettinger** [comment]
looks good.
