### ISSUE TITLE
Add Context Notification Message to Styleguide

### ISSUE THREAD

**Issue by stacy-hunt** [strongloop/strong-arc#1214]
This message shows important information about an interactive element whenever it is in focus.

![image](https://cloud.githubusercontent.com/assets/1924932/7411003/04da3722-ef88-11e4-9d5b-1a45415c335b.png)

**Comment by altsang** [comment]
@seanbrookes, @jtary, @anthonyettinger - feedback?

**Comment by jtary** [comment]
Looks good to me

**Comment by altsang** [comment]
putting to TOB for implementation
