### ISSUE TITLE
need to display licensing messages in Metrics module

### ISSUE THREAD

**Issue by altsang** [strongloop/strong-arc#1216]
As a SL developer using the styleguide, I need to have a consistent way of messaging the user at the global level so that I can notify them without raising exceptions, only information.

- [ ] implement notification message to be defined in styleguide in #1210

**Comment by altsang** [comment]
/cc: @chandadharap

assigning to @anthonyettinger per instruction

**Comment by altsang** [comment]
invalid license message for Metrics to be displayed in notification banner:

@anthonyettinger - see below...

"StrongLoop Arc Metrics licensing missing or invalid. Please verify your licenses in the <link Licenses page>  If you have questions about your license or StrongLoop licensing please contact sales@strongloop.com."

**Comment by anthonyettinger** [comment]
ui component is in master now, example in styleguide. passing over to sean to implement license validity check on metrics

**Comment by seanbrookes** [comment]
Metrics implementation is on master now

**Comment by altsang** [comment]
hmmm do you have a test environment?  I tried testing on my own instance, but I can't see the notification message...

**Comment by seanbrookes** [comment]
I was using Anthony's account as he has access to the auth service and can manually disable individual module license references.  
It is difficult to generate a 'bad' license for the metrics module as it auto renews very easily

**Comment by altsang** [comment]
discussed with @seanbrookes for clarification

@chandadharap, @anthonyettinger, @jtary, @cgole, @sumitha, @crandmck 

super important info:
licensing checks that @seanbrookes has implemented are only consistent and reliable for embedded strong-pm, this is because the validation logic is checked against Arc's licenses and we know that the embedded PM is going to automatically inherit the licenses when spun up

@sam-github  - we need a strong-pm to report back whether or agent is licensed and sending back data to be consistent when we swap out the embedded strong-pm with the newest version per the work that @jtary is doing, the consistency is needed for local and remote strong-pms, there's no guarantee that we you are connecting to will have a licensed pushed to it already, so even if you have a license - if you didn't connect your strong-pm to Process Manager and push your licenses from Arc, you're going to still run into issues and a disconnect

@crandmck - for now we should just say that trials for Metrics is enabled for viewing in the embedded strong-pm and you choose `local application` to view them, a trial for remote strong-pm is possible but not supported at this time

**Comment by chandadharap** [comment]
@altsang We cannot document "embedded" strong-pm, the external user has no idea about "embedded strong-pm". We can say Metrics is enabled for viewing in the local application when Arc starts up.. or something appropriate. leaving it to @crandmck 

Also can we please create a separate issue for your ask of @sam-github to implement  license reporting? 

I'd like to keep this issue focused on iimplementing the banner and messaging. It is tied to the Entitlement and Arc release that should go out in a day or two.
- chanda

**Comment by altsang** [comment]
Not suggesting we document embedded strong-pm, I'm clarifying for you guys what is going on.  Documentation we should just say trial works within Arc via app controller

**Comment by chandadharap** [comment]
thanks.

On Sun, May 3, 2015 at 9:51 PM, Al Tsang <notifications@github.com> wrote:

> Not suggesting we document embedded strong-pm, I'm clarifying for you guys
> what is going on. Documentation we should just say trial works within Arc
> via app controller
>
>
>
> > On May 3, 2015, at 9:35 PM, chandadharap <notifications@github.com>
> wrote:
> >
> > @altsang We cannot document "embedded" strong-pm, the external user has
> no idea about "embedded strong-pm". We can say Metrics is enabled for
> viewing in the local application when Arc starts up.. or something
> appropriate. leaving it to @crandmck
> >
> > Also can we please create a separate issue for your ask of @sam-github
> to implement license reporting?
> >
> > I'd like to keep this issue focused on iimplementing the banner and
> messaging. It is tied to the Entitlement and Arc release that should go out
> in a day or two.
> >
> > chanda
>
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/strongloop/strong-arc/issues/1216#issuecomment-98588693>
> .
>



-- 
Chanda Dharap
Director, Engineering
@StrongLoop Inc
(510) 304-3924
chanda@strongloop.com

*StrongLoop <http://strongloop.com/>** makes it easy to **develop APIs
<http://strongloop.com/mobile-application-development/loopback/>** in Node,
plus get DevOps capabilities
<http://strongloop.com/node-js-performance/strongops/> like monitoring,
debugging and clustering**.*

**Comment by altsang** [comment]
@sam-github strongloop-internal/scrum-nodeops#547

**Comment by chandadharap** [comment]
done.
