### ISSUE TITLE
Add Breadcrumbs component to Stylegude

### ISSUE THREAD

**Issue by stacy-hunt** [strongloop/strong-arc#1232]
![image](https://cloud.githubusercontent.com/assets/1924932/7577167/199283c0-f7fa-11e4-8d2f-c40797c3cbb6.png)

Link to SVG for separator: https://drive.google.com/open?id=0B1FTzkB7697Gblp3VXJuNllGdWc&authuser=0

**Comment by altsang** [comment]
@seanbrookes, @jtary, @anthonyettinger - thoughts?  LGTM 
FWIW - I actually like this more because it's lighterweight

**Comment by altsang** [comment]
NVM again - I'll verify on master

**Comment by altsang** [comment]
verified on master, looks good :+1:
