### ISSUE TITLE
power button: has become too overloaded, licenses page needs a new control

### ISSUE THREAD

**Issue by altsang** [strongloop/strong-arc#1234]
As an Arc user I would want a more intuitive icon to go to so that I can find login/logout functions separately from where to find licensing.

- [ ] explore where to put licenses page and other Arc "settings"

**Comment by ijroth** [comment]
+1

**Comment by rmg** [comment]
Could we at least replace the "power button" with something closer to the conventional [menu hamburger](https://www.iconfinder.com/icons/134216/hamburger_lines_menu_icon) so that there's some hint that it is a menu and not an exit/shutdown (not logout) button?

**Comment by altsang** [comment]
@rmg yes that was an option that we were going to bring up if it were to remain on the same menu versus introducing another icon

**Comment by stacy-hunt** [comment]
The power button orginally only had one function, but it seems likely that
there will be other functions we need to add in the future, so I'd be in
favour of moving to a menu rather than cluttering up the UI with more
buttons. It does mean 2 clicks to log out, but lots of apps do that and
people are used to it. I don't really like the hamburger button
aesthetically, but it is well recognised so I don't think it's worth the
effort to reinvent it. I'll draft up a new button and see what you guys
think.

**Comment by altsang** [comment]
sounds good @stacy-hunt , yeah I don't like the hamburger button either, but from what little I can tell - seems to be getting traction for web and not only mobile

**Comment by seanbrookes** [comment]
+1 on the emergent hamburger icon convention

On Wed, May 13, 2015 at 3:00 PM, Al Tsang <notifications@github.com> wrote:

> sounds good @stacy-hunt <https://github.com/stacy-hunt> , yeah I don't
> like the hamburger button either, but from what little I can tell - seems
> to be getting traction for web and not only mobile
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/strongloop/strong-arc/issues/1234#issuecomment-101828785>
> .
>



-- 
*StrongLoop <http://strongloop.com/>** makes it easy to **develop APIs
<http://strongloop.com/mobile-application-development/loopback/>** in Node,
plus get DevOps capabilities
<http://strongloop.com/node-js-performance/strongops/> like monitoring,
debugging and clustering**.*

**Comment by stacy-hunt** [comment]
See what you think of this:

![image](https://cloud.githubusercontent.com/assets/1924932/7622165/b7cf6c8c-f981-11e4-8722-a258c50a6554.png)

**Comment by ijroth** [comment]
I like, FWIW

**Comment by altsang** [comment]
+1, looks good to me, can we have some proposals on guidelines of what would go in the hamburger menu versus being a first class citizen (e.g. app controller - for now, and docs)

**Comment by rmg** [comment]
It doesn't make me think "if I press this to see what it does it will probably kill my app", so :+1: from me

**Comment by altsang** [comment]
@anthonyettinger, @jtary, @seanbrookes - feedback before I created story for implementation?

**Comment by altsang** [comment]
assigning to @anthonyettinger

**Comment by seanbrookes** [comment]
LGTM

On Thu, May 14, 2015 at 3:09 PM, Al Tsang <notifications@github.com> wrote:

> assigning to @anthonyettinger <https://github.com/anthonyettinger>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/strongloop/strong-arc/issues/1234#issuecomment-102183207>
> .
>



-- 
*StrongLoop <http://strongloop.com/>** makes it easy to **develop APIs
<http://strongloop.com/mobile-application-development/loopback/>** in Node,
plus get DevOps capabilities
<http://strongloop.com/node-js-performance/strongops/> like monitoring,
debugging and clustering**.*

**Comment by altsang** [comment]
looks great, verified on master
