### ISSUE TITLE
API Analytics: need a new landing page icon

### ISSUE THREAD

**Issue by altsang** [strongloop/strong-arc#1235]
As an Arc user, I would expect to be able to navigate to viewing API analytics from within the landing page so that I can access it easily

**Comment by stacy-hunt** [comment]
I'm not sure I'm really sold on any of these - but see what you guys think. If there isn't one that really nails it I'll keep trying. 

![image](https://cloud.githubusercontent.com/assets/1924932/7624610/8a130ad2-f9a0-11e4-96f8-ff00a1ddde31.png)

**Comment by altsang** [comment]
#4, and then #1?

**Comment by chandadharap** [comment]
They all look like Cloud deployments. Not sure thats the right icon.

On Wednesday, May 13, 2015, Al Tsang <notifications@github.com> wrote:

> #4 <https://github.com/strongloop/strong-arc/pull/4>, and then #1
> <https://github.com/strongloop/strong-arc/issues/1>?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/strongloop/strong-arc/issues/1235#issuecomment-101881916>
> .
>


-- 
Chanda Dharap
Director, Engineering
@StrongLoop Inc
(510) 304-3924
chanda@strongloop.com

*StrongLoop <http://strongloop.com/>** makes it easy to **develop APIs
<http://strongloop.com/mobile-application-development/loopback/>** in Node,
plus get DevOps capabilities
<http://strongloop.com/node-js-performance/strongops/> like monitoring,
debugging and clustering**.*

**Comment by altsang** [comment]
@stacy-hunt to noodle on this more, for now, @anthonyettinger is going to use one of them as a placeholder

**Comment by stacy-hunt** [comment]
Here's a link to the placeholder svg icon. The 2 files are called "API_analytics_over" and "API_analytics_out":
https://drive.google.com/open?id=0B1FTzkB7697GdTY5Nm1UaHJQZHc&authuser=0

**Comment by stacy-hunt** [comment]
This is the icon we're currently using:
![image](https://cloud.githubusercontent.com/assets/1924932/8314314/975d2ba6-199d-11e5-9726-b00e8f570f44.png)
