### ISSUE TITLE
Add module-level contextual help for API Analytics

### ISSUE THREAD

**Issue by crandmck** [strongloop/strong-arc#1257]
The API Analytics Arc module does not have contextual-help as all the other modules do:
![missing analytics help](https://cloud.githubusercontent.com/assets/2925364/7733133/119b3498-fee2-11e4-9d1d-786368020d8f.png)

I added a placeholder Confluence article: http://docs.strongloop.com/display/SLC/API+Analytics
The ID is 6719905
It just needs to be hooked up the UI.

**Comment by anthonyettinger** [comment]
ok, thanks. Will get to it before next release. @chandadharap

**Comment by altsang** [comment]
verified on master as TBD placeholder
