### ISSUE TITLE
remove browserify `d3` and `jquery` references in tracing packages

### ISSUE THREAD

**Issue by anthonyettinger** [strongloop/strong-arc#1261]
ongoing conversation about this approach is happening in one of the PRs: https://github.com/strongloop/cxviz-eventloop/pull/3

connected to https://github.com/strongloop/strong-arc/pull/1361

**Comment by chandadharap** [comment]
Please comment on why this is pulled into current Sprint? Is this urgent to bring in mid-sprint? Usually please check with me before bringing into Sprint.

**Comment by anthonyettinger** [comment]
this is a fix that needs to happen for this release.

part of the d3 conflict error we were having when we introduced browserify

**Comment by sam-github** [comment]
can you link all the PRs to this issue?

**Comment by rmg** [comment]
An alternative that doesn't require modifying any of those modules: strongloop/strong-arc#1363

**Comment by chandadharap** [comment]
PRs not necessary to be merged anymore.
