### ISSUE TITLE
Unhelpful error message when connecting to PM with no deployed app

### ISSUE THREAD

**Issue by crandmck** [strongloop/strong-arc#1283]
1. Start PM with `slc pm`
1. In Arc, go to "Process Manager". 
1. Enter the PM URL, e.g. `http://localhost:8701`. **App Status** shows "Problem" in red.
1. Click on the red question mark.

![](http://content.screencast.com/users/RandMck/folders/Jing/media/9761af39-3734-45b6-a367-dfd64cfad429/00000266.png)

The error message is not helpful.

Suggestion: "No application found.  You must deploy an application to this PM before you can connect to it."

**Comment by seanbrookes** [comment]
yeah this is new - my guess is it is a result of  multi-app pm.
we already have a message for 'no app found' will take a look to make sure it is the same use case
