### ISSUE TITLE
SL Gateway: need to break out strong-gateway-demo into tutorial

### ISSUE THREAD

**Issue by altsang** [strongloop/strong-arc#1300]
As a SL LB user, I want to be able to download the new SL Gateway and use it with my LB backend.

strong-gateway-demo needs to be broken up into its parts

@superkhau - please append outline of tutorial

**Comment by superkhau** [comment]
1. create api server (notes)
2. spin up the client app and show it using the api server
3. introduce gateway, hook up client app with gateway reverse proxy to api server
  - proxy without protection
  - enforce protection
    - register client and users
      - describe sample-data.json as a precanned for our demo purpose only
    - tweak client to exercise oauth 2 flow
      - fetch access token
      - use token to access api (through gateway)
4. talk about QOS/policies
  - rate limiting
  - metrics
    - run gateway with strong-pm (local or remote)
    - use arc to show metrics
  - point to docs for other policies
5. choose your datasource for your oauth2 metadata/data
  - datasources.json
  - run setupdb.js to create tables for relational db
  - point to docs for other types of datasources
