### ISSUE TITLE
Licensing: next iteration of licensing page with renewal buttons

### ISSUE THREAD

**Issue by altsang** [strongloop/strong-arc#1304]
As a SL arc user, I will initially receive a 30 day license and then the feature will expire, I would like a renew button at the feature level only that I can request a renewal of the license.

- [ ] remove product level checkboxes
- [ ] renewal button
- [ ] remove auto renew logic

Updated visual design:

![image](https://cloud.githubusercontent.com/assets/1924932/8012296/2d218efc-0b75-11e5-979e-1756be38fd0e.png)

**Comment by anthonyettinger** [comment]
@stacy-hunt need design mock

**Comment by stacy-hunt** [comment]
Done

**Comment by chandadharap** [comment]
This is on a feature branch and needs to merge to master.

**Comment by jtary** [comment]
@chandadharap Not super up to date with the most recent stuff, but can dig in to it if need be.

**Comment by chandadharap** [comment]
merged. will move to done. Verification is a separate story next Sprint.
