### ISSUE TITLE
Standalone example app for Smart Profiling

### ISSUE THREAD

**Issue by chandadharap** [strongloop/strong-arc#1306]
Please create an example app, something small to demonstrate the Watchdog use case.

The app should be "smartprofiling-example-app", Artistic/SL license. and publicly available on github. (This is not intended to be a continuously running app on demo.)

@sam-github for FYI.

**Comment by chandadharap** [comment]
Sam's input: Capture difference between Smart profiling versus Full profiling with example. Small refactor.

**Comment by crandmck** [comment]
Joe created https://github.com/strongloop/smartprofiling-demo.  I'll work on README when he's done on his end.

**Comment by cgole** [comment]
verified the app works.

**Comment by chandadharap** [comment]
@jtary Sorry I didn't spot this earlier, thought I had mentioned, we have a naming convention. Please rename app to smartprofiling-example-app
