### ISSUE TITLE
Add contextual help to Smart Profiling

### ISSUE THREAD

**Issue by chandadharap** [strongloop/strong-arc#1309]
- [x] Identify areas where help is needed (@crandmck)
- [x] Create these on UX (@jtary)
- [x] Create the help text (@crandmck)

**Comment by chandadharap** [comment]
Rand created a placeholder article: http://docs.strongloop.com/display/SLC/Smart+profiling.  The ID is 6720103.

**Comment by crandmck** [comment]
My part is done.

**Comment by chandadharap** [comment]
@jtary Is it done on the UI, if so, go ahead and close it.

**Comment by jtary** [comment]
@chandadharap it's already in the UI. Closing out.
