### ISSUE TITLE
PID selector - [Object : object] in drop down selector

### ISSUE THREAD

**Issue by altsang** [strongloop/strong-arc#1311]
Go to the PID selector in API Analytics or other Arc module.

to reproduce:

1. override local application with a another host - "localhost" , port : 8701
2. now type to try to get back to "local application"
3. upon complete - [object Object] : ----

![image](https://cloud.githubusercontent.com/assets/2261105/7948264/86e2405c-0937-11e5-8bc2-8cc47e2e8454.png)

**Comment by chandadharap** [comment]
need not be in TBR if its verified. Its assumed for this case.
