### ISSUE TITLE
Tracing Demo: need public facing demo to show CPU and Memory leak

### ISSUE THREAD

**Issue by altsang** [strongloop/strong-arc#1344]
As a Arc user newly introduced to Tracing, I want to understand the new module and an example app showing me what it's capabilities are will help me get started.

- [x] `tracing-example-app` - new repo 
- [x] intended to be `slc start` within SL PM
- [x] on a set interval - i.e. 30 seconds, a CPU spike occurs
- [x] on an set interval _not_ coinciding with the CPU spike, a memory leak happens - very large allocation, and then deallocation

the user should be able to _easily_ identify the two events within the tracing time chart and drill down one top line function with nested functions that show the drill down capabilities within Tracing and the flamegraph

**Comment by superkhau** [comment]
- [ ] Aim for 30 second interval
- [ ] Extended peaks and troughs
- [ ] Raw node (no Express/LoopBack)
- [ ] Make the functions easy to recognize (explainable)
- [ ]  Has to be run in PM

---

# Instructions to get tracing up an running in Arc

1. git clone this - https://github.com/strongloop/tracing-example-app/tree/mem_leak
2. npm install; slc start (auto runs "main" in package.json"
3. run `slc arc --feature tracing`
4. go to your Process Manager in Arc and add `localhost 8701`
5. push license option
6. then go to Tracing module - turn it on and leave it on for a while to collect data points

**Comment by superkhau** [comment]
Connects https://github.com/strongloop/tracing-example-app/pull/1

**Comment by altsang** [comment]
this is good, reviewed with @superkhau
