### ISSUE TITLE
Arc: need new icon for Arc

### ISSUE THREAD

**Issue by altsang** [strongloop/strong-arc#1358]
The current icon for Arc was done as a bit of a scramble, as a SL Arc user, I would want an icon that is more bold and iconic of SL's flagship product.

- [ ] SL marketing site icon
- [ ] mini-version for favicon

**Comment by stacy-hunt** [comment]
This doesn't require feedback as I know they're not what we need - just posting so you know I'm working on it:

![image](https://cloud.githubusercontent.com/assets/1924932/8314426/4f459da2-199e-11e5-9ab7-0839276fbfee.png)

**Comment by stacy-hunt** [comment]
Here's a version that I think has merit. Thoughts?

![image](https://cloud.githubusercontent.com/assets/1924932/9369799/709fc89c-4680-11e5-8f81-50ac4b8dc1cd.png)

**Comment by stacy-hunt** [comment]
Al like 2 and 5

**Comment by altsang** [comment]
I ran this by JCS, unfortunately none of them really stood out.  The last one possibly but the Arc looked more like a semi-circle curve

the issue with the electrodes is that there isn't an immediate association of what they are without help from the photo we used on the website.  At first I thought they were actually insect antennas

maybe we can take #5 and evolve it?

**Comment by seanbrookes** [comment]
Why not point the electrodes inwards to help form an 'A' shape.  I proposed something earlier as a rough sketch:
![proposed-logo](https://cloud.githubusercontent.com/assets/1751524/9446774/41ff7304-4a48-11e5-8b90-171476cfe631.png)

**Comment by altsang** [comment]
electrodes and an electrical arc just aren't common every day things software devs discuss, if we were EEs than might be a different story, I think we should just drop trying to get the electrodes and get something that looks like an arc (as in the shape)

**Comment by stacy-hunt** [comment]
Try this one out:

![image](https://cloud.githubusercontent.com/assets/1924932/9644626/0ba9947a-517c-11e5-9555-a2107baa8cc6.png)

**Comment by stacy-hunt** [comment]
How about these?
![image](https://cloud.githubusercontent.com/assets/1924932/9747894/286ee0f0-562d-11e5-9083-75a4cad7a375.png)

**Comment by altsang** [comment]
going to bench this for now
