### ISSUE TITLE
Host and App Selector: overhaul PID selector to use Process Manager as single source of truth

### ISSUE THREAD

**Issue by altsang** [strongloop/strong-arc#1360]
As a SL Arc user, I would want a consistent experience when in an Arc module to switch my context.

All SL PMs are to be entered into Process Manager, the PID selector will have a dropdown that references what is in the Process Manager and a add new link for convenience to take you there.

 [visual comps](https://drive.google.com/open?id=0B1FTzkB7697GZ015b0daSklrU0U&authuser=0)

@stacy-hunt: comps need to be updated to show `+` button that will let you add an a new host, which will hot link you to Process Manager add by strong-pm host the text should read `+ Add PMHost` (consistent with Process Manager)

areas affected:
- [x] profiler
- [x] metrics
- [x] api analytics
- [x] tracing
- [x] build and deploy

connected to strongloop/strong-arc#1388
connected to #1430 
connected to #1459

**Comment by seanbrookes** [comment]
port existing components (profiler/build-deploy/metrics) to Mesh host source of truth (PM View)
- add support for modal 'add new' form

**Comment by seanbrookes** [comment]
duplicate / overlap with https://github.com/strongloop-internal/scrum-nodeops/issues/737

**Comment by seanbrookes** [comment]
copied info over to other story and closing

**Comment by chandadharap** [comment]
Reopening because this is the story Im tracking in Rally. Please don't create duplicates and then close originals, it messes up Sprint tracking.

**Comment by seanbrookes** [comment]
A couple of notes on this story so we're clear on what has been done and what is still to do:
Done:
- update the deploy form to use the same source of truth as the pm view so the user can select from a list of possible pm's
- update PM view to add 'Service' column to display the app name running on a particular host
- update the 'action'm menu ont he PM View to improve the UX

What has not been done:
- Metrics, Profiler, and API analyitics were not updated.  Two main reasons: the internal pm instance complicates things and Jtary has made some changes to the PM host form for smart profiling that I didn't want to mess with.
- there is another set of stories for replacing the internal pm so the components above should be updated as part of that story.
- an 'add new host' link has not yet been added to the tracing and deployment views - still needs to be done

**Comment by seanbrookes** [comment]
Another note regarding the description of this issue.  I don't think we are looking for 'app selection' at the host level at this point.  I think that is hold over from the target UX for multi-app support.  Currently Arc is only supporting single app per pm host so the need to pivot on app is not needed.

**Comment by chandadharap** [comment]
@altsang @seanbrookes Can we close this? and split off the internal-pm work in another story? i;d liketo close work, rather than ongoing long stories.

**Comment by altsang** [comment]
I don't know if this work is captured elsewhere, if not, we can't close until the work is complete.  It's not an on-going long story

@seanbrookes 
yes we don't need to make this app-centric anymore with putting multi-app process manager on the backburner - I'm just interested in making the "PID selector" consistent:
- you go to Process Manager to add to the list
- you'll have a drop down to show what host (and app if running?)
- you'll have a `+Add new host` link that'll take you to Process Manager in the PID selector component

if the above is correct then this story still needs to be complete in all the other Arc modules, I'll update the story description and comments above to Stacy

**Comment by seanbrookes** [comment]
this was more work than thought given the comlications of the existing ui logic around the old internal pm plus the rework Joe did for the smart profiler implementation.

I would estimate the amount of work remaining is around 3 points

**Comment by cgole** [comment]
verified this for arc deploy.  From the UI side, this seems to work for metrics as well. Metrics has a dropdown for host/port and I thought, it gets this from Arc PM.  Not sure how the backend is implemented. 
Is there another story for profiler and API analytics?

**Comment by cgole** [comment]
verified

**Comment by seanbrookes** [comment]
not sure what the expectation is here going forward.

The latest on this is that the PM Host selectetor has been replaced across the app to a dropdown select list with an 'add PM Host' link in the list.  Clicking that will take the user to the PM View.

Anthony is looking into the API Analytics view as there may be a wrinkle there.

One other gotcha I just thought of is that the 'internal' pm will not be accessible from metrics and profiler now.  We will need to consider how we want to handle that going forward

**Comment by chandadharap** [comment]
That is vali @seanbrookes . Also now since you HAVE to add the pm via Process Manager page, that should probably be the first thing you do before even getting to Metrics, profiling, Tracing etc

Maybe you can discuss in the UX meetings.

**Comment by chandadharap** [comment]
release with Smart Profiling.
