### ISSUE TITLE
API Analytics: units of measure are missing from all charts

### ISSUE THREAD

**Issue by altsang** [strongloop/strong-arc#1381]
As a SL Arc user, we need units of measure for all charts so that I can interpret the data on each of the levels

**Comment by anthonyettinger** [comment]
@altsang -- i added axis labels. but i don't have good data set to test with. can you let me know if there are any issues (ie: text overlapping)?

branch is https://github.com/strongloop/strong-arc/tree/feature/api-analytics-units

**Comment by altsang** [comment]
verified on master and staging
