### ISSUE TITLE
Entitlement Phase 2: initial license not pulled down

### ISSUE THREAD

**Issue by altsang** [strongloop/strong-arc#1382]
As an SL user using Arc for the new licensing page, the initial license is not being pulled down because the auto renew logic has been removed, I would want...

- [x] initial 30 day trial period automatically pulled down for all existing AND new products AND features
- [ ] manual renewal of features for features marked renewable

/cc: @raymondfeng,needs to be worked out between you and @anthonyettinger

**Comment by raymondfeng** [comment]
See https://github.com/strongloop/strong-arc/commit/1ac96ce3ecdd93a5abeea38c153023f8cda24a0e

**Comment by chandadharap** [comment]
Add to Chandrika's test cases (Chanda)

**Comment by chandadharap** [comment]
Added test case, moving to done. Verificiation is off of test case,
