### ISSUE TITLE
Epic: back end APIs for gateway mapping and policy config

### ISSUE THREAD

**Issue by altsang** [strongloop/strong-arc#1383]
As an Arc user utilizing the "Gateway Manager" (TBD), I have three views: 1. mapping view, 2. policy config view, 3. policy builder view
I need back end APIs to support  #1 and #2 for MVP

work to be broken down and divided between Ritchie and Raymond

**Comment by chandadharap** [comment]
I don't see any break down under this Epic. @raymondfeng @ritch

**Comment by altsang** [comment]
this work eventually was assigned to Raymond and we created LB models for each of the entities listed above, I have no idea which stories ended up being mapped to this epic
