### ISSUE TITLE
Gateway policy config implementation

### ISSUE THREAD

**Issue by altsang** [strongloop/strong-arc#1385]
As a SL Arc user, we want a GW module with the second view to handle the GW policy config use case, so that I have a dedicated view to see all policies and configure them in detail.

UX specs folder: https://drive.google.com/drive/folders/0B1FTzkB7697GQWlPTDhfSFkyMnM

/cc: @stacy-hunt to update with the final UX export

**Comment by chandadharap** [comment]
@altsang Is this ready to start implementation for Sprint 74?

**Comment by seanbrookes** [comment]
to my knowledge none of the ui work for gateway has started yet

**Comment by chandadharap** [comment]
redundant. closing.
