### ISSUE TITLE
Licensing: better messaging needed if you are denied a renewal license

### ISSUE THREAD

**Issue by altsang** [strongloop/strong-arc#1393]
As a SL Arc user, there should be two different message displayed to the user so that they know the different licensing issues that may encounter.

1. if you navigate to a module that requires a license and you are missing that license the below message is fine...
![image](https://cloud.githubusercontent.com/assets/2261105/8421430/621d519c-1e83-11e5-95a5-14236e0418c8.png)

2. if you click "Renew" the same message isn't acceptable. It should read...

`<product> <feature> licensing cannot be renewed.  If you have questions about your licenses or licensing please contact sales.`

**Comment by chandadharap** [comment]
minor nit: removing bug label. This is a feature spec.

**Comment by cgole** [comment]
verified
