### ISSUE TITLE
Extend API Composer with visual composition capabilities (or Add module for API composer)

### ISSUE THREAD

**Issue by jtary** [strongloop/strong-arc#1395]
Create a new module for the visual composer, with layout spaces for the side panels and workspace area. Module should check for appropriate license, and display correct warning if the user does not have a license for visual-comp.

**Comment by altsang** [comment]
@jtary - please check with @sean this isn't suppose to be a brand new module, there are a set of slider panels that we've built into Composer, we can discuss in UX meeting

**Comment by jtary** [comment]
@altsang: There is already a lot of interface for the API composer. From a navigation point of view, we can make it look like part of the composer module. But from an implementation point of view, it would be a complete mess to try and shoe-horn that much new code into the existing composer code base.

**Comment by altsang** [comment]
the issue is that the canvas view and properties editor work in tandem - we heard this when we did our user focus studies before building Arc (Studio back then), they're like two sides of the coin, from a code perspective - may we can separate out as a separate module but having the interface unified in its view

**Comment by jtary** [comment]
@altsang if we keep a unified data layer, we can switch between the two modules seamlessly. And if we keep some components (like the properties editor) consistent between the two views, that should help anchor the user so they don't feel like they are being bounced between unrelated interfaces. This will also make it much easier to put a license-wall around the visual composition.

**Comment by altsang** [comment]
let's discuss in the UX meeting when we get there, I strongly prefer to have to build toward what we spent weeks and months on already worked out, but never completed in implementation, not only was it received well by our focus groups but it's also the interaction model by which we built Composer in the first place with the assumptions baked into the design

I'm not sure how switching between the modules can be completely seamless unless you're invoking one in the slider panel of the other, but I'm open to revisiting.

re: licensing - the same idea can be put on the slider panel to enable or disable it
