### ISSUE TITLE
Gateway View: Mapping List

### ISSUE THREAD

**Issue by seanbrookes** [strongloop/strong-arc#1396]
table cols:
name (editabled inline)
verb (select)
endpoint pattern (text)
scopes (if pipeline has auth policy with scopes)
pipeline (context modal)
endpoint ( if pipeling has proxy policy

Notes:
- scopes and endpoint values are only shown if and auth policy(with scopes) and a proxy policy are found respectively in the chosen pipeline

- [x] functionality (components / api )
- [x]  visual treatment / layout

**Comment by seanbrookes** [comment]
visual treatment still needed

**Comment by chandadharap** [comment]
I'm moving this back into InProgress. Its not a review is it?

**Comment by chandadharap** [comment]
Create a visual polish story and we can close this.
