### ISSUE TITLE
Gateway View: Mapping Form

### ISSUE THREAD

**Issue by seanbrookes** [strongloop/strong-arc#1397]
- Add New
- modal

name - input
verb - select dropdown (single)
endpoint - input single value (could use some context help)
pipeline -- select from list -- link to add new (clone options)

- [x] functionality (components / api)
- [ ] visual treatement/polish

**Comment by seanbrookes** [comment]
visual treatment still needed: https://github.com/strongloop-internal/scrum-loopback/issues/398

**Comment by chandadharap** [comment]
@seanbrookes Its not clear to me that visual treatment was "missing" in Stacy's spec or that it just didn't get done in this story? Please clarify. I'd have expected visual treatment to be nominal and based on Style Guideline and not custom visual?

**Comment by seanbrookes** [comment]
I mean apply visual treatment / layout as per spec.  Stacy just published the latest (last) visual spec yesterday.  The UI is functionally complete.

**Comment by chandadharap** [comment]
This comment was at start of Sprint, when the spec was available. This has suddenly landed on Anthony's plate?

**Comment by chandadharap** [comment]
e2e test and functioanlity complete. separate story for final visual treatment.
