### ISSUE TITLE
Gateway View: New Pipeline Modal Form

### ISSUE THREAD

**Issue by seanbrookes** [strongloop/strong-arc#1405]
name
policy editor

**Comment by chandadharap** [comment]
Needs Comp from Stacy

**Comment by stacy-hunt** [comment]
I'll anticipate a description of what the comp needs to illustrate in the UX meeting.

**Comment by stacy-hunt** [comment]
![image](https://cloud.githubusercontent.com/assets/1924932/9643915/5093f812-5179-11e5-8838-d3e56d16d320.png)

**Comment by seanbrookes** [comment]
Pipelines don't have a type field

**Comment by stacy-hunt** [comment]
D'oh! Thanks for the catch Sean. Corrected.

**Comment by chandadharap** [comment]
ping? is this verified?

**Comment by stacy-hunt** [comment]
Yep, the image has been updated. There's no type field in it any more.
