### ISSUE TITLE
Gateway View: Pipeline Detail View

### ISSUE THREAD

**Issue by seanbrookes** [strongloop/strong-arc#1407]
- [x] create new
- [x] edit (except renaming)
- [x] clone

e2e tests

- [x] create new
- [ ] edit (except renaming)
- [x] clone

**Comment by chandadharap** [comment]
needs functionality and e2e tests.

**Comment by chandadharap** [comment]
Please add detail to the description. @anthony

**Comment by anthonyettinger** [comment]
test is in place, but there is an issue with running multiple tests.
added 2 points to account for e2e testing.

**Comment by anthonyettinger** [comment]
blockers have all been resolved on writing e2e tests. I created a new ticket for the `edit` e2e test.
