### ISSUE TITLE
finalize UX for Gateway Manager

### ISSUE THREAD

**Issue by altsang** [strongloop/strong-arc#1413]
As a SL product manager, we've explored the different models for UX around the Gateway MVP and would like to finalize the UX for the first iteration so we can build V1.

**Comment by altsang** [comment]
UX design:
https://drive.google.com/drive/folders/0B1FTzkB7697GQWlPTDhfSFkyMnM

**Comment by altsang** [comment]
@seanbrookes and @stacy-hunt

I'll be away for this coming Monday review, please update this issue with the final export and move to done.  @stacy-hunt please check with @sean on which cards he's created for VD comps, he's broken out the GW Manager epic into a bunch of stories, thx

/cc: @chandadharap

**Comment by chandadharap** [comment]
Whats the status on this? Do we have a finalized version?

**Comment by stacy-hunt** [comment]
We do: the final wireframe is at:

 https://drive.google.com/open?id=0B1FTzkB7697GbnhvLTFOSTVtcXM

The visual comp is at:

 https://drive.google.com/open?id=0B1FTzkB7697GWXliZkFNaVlobVU

**Comment by altsang** [comment]
LGTM - done
