### ISSUE TITLE
Logout fails the api call as it doesn't pass in access_token

### ISSUE THREAD

**Issue by raymondfeng** [strongloop/strong-arc#1414]
Here is the error response from the api call:
```json
{"error":{"name":"Error","status":500,"message":"could not find accessToken","stack":"Error: could not find accessToken\n    at /home/raymond/strong-subscription-admin/node_modules/loopback/common/models/user.js:278:12\n    at /home/raymond/strong-subscription-admin/node_modules/loopback-datasource-juggler/lib/dao.js:1407:62\n    at allCb (/home/raymond/strong-subscription-admin/node_modules/loopback-datasource-juggler/lib/dao.js:1339:7)\n    at /home/raymond/strong-subscription-admin/node_modules/loopback-connector-mongodb/lib/mongodb.js:713:9\n    at handleCallback (/home/raymond/strong-subscription-admin/node_modules/loopback-connector-mongodb/node_modules/mongodb/lib/utils.js:95:12)\n    at /home/raymond/strong-subscription-admin/node_modules/loopback-connector-mongodb/node_modules/mongodb/lib/cursor.js:590:16\n    at handleCallback (/home/raymond/strong-subscription-admin/node_modules/loopback-connector-mongodb/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:234:5)\n    at setCursorNotified (/home/raymond/strong-subscription-admin/node_modules/loopback-connector-mongodb/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:434:3)\n    at /home/raymond/strong-subscription-admin/node_modules/loopback-connector-mongodb/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:535:16\n    at queryCallback (/home/raymond/strong-subscription-admin/node_modules/loopback-connector-mongodb/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:215:5)"}}
```

**Comment by ritch** [comment]
I've added a better error message to loopback. We still need to fix the case where it is not passed in from the original call though (in the browser).

**Comment by cgole** [comment]
verified

**Comment by benawarez** [comment]
when I call logout, I get the following: 

{"error":{"name":"Error","status":500,"message":"could not find accessToken","stack":"Error: could not find accessToken\n    at E:\\Dev\\ScreenPosts\\node_modules\\loopback\\common\\models\\user.js:289:12\n    at E:\\Dev\\ScreenPosts\\node_modules\\loopback-datasource-juggler\\lib\\dao.js:1554:62\n    at E:\\Dev\\ScreenPosts\\node_modules\\loopback-datasource-juggler\\lib\\dao.js:1486:9\n    at Object.async.each (E:\\Dev\\ScreenPosts\\node_modules\\loopback-datasource-juggler\\node_modules\\async\\lib\\async.js:153:20)\n    at allCb (E:\\Dev\\ScreenPosts\\node_modules\\loopback-datasource-juggler\\lib\\dao.js:1422:13)\n    at E:\\Dev\\ScreenPosts\\node_modules\\loopback-datasource-juggler\\lib\\connectors\\memory.js:372:7\n    at E:\\Dev\\ScreenPosts\\node_modules\\loopback\\node_modules\\continuation-local-storage\\node_modules\\async-listener\\glue.js:188:31\n    at process._tickDomainCallback (node.js:381:11)\n    at process.<anonymous> (E:\\Dev\\ScreenPosts\\node_modules\\loopback\\node_modules\\continuation-local-storage\\node_modules\\async-listener\\index.js:19:15)"}}

I'm using the same code as the loopback-getting-started-intermediate... it apparently works on the demo but not on mine.  When I debug, I can see that my local storage clears the tokens but the above error is produced once the api call is made.  please advise. thanks.

**Comment by cyberbobjr** [comment]
Same error here, thanks for your help.

**Comment by janpansa** [comment]
I am also having this issue. I log in using the api and the api returns an access token, userid and ttl. I then use that access token as a parameter to logout.

Even with the access_token that I pass through in the URL, it still gives a status 500 message.

> {"error":{"name":"Error","status":500,"message":"could not find accessToken","stack":"Error: could not find accessToken\n    at /usr/src/app/node_modules/loopback/common/models/user.js:302:12\n    at /usr/src/app/node_modules/loopback-datasource-juggler/lib/dao.js:2003:62\n    at /usr/src/app/node_modules/loopback-datasource-juggler/lib/dao.js:1932:9\n    at /usr/src/app/node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:396:17\n    at async.each (/usr/src/app/node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:153:20)\n    at _asyncMap (/usr/src/app/node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:390:13)\n    at Object.map (/usr/src/app/node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:361:23)\n    at allCb (/usr/src/app/node_modules/loopback-datasource-juggler/lib/dao.js:1860:13)\n    at /usr/src/app/node_modules/loopback-connector-mongodb/lib/mongodb.js:870:9\n    at handleCallback (/usr/src/app/node_modules/loopback-connector-mongodb/node_modules/mongodb/lib/utils.js:96:12)"}}
