### ISSUE TITLE
Xamarin SDK: TodoApp readme.md needs more explicit instructions

### ISSUE THREAD

**Issue by altsang** [strongloop/strong-arc#1420]
As a SL developer that is new to Node and mobile development using Xamarin, we need more explicit instructions on how to get the TodoApp (to be renamed to `loopback-example-xamarin`) up and running.

user has a choice to build and run item on Mac  OS X and see iOS app against our pre-canned backend - (xamarindemo.strongloop.com)  note - they do NOT need to know this LB backend

OR

user can run the LB backend themselves and change the BASE_URL path found in the LBXamarinSDK.cs in the Gateway class at the top of file

we should include prerequisites like getting Xamarin Studio and something beyond the starter license to compile and run this app

**Comment by crandmck** [comment]
@altsang I don't have commit access to that repo yet.  I know they are going to move the repo into our org, so maybe I should just wait for that.  In the meantime, I could open a PR, but of course it would be easier just to edit the README.md.

**Comment by altsang** [comment]
ahh yes that makes sense, probably would be good if you just get an idea of what edits you want to make so that when the repo is transferred you can just implement the changes

**Comment by crandmck** [comment]
OK now we have https://github.com/strongloop/loopback-example-xamarin.  I'll work there.

**Comment by crandmck** [comment]
The [README](https://github.com/strongloop/loopback-example-xamarin/blob/master/README.md) is done, except:
- Need to make repo public for images to show up properly.
- Would like to add a section demonstrating how when you use the app in the iOS simulator, data is persisted to LoopBack backend (either locally at http://localhost:3000/explorer/ or at http://xamarindemo.strongloop.com/explorer/).  However, I have not been able to perform any authenticated actions following the standard procedure in http://docs.strongloop.com/display/LB/Introduction+to+User+model+authentication.

**Comment by crandmck** [comment]
The repo is now public.    Still sorting out the ACLs.

**Comment by chandadharap** [comment]
okay, illlclose.
