### ISSUE TITLE
Xamarin SDK: need review of Announcement Blog for Xamarin

### ISSUE THREAD

**Issue by altsang** [strongloop/strong-arc#1421]
As a SL developer, I would want to be aware of the new Xamarin SDK with the proper announcment information including where to find the SDK, and example app, perfectedTech intro etc.

copy - https://docs.google.com/document/d/19nPl1IPYShKz1Cg7Iimvw0KMGd-qXqUJ3xn_dSGCBh4/edit#

Shubhra to post to WP when ready

**Comment by crandmck** [comment]
I edited it, and had one question/comment in the Gdoc.

**Comment by altsang** [comment]
looks good, thx @crandmck
