### ISSUE TITLE
Arc build creates tar inside app directory 

### ISSUE THREAD

**Issue by cgole** [strongloop/strong-arc#1435]
build tar using Arc build. tar got created inside app directory and not one level outside ie ../

**Comment by sam-github** [comment]
I cannot reproduce. I suspect that you didn't reinstall arc. Using npm ls, verify that the strong-build version that arc depends on is 2.0.3

**Comment by cgole** [comment]
cannot repro

**Comment by cgole** [comment]
cannot repro
