### ISSUE TITLE
Tracing page doesnt load pids

### ISSUE THREAD

**Issue by cgole** [strongloop/strong-arc#1460]
connected to #1459
I have an app running with a valid tracing license, but pids dont load - http://www.screencast.com/t/EefAd6QDwIO (1KB)

**Comment by seanbrookes** [comment]
I think this is the wrong screencast - do you have a different one?

**Comment by seanbrookes** [comment]
or just outline the steps to reproduce

**Comment by cgole** [comment]
verified
