### ISSUE TITLE
remove zeroclipboard to minimize security risk

### ISSUE THREAD

**Issue by altsang** [strongloop/strong-arc#1468]
As a outside vendor doing security scan, I've encountered Flash components as a possible vector for infiltration, for now to minimize exposure would like to remove zeroclipboard library from the license manager license key pop up page.

- [ ] remove library
- [ ] hide copy button

**Comment by chandadharap** [comment]
Removing bug tag. @anthony please add an estimate so I can throw something out of current Sprint if needed. This one is clearly priority.

**Comment by altsang** [comment]
verified on master
