### ISSUE TITLE
Windows - host:port entry disappears from PM, on clicking activate button

### ISSUE THREAD

**Issue by cgole** [strongloop/strong-arc#1470]
Steps 
Add host-port to PM in Arc.
Click activate.
The entry disappears

**Comment by cgole** [comment]
dup of #1470

**Comment by seanbrookes** [comment]
I'm having trouble reproducing this problem.  the PM activate seems to be working ok on the windows VM I tested it on.
I did see the setStatus error when starting the app from App Controller but that is a known, unrelated issue.

**Comment by cgole** [comment]
cannot repro
