### ISSUE TITLE
Arc returns blank page

### ISSUE THREAD

**Issue by cgole** [strongloop/strong-arc#1471]
latest from staging -

![screen shot 2015-07-30 at 11 12 00 am](https://cloud.githubusercontent.com/assets/991632/8991192/e30c6fc8-36ab-11e5-9e50-b2cf1b6c2957.png)

**Comment by rmg** [comment]
What version of loopback-workspace was installed? If it is higher than 3.15.1 then a cached copy of a bad version was installed.

**Comment by shaununderwood** [comment]
I've the exact same issue and can't move any further cos of it.
after executing npm install -g strongloop the above writer's scenario occurs. 

➜  ~  slc version
strongloop v4.1.1 (node v2.2.1)
├── strong-arc@1.7.1 (9bb91bb)
├── strong-build@2.0.3 (b66d030)
├── strong-deploy@3.0.0 (bee617c)
├── strong-pm@5.0.0 (dbaa1a5)
├── strong-registry@1.1.5 (f46e58f)
├── strong-start@1.3.0 (3862a1f)
├─┬ strong-supervisor@3.0.2 (539c0ce)
│ └── strong-agent@1.6.4
├── generator-loopback@1.10.2 (167461e)
├── node-inspector@0.7.4
└── nodefly-register@0.3.3

**Comment by shaununderwood** [comment]
okay, i've resolved this. Chrome has AdBlock recently installed, deactivating AdBlock extension allows the Metrics files to be loaded.
