### ISSUE TITLE
Smart profiling on mac returns empty profiles

### ISSUE THREAD

**Issue by cgole** [strongloop/strong-arc#1475]

**Comment by cgole** [comment]
![screen shot 2015-08-03 at 12 02 41 pm](https://cloud.githubusercontent.com/assets/991632/9045402/c164fbb8-39d7-11e5-8e02-29a73f4ac6cc.png)

**Comment by cgole** [comment]
I can see data when I run this through command line

**Comment by cgole** [comment]
sample profiles that I got from the command line - https://gist.github.com/cgole/4793a5833e66bc83908d

**Comment by bnoordhuis** [comment]
I'll take a look tomorrow, maybe the issue is with the agent.  Self-assigning.

**Comment by cgole** [comment]
@bnoordhuis I assumed this is an issue with Arc, since I do get data when I run it through cli?

**Comment by bnoordhuis** [comment]
It's possible the new CPU profiler doesn't send all the necessary fields, I'll check that.

**Comment by sam-github** [comment]
@bnoordhuis strong-agent master is unreleasable until this bug is fixed. If you can fix it in the next week or so, we can block any agent releases and wait for cpu profiling to work again.

If its going to take a while, can you back out the the older version that worked on Linux? Or perhaps both can co-exist, and be switchable at runtime?

**Comment by sam-github** [comment]
@bnoordhuis, will you be able to fix this?

**Comment by bnoordhuis** [comment]
I reverted the new CPU profiler and we won't be releasing that anytime soon anyway so I think this can be closed.

**Comment by chandadharap** [comment]
@cgoe can we review  the revert before closing?

**Comment by chandadharap** [comment]
@cgole I had tagged incorrectly. Can we review then close?

**Comment by cgole** [comment]
verified

**Comment by cgole** [comment]
![screen shot 2015-12-07 at 3 04 32 pm](https://cloud.githubusercontent.com/assets/991632/11642633/e4911bba-9cf3-11e5-9824-c86bf8f45899.png)
