### ISSUE TITLE
UX: need to flesh out cardinality UX

### ISSUE THREAD

**Issue by altsang** [strongloop/strong-arc#1477]
As a SL developer using the canvas within the Composer, I would need to be able to specify all of the supported relationships between models - http://docs.strongloop.com/display/public/LB/Creating+model+relations, in order to do so we need UX details on how they are specified especially the `hasManyThrough`.

**Comment by stacy-hunt** [comment]
Basic Cardinality:

https://drive.google.com/open?id=0B1FTzkB7697GVGRFYmFsMllXQ0U
