### ISSUE TITLE
Arc: remove internal pm - we have process manager now

### ISSUE THREAD

**Issue by altsang** [strongloop/strong-arc#1484]
As an Arc developer I would like to be able to run my app to preview it, run API explorer and other runtime information without having to worry about strong-pm.

- confusing to have an app controller and process manager trying to interact with strong-pm (internally vs. externally)

/cc: @jtary

connected to: #1539 
connected to: strongloop/loopback-workspace#229

**Comment by chandadharap** [comment]
Al's note: - App controller could just run the app as a child Node process  ( `node .`)

**Comment by seanbrookes** [comment]
I've converted the app controller over to use the workspace api and things seem to work pretty well.
- Currently looking into the Live Set work Ritchie did to see if we can avoid using polling
- would probably benefit from a help icon in the dialog explainng the relationship between  App Controller and Strong Pm

**Comment by chandadharap** [comment]
We should create  separate story for icon, and if the LiveSet foray takes longer than you expect, perhaps break out that into another story for backlog too. That way, the original intent of the story can close.

**Comment by seanbrookes** [comment]
this is done now, just waiting for CI issues to be resolved so it can be merged

**Comment by cgole** [comment]
seeing some issues with this. 
1. app controller still seems to be using the internal pm - /usr/local/bin/node /usr/local/lib/node_modules/strongloop/node_modules/strong-arc/node_modules/strong-pm/bin/sl-pm.js --listen=0 --base=.strong-pm --no-control

2. When I click on the little hyphen link below the name of the app, it takes me to http://localhost:64120/- which returns Cannot GET /-

**Comment by cgole** [comment]
verified
