### ISSUE TITLE
Property types are not shown when a model definition view is opened first time

### ISSUE THREAD

**Issue by raymondfeng** [strongloop/strong-arc#1485]
Start Arc, go to Composer, open a model definition.

![image](https://cloud.githubusercontent.com/assets/540892/9276635/0eab5c5c-425a-11e5-9bbf-92639e42b8e6.png)

If the model definition view is opened again, the property type starts to show up.

**Comment by seanbrookes** [comment]
some clarification on how to reproduce:
- are you saying the 'Type' dropdown isn't populated the first time you open a model editor view?

**Comment by raymondfeng** [comment]
No, the initial value is empty.

**Comment by seanbrookes** [comment]
the Type value should display 'String' as default value  - gotit

**Comment by cgole** [comment]
reproduce

**Comment by anthonyettinger** [comment]
This has been fixed.
