### ISSUE TITLE
No way to delete an existing property from model definitions in Arc

### ISSUE THREAD

**Issue by raymondfeng** [strongloop/strong-arc#1486]
I don't see a `delete` button to remove an existing property.

**Comment by seanbrookes** [comment]
The UX design calls for the delete button to only show up when a user hovers over the relevant 'row'

**Comment by seanbrookes** [comment]
works as designed

**Comment by cgole** [comment]
not a bug

**Comment by seanbrookes** [comment]
@sam-github why was this reopened?
