### ISSUE TITLE
Api Analytics performance issue - takes very long to load when app is subjected to high loads

### ISSUE THREAD

**Issue by cgole** [strongloop/strong-arc#1489]
- takes very long to load when app is subjected to high loads
- to reproduce, subject app to high load. 
- Can reproduce with strong-gateway-demo app

https://github.com/strongloop/strong-gateway-demo

connected to #1522

**Comment by anthonyettinger** [comment]
@cgole can I get detailed/specific steps to reproduce?

And a description calling out what exactly is slow? Which graph?

**Comment by cgole** [comment]
1. Unzip this file. - https://drive.google.com/open?id=0B4n1rGzq6syFfldZcDFXMEdZMXpTOTVZMkNWQS1LSWF4NFUxLWE0Skc0c0dDYkc0THk3UFU
2. Start arc with --feature api-analytics
3. Add localhost:8701 in PM
4. cd into the app (from 1) 
5. cd auth-server
6. slc start
7. slc ctl set-size 1 1
8. cd resource-server
9. slc start
10. slc ctl set-size 2 1
11. cd ..
12. node client
13. Copy this into a file  - https://gist.github.com/cgole/27eddf582445528c31c7 into rate-limiting.js
Run the script - node rate-limiting.js


GO to the api analytics page. Analytics are slower than normal.  
Other issues - 
http://screencast.com/t/GhTv8OkM
http://screencast.com/t/IkEymGkbWA

**Comment by seanbrookes** [comment]
the main fix was to add loading indicator to the view between clicks on the chart.  The main culprit appears to be the api work needed to compile the summary data to push to the chart.  

There may be some improvements we can make to the ui to tune it up a bit.

There were a few ux tweaks contained in this PR as well but a number of follow on stories have been created in the backlog

**Comment by cgole** [comment]
much better than before. verified
