### ISSUE TITLE
API analytics charts- axis labels inaccurate

### ISSUE THREAD

**Issue by cgole** [strongloop/strong-arc#1490]
I am seeing this often. Should be easy to reproduce
![1](https://cloud.githubusercontent.com/assets/991632/9286081/d34ea90a-42a1-11e5-84bc-be56275ee95b.png)

connected to #1522

**Comment by chandadharap** [comment]
@cgole What is inaccurate?  What do you think it should be? and how to reproduce?

**Comment by seanbrookes** [comment]
I'm unable to reproduce this. Anthony suggested he had fixed it at one point.  Are there steps to consistently repro?

**Comment by seanbrookes** [comment]
I am seeing intermittent misordering of the times.  Looks to be a sort issue based on the value as opposed to respecting the time order first.
- will keep looking.

**Comment by seanbrookes** [comment]
this looks to be a result of the initial getData method getting called twice during initialization and a user clicking on one of the bars inbetween loads causing a duplication in the breadcrumbs and causing the chart depth  index to become 'corrupt'  

fix is to ensure the getData method only gets called once during initialization

**Comment by cgole** [comment]
verified
