### ISSUE TITLE
API analytics chart labels overlapping each other

### ISSUE THREAD

**Issue by cgole** [strongloop/strong-arc#1491]
![screen shot 2015-08-14 at 4 08 31 pm](https://cloud.githubusercontent.com/assets/991632/9286087/f6d3b8de-42a1-11e5-8051-03b425d5bce2.png)

connected to #1522
connected to #1526

**Comment by anthonyettinger** [comment]
@cgole Can I get specific steps to reproduce?

**Comment by cgole** [comment]
I still see the number of very close to each other making it difficult to read. http://screencast.com/t/p04Cy3KJ9W

**Comment by cgole** [comment]
@sean, is it possible to make this any better?

**Comment by seanbrookes** [comment]
can you be more specific (show an updated screen shot of what you are seeing?

I set the number of 'ticks' to display to approx 6 so the chart with display the closest 'rounded' values without any crowding

Maybe you are seeing something different?

**Comment by cgole** [comment]
@seanbrookes  the screenshot if in the comment. Click on the link in the comment.

**Comment by seanbrookes** [comment]
Please double check the version of your code as there should only ever be 6 or 7 ticks on the x axis now.

**Comment by cgole** [comment]
verified. not a bug anymore
