### ISSUE TITLE
strong-pm not running an application needs softer messaging

### ISSUE THREAD

**Issue by altsang** [strongloop/strong-arc#1494]
As a SL arc user, I'm now use to adding strong-pms first entered into the Arc Process Manager because of the UX change to centralize drive users to using Arc PM as the master data table.

When I add a new strong-pm that is not running an app the messaging that something is wrong is quite strong and lumped into the same category as `Problem`.

![image](https://cloud.githubusercontent.com/assets/2261105/9318220/8bd56134-44f6-11e5-89e2-4e15cb0b1191.png)

suggestions for correction and simplification:
- [ ] verify we know the state because we show the right contextual help in the popover that "No app is found".
- [ ] change `Problem` to `No App` and make font color the same as regular typeface text per styleguide
- [ ] change red question mark to regular gray question mark per styleguide

/cc: @anthonyettinger , @jtary, @stacy-hunt 

connected to #1496

**Comment by cgole** [comment]
we might have introduced a regression. now, when a pm has no app deployed to it, the status shows as Inactive

**Comment by cgole** [comment]
Start a pm, dont deploy an app to it yes. add it to Arc PM.
Status is inactive

**Comment by cgole** [comment]
verified

**Comment by chandadharap** [comment]
Published in 1.8.1 
Closing.
