### ISSUE TITLE
Styleguide - misc

### ISSUE THREAD

**Issue by anthonyettinger** [strongloop/strong-arc#1498]
- [x] Borderless Button:  #7dbd33 should be the color for .ui-bnt.accessory
- [x] Add medium modal dialog to style guide (see Policy edit confirmation dialog)
- [x] Add pillbox to Styleguide (#375)

**Comment by anthonyettinger** [comment]
@stacy-hunt PTAL (Please Take A Look)

**Comment by stacy-hunt** [comment]
It's close. But the "close" button should be right-aligned with the text above and the same distance from the right border as the "secondary" button is from the left border:

**Comment by stacy-hunt** [comment]
Borderless button and Pillbox are OK.
Regarding the medium modal dialog:
- the "close" button should be right-aligned with the text above and the same distance from the right border as the "secondary" button is from the left border:
- the corners should be square

![image](https://cloud.githubusercontent.com/assets/1924932/10465248/b1c2df9c-71a2-11e5-8e51-e235fd33e333.png)

**Comment by stacy-hunt** [comment]
All good now, thanks Anthony
