### ISSUE TITLE
Gateway-specific design fixes

### ISSUE THREAD

**Issue by anthonyettinger** [strongloop/strong-arc#1504]
- [x] Modals have extra borders that shouldn’t be there
- [x] Make sure all forms / inputs match style guide
- [x] Check label of “Revert” buttons (some currently say “cancel”
- [x] No left margin on buttons

**Comment by stacy-hunt** [comment]
Modals have extra borders that shouldn’t be there
- [x] Verified
Make sure all forms / inputs match style guide
- [x] Verified (as far as I can tell - I don't have a list of all forms and inputs)
Check label of “Revert” buttons (some currently say “cancel”
- [x] Verified
No left margin on buttons
- [x] Verified
