### ISSUE TITLE
Pipelines design fixes

### ISSUE THREAD

**Issue by anthonyettinger** [strongloop/strong-arc#1506]
- [x] Add “Revert” button to Policy form
- [x]  Add Help to heading
- [x] Form fields / labels don’t match style guide (markup is wrong)
- [x] Remove form border? (see visual comp - not essential but preferable)

**Comment by stacy-hunt** [comment]
- Add “Revert” button to Policy form
- [x] Verified
- Add Help to heading
- [x] Verified
- Form fields / labels don’t match style guide (markup is wrong)
- [x] Verified
- Remove form border? (see visual comp - not essential but preferable)
- [x] Verified
