### ISSUE TITLE
Mappings design fixes

### ISSUE THREAD

**Issue by anthonyettinger** [strongloop/strong-arc#1507]
- [x] New Mapping Dialog check vertical margins between form groups against comp
- [x] Remove form border
- [x] Validation when adding a new mapping
- [x] Same improvements as Pipeline view: vertical margins, remove form border, position save button

**Comment by stacy-hunt** [comment]
- New Mapping Dialog check vertical margins between form groups against comp
- [x] Verified
- Remove form border
- [x] Verified
- Validation when adding a new mapping
- [x] Verified
- Same improvements as Pipeline view: vertical margins, remove form border, position save button
- [x] Verified
