### ISSUE TITLE
smart profiler: not returning samples

### ISSUE THREAD

**Issue by altsang** [strongloop/strong-arc#1508]
steps to reproduce (walked through with Joe to verify already)

1. run `smartprofiler-example-app` in strong-pm
2. make sure license is pushed to strong-pm
3. point browser to example app and set timeout to 150ms
4. run arc
5. add strong-pm in Arc Process Manager
5. go to Profiler module, select strong-pm instance
6. goto profiler settings, and set to smart profile, threshold 20ms, 1500 sample
7. make sure pid is selected and CPU profile is selected
8. click `start` button
9. go to terminal and use `slc ctl status` to verify profiling status is set to 20x1500
10. wait N minutes - profiling will not auto-stop and return CPU profile

/cc: @chandadharap, re-shoot is schedule for 8/25 3PM

**Comment by chandadharap** [comment]
Hi, Is this still unverified? Its sitting assigned to you, am assuming it got fixed? please let me know.

**Comment by altsang** [comment]
:+1: verified on master and on feature/initial-gateway-module
