### ISSUE TITLE
modify policy e2e test

### ISSUE THREAD

**Issue by anthonyettinger** [strongloop/strong-arc#1509]

**Comment by chandadharap** [comment]
Based on history, this was not verified by Chandrika? @cgole please confirm and reopen if so.

**Comment by cgole** [comment]
waiting for arc gateway QA

**Comment by cgole** [comment]
coverage looks good-

covers - 
create policy, pipeline, mapping
clone policy, pipeline, mapping
edit policy, pipeline, mapping
delete policy, pipeline, mapping
