### ISSUE TITLE
Metrics: data points are being squashed

### ISSUE THREAD

**Issue by altsang** [strongloop/strong-arc#1521]
steps to reproduce:

1. run tracing-example-app in strong-pm with proper license
2. let Metrics run for extended amount of time to collect at least a number of data points to span at least 5 hours

**Comment by seanbrookes** [comment]
![merics-squashed](https://cloud.githubusercontent.com/assets/1751524/9998071/75e153ec-6044-11e5-86ec-02060a3f92d0.png)


Is this the issue?  @altsang

**Comment by altsang** [comment]
@seanbrookes 

looks like this..

![image](https://cloud.githubusercontent.com/assets/2261105/9998964/c063fc68-6048-11e5-8274-dbf073cb433a.png)

**Comment by cgole** [comment]
verified
