### ISSUE TITLE
Profiler: select all PIDs pushes down PID selector

### ISSUE THREAD

**Issue by altsang** [strongloop/strong-arc#1523]
steps to reproduce:

1. go to process manager and add a strong-pm with appropriate licensing for watchdog
2. increase processes to at least 2
3. go to Profiler
4. set smart profile in `Profile Settings`
5. click `Select All` button

before clicking `Select All` button
![image](https://cloud.githubusercontent.com/assets/2261105/9617481/e995e156-50b6-11e5-9300-5004feacbd03.png)

after click `Select All` button..

![image](https://cloud.githubusercontent.com/assets/2261105/9617486/f1ee1cec-50b6-11e5-8b72-68ee2ebc3036.png)

**Comment by cgole** [comment]
verified
