### ISSUE TITLE
arc on staging cannot find module 'minkelite'

### ISSUE THREAD

**Issue by cgole** [strongloop/strong-arc#1530]
strong-arc@1.8.33 (a009561)

To repro - 
install latest arc from staging
run slc arc
on the console you'll get this -

$ slc arc
Loading workspace /Users/chandrikagole/workspace/test2
StrongLoop Arc is running here: http://localhost:59163/#/
module.js:338
    throw err;
    ^

Error: Cannot find module 'minkelite'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/strongloop/node_modules/strong-arc/node_modules/strong-pm/node_modules/strong-mesh-models/server/server.js:7:17)
    at Module._compile (module.js:430:26)
    at Object.Module._extensions..js (module.js:448:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
^C

**Comment by rmg** [comment]
Were there any errors during installation?

**Comment by cgole** [comment]
no error - https://gist.github.com/cgole/91db49b6d5c66c65f7b1

**Comment by Setogit** [comment]
The installation log looks normal: https://gist.github.com/cgole/91db49b6d5c66c65f7b1
[sqlite3] Success and minkelite@1.2.18 show up in the log.

**Comment by Setogit** [comment]
Installed the latest strongloop from staging.  'slc arc' works fine on OSX:

> sqlite3@3.0.10 install /usr/local/lib/node_modules/strongloop/node_modules/minkelite/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

[sqlite3] Success: "/usr/local/lib/node_modules/strongloop/node_modules/minkelite/node_modules/sqlite3/lib/binding/node-v14-darwin-x64/node_sqlite3.node" is installed via remote

├── minkelite@1.2.18 (xtend@4.0.0, util@0.10.3, ago@1.0.0, md5@2.0.0, stats-lite@1.0.3, express@4.9.8, body-parser@1.9.3, sqlite3@3.0.10)

└── strong-arc@1.8.33 (parse-ms@1.0.0, opener@1.4.1, path@0.11.14, strong-trace-waterfall@1.1.3, minimist@1.2.0, split@0.3.3, strong-trace-waterfalldata@1.0.1, sha1@1.1.1, node-underscorify@0.0.14, http-proxy@1.11.2, cxviz-color@1.0.1, strong-tra

**Comment by cgole** [comment]
not a bug.  maybe a bad install of strongloop.

**Comment by Setogit** [comment]
@cgole: Does it work for you now?  What was the root cause?  The installation step is straightforward, just "npm install -g strongloop"

**Comment by Setogit** [comment]
Chandrika Gole [12:55 PM] 
@seto: I closed the bug as cannot not reproduce. I am not sure what the issue was. I just reinstalled from staging and now I don't see it
