### ISSUE TITLE
Gateway: default-rate-limiting-policy doesn't show values

### ISSUE THREAD

**Issue by altsang** [strongloop/strong-arc#1531]
1. clone strong-gateway
2. run `slc arc --feature gateway`
3. go to Gateway module
4. click on default-rate-limiting-policy

![image](https://cloud.githubusercontent.com/assets/2261105/9748250/6a3d75d6-5638-11e5-8a6d-67ccc2fca562.png)

5. you need to click on `Type` to show the rest of the fields

**Comment by chandadharap** [comment]
resolved.
