### ISSUE TITLE
Arc app controller doesn't show link to app when started

### ISSUE THREAD

**Issue by cgole** [strongloop/strong-arc#1551]
There is a little hyphen link under the app name. When I click on it, it takes me to http://localhost:64120/- which returns Cannot GET /-

http://screencast.com/t/OXs0MYhP60n

connected to: #1552

**Comment by seanbrookes** [comment]
need to publish latest version of loopback-workspace for the link to show

**Comment by cgole** [comment]
It is missing http:
Right now it shows as //localhost:3000/

**Comment by seanbrookes** [comment]
it's a protocol relative url so it can handle http or https

**Comment by cgole** [comment]
then maybe take the // out too?

**Comment by cgole** [comment]
verified
