### ISSUE TITLE
Arc gateway - Cannot get cursor in the text box and so cannot add scope for policies(sometimes)

### ISSUE THREAD

**Issue by cgole** [strongloop/strong-arc#1553]
To repro - 

Add policy with name auth-test-policy-x 
Sometimes, I am not able to add scopes. Do we have any restrictions on policy names? I noticed that only when I name the policy as demo-auth-policy-xx, I can get the cursor to show up in the scope text box. Sometimes just clicking on it multiple times makes the cursor reappear. 

After saving the policy(w/o being able to add scope), I am able to add scope in the edit mode.

**Comment by cgole** [comment]
@jisoolee, to test this just try clicking everything around policy and making sure it works as expected

**Comment by JISOOLEE** [comment]
works as expected
