### ISSUE TITLE
Composer: scaffolded model, data type does not show up

### ISSUE THREAD

**Issue by altsang** [strongloop/strong-arc#1568]
steps to reproduce:

1. `slc loopback` a new project
2. `slc loopback:model` a new model
3. give model properties
4. `slc arc`

model doesn't have dropped down values for data types properly displayed

![image](https://cloud.githubusercontent.com/assets/2261105/10154995/ad038d74-6623-11e5-81dc-74f083bd539d.png)

**Comment by cgole** [comment]
fixed
