### ISSUE TITLE
text not contained in dropdown for verbin gateway mapping form

### ISSUE THREAD

**Issue by cgole** [strongloop/strong-arc#1573]
![screen shot 2015-09-29 at 2 14 51 pm](https://cloud.githubusercontent.com/assets/991632/10179621/00885e78-66bc-11e5-90ca-9f90a22e7d0e.png)

2 issues - 
1. text coming out of dropdown
2. the selection highlight doesn't move along with the cursor

**Comment by JISOOLEE** [comment]
Now it works fine. Default is "All".
