### ISSUE TITLE
Composer, discovery of MySQL, Decimal as string (should be number)

### ISSUE THREAD

**Issue by proreact-mj** [strongloop/strong-arc#1583]
Hi 

Using the composer to discover a MySQL database, I have a few "decimal(11,2)" fields, but they don't turn out as numbers as expected, but is cast as string (contrary to the documentation): https://docs.strongloop.com/display/public/LB/MySQL+connector 

Not a big problem, but though you might like to know :)

**Comment by raymondfeng** [comment]
See https://github.com/felixge/node-mysql/#connection-options.You can use `bigNumberStrings` to control the format.
