### ISSUE TITLE
manually editing pid count number does not always working as expected.

### ISSUE THREAD

**Issue by cgole** [strongloop/strong-arc#1586]
When I select the current pid count number and enter a new number, it should work. But right now, this is very random. for eg - If I try to change from 1 to 3, it will pick 13 instead of 3

I see this a lot but it works sometimes

**Comment by cgole** [comment]
Note : if you use the pid count selector and edit the number slowly and carefully it might work, but we should definitely make it more solid

**Comment by anthonyettinger** [comment]
Please test, sean submitted a fix

**Comment by seanbrookes** [comment]
this should be resolved with the latest on master

**Comment by cgole** [comment]
there is still a small problem with this. Lets say the pid count is 1 and I change it to 12. In the PM arc UI, the pid count goes back to 1 (from 12) and then increases as the pids are added. I think we should let the count stay at 12 and instead have some indication that the processes are being added.  
But the functionality is there. The pid count eventually gets set to when I want it to be.
