### ISSUE TITLE
Remove potentially unused dependency on pm

### ISSUE THREAD

**Issue by chandadharap** [strongloop/strong-arc#1596]

**Comment by bajtos** [comment]
@jtary to check with @chandadharap what is the priority of this.

**Comment by cgole** [comment]
$ ps -ef | grep node
  501 33275 30540   0  3:32PM ttys002    0:05.61 node /usr/local/bin/slc arc
  501 36633 33275   0  3:33PM ttys002    0:01.38 /usr/local/bin/node .

verified
