### ISSUE TITLE
Create a backlog for Arc Refactor based on f2f sessions

### ISSUE THREAD

**Issue by chandadharap** [strongloop/strong-arc#1597]
https://docs.google.com/document/d/1OCkUqqjTRMWfQdwzWdYn_f8Y8nXh8eL97_jNSlDfuos/edit#heading=h.74tnagaiv6ul

Please re-use the milestone Arc-QIP

**Comment by jtary** [comment]
Broke out some of the major points into a spike. Remaining issues can be schedule and estimated once their feasibility has been determined.
