### ISSUE TITLE
model property datatypes are not persistent

### ISSUE THREAD

**Issue by b-admike** [strongloop/strong-arc#1598]
Tested on Windows 7 (64bit), using node v4.1.0 and npm 2.14.3 and 
strongloop v5.0.1 (node v4.1.0)
├── strong-arc@1.8.3 (d95b140)
├── strong-build@2.0.6 (d008a3e)
├── strong-deploy@3.1.2 (be6180a)
├── strong-mesh-models@8.1.0 (62e539b)
├── strong-pm@5.0.1 (b96f806)
├── strong-registry@1.1.5 (f46e58f)
├── strong-start@1.3.2 (1327018)
├─┬ strong-supervisor@3.3.0 (46b06b4)
│ └── strong-agent@2.0.2 (4ea7ee9)
├── generator-loopback@1.12.1 (a374136)
├── node-inspector@0.7.4
└── nodefly-register@0.3.3

using stronloop from npmjs registry.

Steps to reproduce:
1) create a basic loopback app using slc arc
2) save the loopback-connector-mssql module to the package.json of the app and install the connector
3) using slc arc composer, add a model with a 'string' datatype property
4) add a datastore with remote test mssql server details.
5) start slc pm under root app directory. build and deploy app using slc arc.
6) check slc arc composer details for model. the property doesn't have a datatype set.

**Comment by anthonyettinger** [comment]
@cgole please verify this is still an issue on windows, and if so we can troubleshoot in your windows environment when I'm onsite tomorrow.

**Comment by JISOOLEE** [comment]
Problem solved for both WIndows and Linux.
