### ISSUE TITLE
Refactor: create limited 'arc-ui' module

### ISSUE THREAD

**Issue by jtary** [strongloop/strong-arc#1610]
Create a limited version of the arc-ui common module for styling and common components. For the spike this can be a rough and minimal version.

**Comment by anthonyettinger** [comment]
- [ ] create strong-arc-ui repo
 - [ ] move arc ui widgets to new repo
 - [ ] move styleguide to new repo
 - [ ] test integration with strong-arc-base repo (from @jtary)

**Comment by anthonyettinger** [comment]
This list has been broken up into tasks
