### ISSUE TITLE
Replace deprecated loopback-explorer with loopback-component-explorer

### ISSUE THREAD

**Issue by crandmck** [strongloop/strong-arc#1642]
This project seems to still be using the deprecated `loopback-explorer` which was replaced by `loopback-component-explorer` about two months ago (see https://github.com/strongloop/loopback-component-explorer/issues/123).  The  `loopback-explorer`  module is no longer maintained and shouldn't used afaik.  

@bajtos can confirm.

So, I believe  `loopback-explorer` simply needs to be replaced by `loopback-component-explorer` everywhere.  For example:
- https://github.com/strongloop/strong-arc/blob/master/package.json#L92
- https://github.com/strongloop/strong-arc/blob/master/arc-api/server/boot/explorer.js
- https://github.com/strongloop/strong-arc/blob/master/build-deploy/server/boot/explorer.js

And others.  There are also a couple console messages that still include the old module name as well.

**Comment by bajtos** [comment]
+1

IIRC, there was a problem with strong-mesh-models - they define properties with default values of `null`, which throws an error in swagger-ui. We should investigate and fix this problem as part of this task.

**Comment by crandmck** [comment]
@jtary @chandadharap I think this should be fixed sooner rather than later.

**Comment by jtary** [comment]
@crandmck I can take a look at this in the upcoming sprint. If it's not too much work, we can probably get it done.

**Comment by crandmck** [comment]
@jtary :+1:
