### ISSUE TITLE
Multiple issues for Profiler  that needs clarification

### ISSUE THREAD

**Issue by smartmouse** [strongloop/strong-arc#1659]
There are a few issues with profiler that needs to clarify the proper usage
1. It may seems hang at times when loading data/profiling
2. With multiple processes, loading the same cpu-profiling data file will create multiple "From File" entries on the left hand side -- see screen shot. Sort of confusing.
What is the purpose?  Thought that we will just click on the process on the left panel and display the
data.
3. With multiple processes, the process does not distinguish the cpu profile data file,  i.e. even if the profile1.cpuprofile  belonged to another process, it will still load it .
1. It is a bit confusing on captured heapdump or cpuprofile data, how do we know which process it is for.-- there is no pid associated in the data file.

Steps:

I have multiple processes
I have created start CPU Profiling for the first PID 1 
Then I click on file , and on the left hand side , I click on the process id, and then load.
The I browse to select the profile data file for PID 1
A "From File"  entry  will be created on the left panel.
Then I click on another PID 2, and load the profile data for PID 1.
It still allows me to load which is not expected.
Another "From File" entry will be created on the left panel.
Then I click on another PID 3, and load the profile data for PID 1.
Another "From File" entry will be created on the left panel.

![profile0](https://cloud.githubusercontent.com/assets/4519627/11322115/1f132216-90aa-11e5-8dd6-f0d169b5d8c4.jpg)
![profile1](https://cloud.githubusercontent.com/assets/4519627/11322118/239472fe-90aa-11e5-8d00-df7f0b2adb46.jpg)
![profilefeeze](https://cloud.githubusercontent.com/assets/4519627/11322120/2aaf073e-90aa-11e5-84cb-e7581bee68d7.jpg)

**Comment by smartmouse** [comment]
Randy, please check if we need to enhance the documentation or is this expected behaviour?
Sort of confusing for me.

**Comment by crandmck** [comment]
I'll have a look, ty!
