### ISSUE TITLE
minimum version of strong-pm for  smart profiling required?

### ISSUE THREAD

**Issue by smartmouse** [strongloop/strong-arc#1660]
From the documentation: https://github.com/strongloop/smartprofiling-example-app

Minimum versions

Be sure to do npm install -g strongloop to ensure you have the latest version of StrongLoop Arc.

To use Smart Profiling in Arc, you must have the following versions or higher:

StrongLoop Arc v. 1.6.6
StrongLoop PM v. 5.0.36
Use slc -v to determine your versions.

=However, we cannot get to  strongloop PM v5.0.36 ===
The version we can install is only 5.0.28
Please clarify

nodebot1@wslnx036:~/ivypm> npm ls -g strong-pm
/home/nodebot1/npm-global/lib
├── strong-pm@5.0.28
└─┬ strongloop@5.0.14
  └── strong-pm@5.0.28

nodebot1@wslnx036:~/ivypm> slc -v
strongloop v5.0.1 (node v0.12.7)
├── strong-arc@1.8.3 (d95b140)
├── strong-build@2.0.6 (d008a3e)
├── strong-deploy@3.1.2 (be6180a)
├── strong-mesh-models@8.1.0 (62e539b)
├── strong-pm@5.0.1 (b96f806)
├── strong-registry@1.1.5 (f46e58f)
├── strong-start@1.3.2 (1327018)
├─┬ strong-supervisor@3.3.0 (46b06b4)
│ └── strong-agent@2.0.2 (4ea7ee9)
├── generator-loopback@1.12.1 (a374136)
├── node-inspector@0.7.4
└── nodefly-register@0.3.3

**Comment by cgole** [comment]
Latest version of pm on npmjs is 5.0.1, so StrongLoop PM v. 5.0.36 is definetly not correct.

**Comment by crandmck** [comment]
I moved the min version requirements into the docs (so we only have to maintain in one place): https://docs.strongloop.com/display/SLC/Smart+profiling+with+Arc and corrected strong-pm version there to 5.0.1.
