### ISSUE TITLE
from ARC when deploy to PM - cluster not working for ppc LE 

### ISSUE THREAD

**Issue by smartmouse** [strongloop/strong-arc#1662]
smoking src on ppc LE SLES 12 with node -.12.x
terminal 
npm install -g strongloop  okay
npm install loopback-connector-mongodb  (some compilation issues with kerboers)
slc loopback okay
slc arc
create model okay
create mongdob datasoource okay

terminal B
Start a different terminal windows
npm install -g strong-pm
npm install loopback-connector-mongodb
sl -pm

Then terminal A
build and deploy to PM  (okay)
set process to 5.
go to process ,manager page -- the process did not set to 5 even we restart cluster 
(switch between 1 and 0)
Also complain missing mongodb-connector

see glist --

https://gist.github.com/smartmouse/c841b911ddd062d49aa6

and screen capture
![ppcle1](https://cloud.githubusercontent.com/assets/4519627/11358569/ae9c284a-9241-11e5-82e5-ec277f30eaf3.jpg)
![ppcle2](https://cloud.githubusercontent.com/assets/4519627/11358573/b4887b96-9241-11e5-8cee-a4e1c918bf18.jpg)

On the arc side:(terminal A)

ivyho2@jtcjs22:/svt/ivyho2/testArc> PORT=60250 slc arc
Loading workspace /svt/ivyho2/testArc
StrongLoop Arc is running here: http://localhost:60250/#/
Web server listening at: http://0.0.0.0:3000
Browse your REST API at http://0.0.0.0:3000/explorer
Swagger: skipping unknown type "geopoint".
Web server listening at: http://0.0.0.0:3000
Browse your REST API at http://0.0.0.0:3000/explorer
loopback-datasource-juggler deprecated Model hook "ManagerHost.beforeCreate" is deprecated, use Operation hooks instead. http://docs.strongloop.com/display/LB/Operation+hooks ../IBMSVT64_12/lib/node_modules/strongloop/node_modules/loopback-datasource-juggler/lib/dao.js:271:9

ivyho2@jtcjs22:/svt/ivyho2/testArc> node -e "console.log(process.config)"
{ target_defaults:
   { cflags: [],
     default_configuration: 'Release',
     defines: [],
     include_dirs: [],
     libraries: [] },
  variables:
   { clang: 0,
     gcc_version: 48,
     host_arch: 'ppc64',
     icu_data_file: 'icudt54l.dat',
     icu_data_in: '../../deps/icu/source/data/in/icudt54l.dat',
     icu_endianness: 'l',
     icu_gyp_path: 'tools/icu/icu-generic.gyp',
     icu_locales: 'en,root',
     icu_path: './deps/icu',
     icu_small: true,
     icu_ver_major: '54',
     node_byteorder: 'little',
     node_install_npm: true,
     node_prefix: '/',
     node_shared_cares: false,
     node_shared_http_parser: false,
     node_shared_libuv: false,
     node_shared_openssl: false,
     node_shared_v8: false,
     node_shared_zlib: false,
     node_tag: '-IBMBuild-1.2.0.6-201508140722',
     node_use_dtrace: false,
     node_use_etw: false,
     node_use_mdb: false,
     node_use_openssl: true,
     node_use_perfctr: false,
     openssl_no_asm: 0,
     python: '/usr/bin/python',
     target_arch: 'ppc64',
     uv_library: 'static_library',
     uv_parent_path: '/deps/uv/',
     uv_use_dtrace: false,
     v8_enable_gdbjit: 0,
     v8_enable_i18n_support: 1,
     v8_no_strict_aliasing: 1,
     v8_optimized_debug: 0,
     v8_random_seed: 0,
     v8_use_snapshot: false,
     want_separate_host_toolset: 0 } }
ivyho2@jtcjs22:/svt/ivyho2/testArc>

ivyho2@jtcjs22:/svt/ivyho2/testArc> which node
/svt/ivyho2/IBMSVT64_12/bin/node
ivyho2@jtcjs22:/svt/ivyho2/testArc> which npm
/svt/ivyho2/IBMSVT64_12/bin/npm
ivyho2@jtcjs22:/svt/ivyho2/testArc> npm config ls -l
; cli configs
long = true
user-agent = "npm/2.11.3 node/v0.12.7 linux ppc64"

; default values
access = null
always-auth = false
bin-links = true
browser = null
ca = null
cache = "/home/ivyho2/.npm"
cache-lock-retries = 10
cache-lock-stale = 60000
cache-lock-wait = 10000
cache-max = null
cache-min = 10
cafile = undefined
cert = null
color = true
depth = null
description = true
dev = false
editor = "vi"
engine-strict = false
fetch-retries = 2
fetch-retry-factor = 10
fetch-retry-maxtimeout = 60000
fetch-retry-mintimeout = 10000
force = false
git = "git"
git-tag-version = true
global = false
globalconfig = "/svt/ivyho2/IBMSVT64_12/etc/npmrc"
globalignorefile = "/svt/ivyho2/IBMSVT64_12/etc/npmignore"
group = 3003
heading = "npm"
https-proxy = null
if-present = false
ignore-scripts = false
init-author-email = ""
init-author-name = ""
init-author-url = ""
init-license = "ISC"
init-module = "/home/ivyho2/.npm-init.js"
init-version = "1.0.0"
json = false
key = null
link = false
local-address = undefined
loglevel = "warn"
; long = false (overridden)
message = "%s"
node-version = "0.12.7"
npat = false
onload-script = null
optional = true
parseable = false
prefix = "/svt/ivyho2/IBMSVT64_12"
production = false
proprietary-attribs = true
proxy = null
rebuild-bundle = true
registry = "https://registry.npmjs.org/"
rollback = true
save = false
save-bundle = false
save-dev = false
save-exact = false
save-optional = false
save-prefix = "^"
scope = ""
searchexclude = null
searchopts = ""
searchsort = "name"
shell = "/bin/bash"
shrinkwrap = true
sign-git-tag = false
spin = true
strict-ssl = true
tag = "latest"
tag-version-prefix = "v"
tmp = "/tmp"
umask = 2
unicode = true
unsafe-perm = true
usage = false
user = 3010
; user-agent = "npm/{npm-version} node/{node-version} {platform} {arch}" (overridden)
userconfig = "/home/ivyho2/.npmrc"
version = false
versions = false
viewer = "man"

**Comment by cgole** [comment]
try it again with npm i --save loopback-connector-mongdb

**Comment by smartmouse** [comment]
After totally cleaned up and remove .strongloop and .strong-pm, reinstall everything and start from scratch and also save loopback-connector-mongodb  to package.json.

The issue has been resolved
