### ISSUE TITLE
Missing steps in profiling ( when excuting on ppc le SLES 12)

### ISSUE THREAD

**Issue by smartmouse** [strongloop/strong-arc#1663]
https://docs.strongloop.com/display/SLC/Profiling

Before we execute node load.js
Inside the profiler-example-app
we need to do npm install
or else 
node load.js will have issues

https://gist.github.com/smartmouse/18600ec0bfb806489c24

**Comment by crandmck** [comment]
Added the appropriate steps to https://docs.strongloop.com/display/SLC/Profiling.

However, when I ran `slc start` I get an error:
```
$ slc start
Error: pm failed, exit with status  1
```
NOTE `slc run` is deprecated, we use `slc start` locally now.
