### ISSUE TITLE
if we profiling using a remote host machine,  need extra steps to cover loading cpu/heap files?

### ISSUE THREAD

**Issue by smartmouse** [strongloop/strong-arc#1665]
Use a remote host (e.g. ppcLE SLES 12) machine for ARC and PM.
We will use local browser on local laptop to launch arc and start profiling capture cpu data and heap .
The heap and cpu profiling data is generate on the remote host ./strong-pm folder
see screen shot  
![remotepm](https://cloud.githubusercontent.com/assets/4519627/11388388/9e5f638a-9303-11e5-87a4-50df411e2b50.jpg)

We will transfer the files over to the local desktop if we want to user ARC on local browser to
load the cpu or heap data.
What other meta-data files do we need to transfer over? or just the cpu/heap files are sufficient?

This is not covered in the doc at all.

**Comment by crandmck** [comment]
@smartmouse If I understand correctly, you are running Arc on the remote system, but connecting to it from a local browser?   That is intentionally not a use case that we cover in the docs because Arc is intended for use on a local system afaik.   Is this scenario tested? @cgole
