### ISSUE TITLE
Arc cannot be launched on RH 6 and RH 7 for Node.0.12.x

### ISSUE THREAD

**Issue by jtary** [strongloop/strong-arc#1666]
summary:

When arc can be launched from browser using URL
-[x] SLES11 
-[x] SLES12

The message displayed:
StrongLoop Arc is running here: http://host:port/#/

e.g. StrongLoop Arc is running here: http://zsl12n1:58633/#/
e.g. StrongLoop Arc is running here: http://wslnx036:54947/#/

When arc cannot be launched from browser using URL
-[x] RH6
-[x] RH7

The message displayed:
StrongLoop Arc is running here: http://localhost:port/#/

**Comment by jtary** [comment]
@smartmouse The localhost output will never work if Arc is running on a remote machine. If you are running Arc on a remote machine you must override the host variable. Try running Arc like this: `HOST=0.0.0.0 slc arc`.

That should result in the hostname type URL bring printed, and being able to access the Arc remotely.

**Comment by smartmouse** [comment]
yes, I know, when we bring up the browser: we actually enter http://hostname: port

There are no differences in the steps when we perform the tests -- in the working machines vs the non-work machines.  
I just did slc arc

I was wondering whether the machines that fails do not have any DNS setup properly, so arc is outputing 
localhost:xxxx instead.
Where as in the working case: arc is outputting : host:port.

But I will give your suggestion a try

**Comment by smartmouse** [comment]
I sent you the machine credentials.

**Comment by smartmouse** [comment]
@jtary I found the differences , between the machines that work -- zsl12n1.canlab.ibm.com and zs111n1.can.ibm.com -- when I echo $HOST, it was set up.
On the machines that do not work, when I echo $HOST, there is nothing, so by default on the working machines, the host environment variable is set up, so ARC can resolve the address and printed out
Hostname:port.

**Comment by smartmouse** [comment]
Yes if I set HOST , it will work. So this is a machine config issues.   will be good if this is documented somewhere.  @crandmck , is this already documented somewhere?

Thanks all, closing the issue.

**Comment by jtary** [comment]
@smartmouse HOST isn't something that's configured by default, it's just a common variable that used by a lot of command line software for overriding which interface a server will bind to. There is a warning printed on the console if you run it via SSH, saying the default address may not work, but that won't show up if you're using some other remote access software.

**Comment by smartmouse** [comment]
@jtary Thanks, at least now the behaviour is consistent and works. Our settings varies from machine to machine when it was configured to us. Many small thing we just take it for granted.  :-) Have a nice weekend!

**Comment by crandmck** [comment]
@smartmouse  I can add a note to the docs.  What should it say?   Something like this:
> To run Arc remotely, be sure to set the $HOST environment variable to the FQDN of the host?

Or, please clarify.
