### ISSUE TITLE
ARC document on support platforms need to be modified

### ISSUE THREAD

**Issue by smartmouse** [strongloop/strong-arc#1674]
https://docs.strongloop.com/display/SL/Installing+StrongLoop

-> Z system SUSE Linux Enterprise Server 11 (with Node 0.12.7)

Since we have certified all z-linux platforms. the above need to enhanced.

Linux on Z System 
Node 0.12.7 -
      SUSE Linux Enterprise Server 11.
      RHEL 6.3 and higher
Node 4.2.x
      SUSE Linux Enterprise Server 12
      RHEL 7

**Comment by crandmck** [comment]
Just to clarify, will _everything_ run on these platforms? Arc, LoopBack, and strong-pm?

And are all features supported?  Smart profiling, metrics, tracing, etc?
