### ISSUE TITLE
ARC document needs to mention smart profiling does not support Linux on System z

### ISSUE THREAD

**Issue by smartmouse** [strongloop/strong-arc#1675]
Smart profile is not supported on Linux on System Z.

Need to mention this upfront and in the profiling section of the doc.

Please close this if you already mention somewhere. I may have missed in from the doc.

Thanks .

**Comment by crandmck** [comment]
Docs say
> Smart profiling is supported only for applications running on Linux x86_64 systems

"Linux on System Z" is not a Linux x86_64 system, is it?
If not, then I don't think we need to add anything, as it's covered by the above statement.

**Comment by smartmouse** [comment]
NOTE: Smart Profiling is supported only for applications (and StrongLoop PM) running on Linux.
The above is is currently in the doc,  You are correct that Linux on System Z is not Linux x86_64 system. and we have also ppc64LE and ppc64 BE systems, they all run linux but not x86_64.

so may be adding Linux x86_64 system should do.
Thanks.

**Comment by crandmck** [comment]
The above text is already in the doc at https://docs.strongloop.com/display/SLC/Smart+profiling+with+Arc and https://docs.strongloop.com/display/SLC/Smart+profiling+with+slc.  

Assuming that is sufficient, I'll close this. If we need to change or add more, please reopen.
