### ISSUE TITLE
Remove dependency on React

### ISSUE THREAD

**Issue by jtary** [strongloop/strong-arc#1680]
Identify and replace directives which use React, and remove React as a dependency of Strong-Arc.

Currently the main module that uses React is the composer. However, most of the modules have at least a '*.react.js' file, even though they may not be used. We need to go through each module, and identify the cases where react is being used. Then we can systematically replace the React components with Angular directives, and eventually remove React as a library dependency.

**Comment by abhullar** [comment]
Modules using React (all under ...client>www>scripts>modules directory)
- arc.react.js (arc folder)
    - arc.directives.js
- arc-user.react.js (arc-user)
    - arc-user.directives.js
- common.react.js (common)
    - common.directives.js
- composer.react.js (composer)
    - composer.directives.js
- datasource.react.js (datasource)
    - datasource.directives.js
- ia.react.js (ia)
    - is.directives.js
- metrics.react.js (metrics)
    - metrics.directives.js
- model.react.js (model)
    - model.directives.js
- property.react.js (property)
    - property.directives.js
- tracing.directives.js (tracing)

**Comment by jtary** [comment]
Closed, covered by other issues.
