### ISSUE TITLE
Heroku build fails

### ISSUE THREAD

**Issue by therealweezel** [strongloop/strong-arc#1732]
Pushing a build to Heroku just stopped working. It used to work a few days ago, but now it always breaks with this error:

remote: 158838 error strong-arc@1.8.8 preinstall: `node .sl-blip.js`
remote: 158838 error spawn sh ENOENT
remote: 158839 error Failed at the strong-arc@1.8.8 preinstall script 'node .sl-blip.js'.
remote: 158839 error Make sure you have the latest version of node.js and npm installed.
remote: 158839 error If you do, this is most likely a problem with the strong-arc package,
remote: 158839 error not with npm itself.
remote: 158839 error Tell the author that this fails on your system:
remote: 158839 error     node .sl-blip.js
remote: 158839 error You can get information on how to open an issue for this project with:
remote: 158839 error     npm bugs strong-arc
remote: 158839 error Or if that isn't available, you can get their info via:
remote: 158839 error     npm owner ls strong-arc
remote: 158839 error There is likely additional logging output above.
remote: 158840 verbose exit [ 1, true ]
remote:  !     Push rejected, failed to compile Node.js app.

**Comment by fmaceachen** [comment]
Same here:
Same here trying to deploy in Heroku:

Error: strong-arc@1.8.8 preinstall: node .sl-blip.js
remote: 158849 verbose stack spawn sh ENOENT
remote: 158849 verbose stack at exports._errnoException (util.js:896:11)
remote: 158849 verbose stack at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
remote: 158849 verbose stack at onErrorNT (internal/child_process.js:348:16)
remote: 158849 verbose stack at _combinedTickCallback (internal/process/next_tick.js:74:11)
remote: 158849 verbose stack at process._tickCallback (internal/process/next_tick.js:98:9)
remote: 158850 verbose pkgid strong-arc@1.8.8

**Comment by dzonatan** [comment]
It might be related with mapbox/node-sqlite3#720 package.

**Comment by rikantro** [comment]
related to #1733

**Comment by rmg** [comment]
The original issue reported here should have been fixed by the release of [strong-arc@1.8.9](https://github.com/strongloop/strong-arc/releases/tag/v1.8.9) which completely removes the `preinstall` script. The release hit npmjs.com at 2016-10-06T19:15:52.430Z according to `npm info strong-arc time`.
