### ISSUE TITLE
Failed at the strong-arc@1.8.8 preinstall script

### ISSUE THREAD

**Issue by igalco** [strongloop/strong-arc#1733]
Hello,

I m trying to install strongloop using : 
npm install -g strongloop

how ever the install fails at strong-arc preinstall 

Please see attached log for more information
[npm-debug.txt](https://github.com/strongloop/strong-arc/files/510521/npm-debug.txt)

**Comment by rikantro** [comment]
I have the same issue when install the package strongloop globally, but if only install strong-arc , nothing bad happens

The log is 

```
npm ERR! strong-arc@1.8.8 preinstall: `node .sl-blip.js`
npm ERR! spawn C:\WINDOWS\system32\cmd.exe ENOENT
npm ERR!
npm ERR! Failed at the strong-arc@1.8.8 preinstall script 'node .sl-blip.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the strong-arc package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node .sl-blip.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs strong-arc

npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls strong-arc
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:

npm ERR! code 1

```

System Info

node 6.7.0
npm 3.10.8
windows 10 x64

**Comment by fmaceachen** [comment]
Same here, yesterday was working:

Same here trying to deploy in Heroku:

Error: strong-arc@1.8.8 preinstall: node .sl-blip.js
remote: 158849 verbose stack spawn sh ENOENT
remote: 158849 verbose stack at exports._errnoException (util.js:896:11)
remote: 158849 verbose stack at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
remote: 158849 verbose stack at onErrorNT (internal/child_process.js:348:16)
remote: 158849 verbose stack at _combinedTickCallback (internal/process/next_tick.js:74:11)
remote: 158849 verbose stack at process._tickCallback (internal/process/next_tick.js:98:9)
remote: 158850 verbose pkgid strong-arc@1.8.8

**Comment by djabif** [comment]
Same here trying to deploy to Heroku:

```
remote: 158950 verbose stack Error: strong-arc@1.8.8 preinstall: `node .sl-blip.js`
remote: 158950 verbose stack spawn sh ENOENT
remote: 158950 verbose stack     at exports._errnoException (util.js:893:11)
remote: 158950 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
remote: 158950 verbose stack     at onErrorNT (internal/child_process.js:348:16)
remote: 158950 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:74:11)
remote: 158950 verbose stack     at process._tickCallback (internal/process/next_tick.js:98:9)
remote: 158951 verbose pkgid strong-arc@1.8.8
remote: 158952 verbose cwd /tmp/build_4dc4f82995fac0c9fae5dfd4533b0145
remote: 158953 error Linux 3.13.0-95-generic
remote: 158954 error argv "/tmp/build_4dc4f82995fac0c9fae5dfd4533b0145/vendor/node/bin/node" "/tmp/build_4dc4f82995fac0c9fae5dfd4533b0145/vendor/node/bin/npm" "install" "-g" "strongloop"
remote: 158955 error node v5.11.1
remote: 158956 error npm  v3.8.6
remote: 158957 error file sh
remote: 158958 error path sh
remote: 158959 error code ELIFECYCLE
remote: 158960 error errno ENOENT
remote: 158961 error syscall spawn sh
remote: 158962 error strong-arc@1.8.8 preinstall: `node .sl-blip.js`
remote: 158962 error spawn sh ENOENT
remote: 158963 error Failed at the strong-arc@1.8.8 preinstall script 'node .sl-blip.js'.
remote: 158963 error Make sure you have the latest version of node.js and npm installed.
remote: 158963 error If you do, this is most likely a problem with the strong-arc package,
remote: 158963 error not with npm itself.
remote: 158963 error Tell the author that this fails on your system:
remote: 158963 error     node .sl-blip.js
remote: 158963 error You can get information on how to open an issue for this project with:
remote: 158963 error     npm bugs strong-arc
remote: 158963 error Or if that isn't available, you can get their info via:
remote: 158963 error     npm owner ls strong-arc
```

**Comment by rurivera6** [comment]
I too am getting the error.  It just started happening today.  I use packer scripts to build an AMI image and that's when I get the exact same error regarding the preinstall 'node .sh-blip.js'.

**Comment by tamitutor** [comment]
I am as well.

npm ERR! Darwin 16.0.0
npm ERR! argv "/Users/twright/.nvm/versions/node/v6.7.0/bin/node" "/Users/twright/.nvm/versions/node/v6.7.0/bin/npm" "install" "strongloop" "-g"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.3
npm ERR! file sh
npm ERR! path sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn sh

npm ERR! strong-arc@1.8.8 preinstall: `node .sl-blip.js`
npm ERR! spawn sh ENOENT
npm ERR! 
npm ERR! Failed at the strong-arc@1.8.8 preinstall script 'node .sl-blip.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the strong-arc package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node .sl-blip.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs strong-arc
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls strong-arc
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/twright/npm-debug.log
npm ERR! code 1

**Comment by CoXmaister** [comment]
On Windows:

140367 verbose stack Error: strong-arc@1.8.8 preinstall: `node .sl-blip.js`
140367 verbose stack spawn C:\Windows\system32\cmd.exe ENOENT
140367 verbose stack     at exports._errnoException (util.js:907:11)
140367 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
140367 verbose stack     at onErrorNT (internal/child_process.js:344:16)
140367 verbose stack     at nextTickCallbackWith2Args (node.js:442:9)
140367 verbose stack     at process._tickCallback (node.js:356:17)
140368 verbose pkgid strong-arc@1.8.8
140369 verbose cwd C:\Users\pste
140370 error Windows_NT 6.3.9600
140371 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\pste\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "strongloop"
140372 error node v4.6.0
140373 error npm  v3.10.8
140374 error file C:\Windows\system32\cmd.exe
140375 error path C:\Windows\system32\cmd.exe
140376 error code ELIFECYCLE
140377 error errno ENOENT
140378 error syscall spawn C:\Windows\system32\cmd.exe
140379 error strong-arc@1.8.8 preinstall: `node .sl-blip.js`
140379 error spawn C:\Windows\system32\cmd.exe ENOENT
140380 error Failed at the strong-arc@1.8.8 preinstall script 'node .sl-blip.js'.
140380 error Make sure you have the latest version of node.js and npm installed.
140380 error If you do, this is most likely a problem with the strong-arc package,
140380 error not with npm itself.
140380 error Tell the author that this fails on your system:
140380 error     node .sl-blip.js
140380 error You can get information on how to open an issue for this project with:
140380 error     npm bugs strong-arc
140380 error Or if that isn't available, you can get their info via:
140380 error     npm owner ls strong-arc
140380 error There is likely additional logging output above.
140381 verbose exit [ 1, true ]

**Comment by CoXmaister** [comment]
I was trying to downgrade node and npm (v6.6.0 and 3.10.0), but it didn't help

npm/npm#14188

**Comment by glen-anderson** [comment]
Same here on Windows 10, npm 3.10.8, node 4.6.0 (LTS). Here's the relevant output from `--loglevel=info`

```
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\ganders\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "node-pre-gyp"
npm ERR! node v4.6.0
npm ERR! npm  v3.10.8
npm ERR! path C:\Users\ganders\AppData\Roaming\npm\node_modules\.staging\sqlite3-0ca53160
npm ERR! code EBUSY
npm ERR! errno -4082
npm ERR! syscall rmdir

npm ERR! EBUSY: resource busy or locked, rmdir 'C:\Users\ganders\AppData\Roaming\npm\node_modules\.staging\sqlite3-0ca53160'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\ganders\AppData\Roaming\npm\node_modules\.staging\sqlite3-0ca53160\npm-debug.log
npm info lifecycle sqlite3@3.1.5~preinstall: Failed to exec preinstall script

> strong-arc@1.8.8 preinstall C:\Users\ganders\AppData\Roaming\npm\node_modules\.staging\strong-arc-07f3db93
> node .sl-blip.js

npm info lifecycle strong-arc@1.8.8~preinstall: Failed to exec preinstall script
npm info lifecycle strong-arc@1.8.8~preinstall: Failed to exec preinstall script
C:\Users\ganders\AppData\Roaming\npm
`-- (empty)

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: modern-syslog@^1.1.2 (node_modules\strongloop\node_modules\modern-syslog):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for modern-syslog@1.1.4: wanted {"os":"!win32","arch":"any"} (current: {"os":"win32","arch":"ia32"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: modern-syslog@^1.x (node_modules\strongloop\node_modules\strong-supervisor\node_modules\modern-syslog):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for modern-syslog@1.1.4: wanted {"os":"!win32","arch":"any"} (current: {"os":"win32","arch":"ia32"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: sqlite3@3.1.5 (node_modules\strongloop\node_modules\sqlite3):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: sqlite3@3.1.5 preinstall: `npm install node-pre-gyp`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 4294963214
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\ganders\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "strongloop" "-g" "--loglevel=info"
npm ERR! node v4.6.0
npm ERR! npm  v3.10.8
npm ERR! file C:\Windows\system32\cmd.exe
npm ERR! path C:\Windows\system32\cmd.exe
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn C:\Windows\system32\cmd.exe

npm ERR! strong-arc@1.8.8 preinstall: `node .sl-blip.js`
npm ERR! spawn C:\Windows\system32\cmd.exe ENOENT
npm ERR!
npm ERR! Failed at the strong-arc@1.8.8 preinstall script 'node .sl-blip.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the strong-arc package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node .sl-blip.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs strong-arc
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls strong-arc
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Work\git\users\ganders\web-registration-viewer\server\npm-debug.log
npm ERR! code 1
```

**Comment by roppa** [comment]
Me too, Mac OS Sierra, node v6.6.0, npm 3.10.3:

```
npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "strongloop"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.3
npm ERR! file sh
npm ERR! path sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn sh

npm ERR! strong-arc@1.8.8 preinstall: `node .sl-blip.js`
npm ERR! spawn sh ENOENT
npm ERR!
npm ERR! Failed at the strong-arc@1.8.8 preinstall script 'node .sl-blip.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the strong-arc package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node .sl-blip.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs strong-arc
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls strong-arc
npm ERR! There is likely additional logging output above.
```

**Comment by dzonatan** [comment]
It might be related with mapbox/node-sqlite3#720 package.

**Comment by jjhesk** [comment]
*** Any help for this problem***

**Comment by rikantro** [comment]
@anthonyettinger can you help us?

**Comment by jjhesk** [comment]
@rikantro we need to get it working...

**Comment by rikantro** [comment]
we need to check when this pull request will be merged
[Lock sqlite version to fix global installation](https://github.com/strongloop/strongloop/pull/325)

**Comment by rmg** [comment]
The original issue reported here should have been fixed by the release of [strong-arc@1.8.9](https://github.com/strongloop/strong-arc/releases/tag/v1.8.9) which completely removes the `preinstall` script. The release hit npmjs.com at 2016-10-06T19:15:52.430Z according to `npm info strong-arc time`.

The sqlite3 issue is already being tracked in multiple other issues, so I'm closing this one to narrow the field.

**Comment by singh7889** [comment]
I got the same issue but i resolved by these steps  
got to issues #2831

$ npm install --global windows-build-tools;
Restart the System.
$ npm install -g strongloop.

**Comment by rurivera6** [comment]
Yes, the original issue regarding the preinstall script has been fixed.  Thank you!

**Comment by singh7889** [comment]
Welcome @rurivera6
