### ISSUE TITLE
use bower package manager for client deps

### ISSUE THREAD

**Issue by bajtos** [strongloop/strong-arc#176]
- Studio uses v1.2.10, which is way behind the latest v1.2.22.
 - We should also use `bower` or `npm` to manage client dependencies, so that update is as easy as bumping up a version number in the config file.

**Comment by chandadharap** [comment]
Anthony already did the work in this story, Im not sure now is the best time for feedback and pulling back. 

I believe this is also in wait state? If so please add a label.
