### ISSUE TITLE
fix the way the UI handles null values for config.dataSource 

### ISSUE THREAD

**Issue by seanbrookes** [strongloop/strong-arc#221]
React seems to have a problem with null value in form element such as select.

We want the default value of config.dataSource to be null but for some reason that value 
gets ignored by react and the previous value for config.dataSource gets used instead which is very 
annoying.

The current work around is assigning the value 'none' to the defualt value and then scrubbing it all over the code base when an API call needs to be made.  Way to leaky.

We need a more elegant solution to this.

**Comment by cgole** [comment]
@seanbrookes, how do I verify this?

**Comment by seanbrookes** [comment]
you should be able to set the datasource of a model to 'none' after it has
been set and saved to a legit data source,

On Wed, Jan 7, 2015 at 3:00 PM, Chandrika Gole <notifications@github.com>
wrote:

> @seanbrookes <https://github.com/seanbrookes>, how do I verify this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/strongloop/strong-arc/issues/221#issuecomment-69108284>
> .
>



-- 
*StrongLoop <http://strongloop.com/>** makes it easy to **develop APIs
<http://strongloop.com/mobile-application-development/loopback/>** in Node,
plus get DevOps capabilities
<http://strongloop.com/node-js-performance/strongops/> like monitoring,
debugging and clustering**.*

**Comment by cgole** [comment]
verified
