### ISSUE TITLE
Missing tables when the default datasources uses MySQL

### ISSUE THREAD

**Issue by bajtos** [strongloop/strong-arc#358]
1. Scaffold a new LB app via `slc loopback`
1. Reconfigure the default `db` datasource to use mysql connector.
2. Use a database that does not have tables for built-in models like `User` or `ACL`, e.g. [MySQL Employees Sample Database](https://dev.mysql.com/doc/employee/en/employees-installation.html)
3. Import models for tables that do exist in the db, e.g. "Employees"
4. Run the app, open the explorer, insert a new model instance, e.g. 

  ```
  POST /Employees request:
  {
    "firstName": "john",
    "lastName": "deer",
    "id": 0
  }
  ```

5. The request fails with the following error:

  ```
  {
    [Error: ER_NO_SUCH_TABLE: Table 'employees.acl' doesn't exist]
    code: 'ER_NO_SUCH_TABLE',
    errno: 1146,
    sqlState: '42S02',
    index: 0
  }
  ```

**Comment by raymondfeng** [comment]
I assume it's addressed by https://github.com/strongloop-internal/scrum-loopback/issues/34

**Comment by arcreative** [comment]
FWIW, I think you can actually do an automigration by using the files in `./node_modules/loopback/common/models/`, going to experiment with this later

**Comment by nimran** [comment]
What is the apt solution for this issue ?
