### ISSUE TITLE
Datasource name validation should be an internal link

### ISSUE THREAD

**Issue by sumitha** [strongloop/strong-arc#374]
Steps to repro, login to studio, click on docs link. it opens docs on a new tab. 
go to new datasource, type in test. You should see an error
DataSource name should conform with valid javascript variable name conventions

click on error it opens up 
https://mathiasbynens.be/notes/javascript-identifiers

click back on this tab, it takes you back to the docs page. You need to explicitly click back to Studio tab.

Please change external validation link to something within our docs

**Comment by cgole** [comment]
I have verified that the link now points to our docs and opens a new tab. @crandmck to make sure content is accurate.

**Comment by crandmck** [comment]
Updated the article to note that you cannot use $ in model or data source names.
