### ISSUE TITLE
refactor within new Composer module

### ISSUE THREAD

**Issue by seanbrookes** [strongloop/strong-arc#412]
the existing composer architecture has most of the application logic hosted in a controller at the root of the app.
This was originally done to ensure the methods would always be available to the calling components no matter where they are injected into the app.
The downside of this 'facade pattern' approach is that the modules that make up the app are not well encapsulated.
This story is about migrating the relevant scope variables and methods back down into their respective child modules.

**Comment by seanbrookes** [comment]
@chanda this should be closed.  We did a major refactoring a while ago so this isn't really needed

**Comment by chandadharap** [comment]
close
