### ISSUE TITLE
Models not displaying in Studio v0.2.0

### ISSUE THREAD

**Issue by mikehumphrey** [strongloop/strong-arc#450]
After creating a new project with >slc loopback I installed and ran the studio-strong and configured a MSSQL Datasource.  Once it connected successfully... I performed the "discover models" for that datasource and selected all tables to generate models for.  This process completed and when I closed all of opened model tabs none of them were listed in the menu under models.  I restarted the app, ran npm install and still no models.  I attempted to re-discover models and it errors out saying that the models already existed.  I checked the model-config and the model directory and they are all there, but do not show up in the menu.  I created a new model and associated it with the in memory datasource and this model will not show up either.  When I use the model explorer i am able to view and test the API successfully.  

![screen shot 2014-10-24 at 9 12 02 pm](https://cloud.githubusercontent.com/assets/2335249/4778846/83cb017c-5c05-11e4-9f8b-bec047e5af04.png)

![screen shot 2014-10-24 at 9 14 16 pm](https://cloud.githubusercontent.com/assets/2335249/4778850/d291dc5e-5c05-11e4-98e1-eaf14b72cdf4.png)

![screen shot 2014-10-24 at 9 21 47 pm](https://cloud.githubusercontent.com/assets/2335249/4778863/e0020624-5c06-11e4-89e6-79d8b7547fc5.png)

**Comment by zealseeker** [comment]
@varmab  Hi, why does this error still exist in my loopback project and the command suggested by cgole couldn't fix the problem.

**Comment by VR-Architect** [comment]
I have same issue posted on another thread. Note I am launching my project via Visual Studio 2015 Community edition.

https://github.com/strongloop/strong-arc/issues/1365 

TypeError: Cannot read property 'dataSource' of undefined
    at Array.<anonymous> (model.services.js:179)
    at Object.forEach (angular.js:326)
    at model.services.js:161
    at angular-resource.js:627
    at processQueue (angular.js:13318)
    at angular.js:13334
    at Scope.$eval (angular.js:14570)
    at Scope.$digest (angular.js:14386)
    at Scope.$apply (angular.js:14675)
    at done (angular.js:9725)(anonymous function) @ angular.js:11706
angular.js:11706 update property called with insufficient parameters: {"id":"common.luState.propertyName97","modelId":"common.luState","facetName":"common","type":"string"}
angular.js:11706 TypeError: Cannot read property 'dataSource' of undefined
    at Array.<anonymous> (model.services.js:179)
    at Object.forEach (angular.js:326)
    at model.services.js:161
    at angular-resource.js:627
    at processQueue (angular.js:13318)
    at angular.js:13334
    at Scope.$eval (angular.js:14570)
    at Scope.$digest (angular.js:14386)
    at Scope.$apply (angular.js:14675)
    at done (angular.js:9725)

**Comment by VR-Architect** [comment]
Found the solution which worked for me on this thread:

https://github.com/strongloop/strong-arc/issues/900
