### ISSUE TITLE
refactor composerRequestInterceptor

### ISSUE THREAD

**Issue by seanbrookes** [strongloop/strong-arc#535]
This either needs to go into the composer module or needs to be renamed arc.

**Comment by chandadharap** [comment]
Is this  really for Chandrika to verify? or did it land here by mistake instead of Done?

**Comment by seanbrookes** [comment]
I guess it should be done as there isn't much to verify

On Sun, Jan 18, 2015 at 8:53 PM, chandadharap <notifications@github.com>
wrote:

> Is this really for Chandrika to verify? or did it land here by mistake
> instead of Done?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/strongloop/strong-arc/issues/535#issuecomment-70446362>
> .
>



-- 
*StrongLoop <http://strongloop.com/>** makes it easy to **develop APIs
<http://strongloop.com/mobile-application-development/loopback/>** in Node,
plus get DevOps capabilities
<http://strongloop.com/node-js-performance/strongops/> like monitoring,
debugging and clustering**.*

**Comment by cgole** [comment]
Moving to done then
