### ISSUE TITLE
arc: datasource should be `data source`

### ISSUE THREAD

**Issue by altsang** [strongloop/strong-arc#555]
For consistency, string labels and other references should be `data source` not `datasources`.

Docs are being scrubbed to replace `datasource` to `data source`.

Note: `datasources` is only used in things like filenames because of inconveniences of whitepsaces.

**Comment by cgole** [comment]
Still exists in some places 
![screen shot 2015-01-07 at 11 07 42 am](https://cloud.githubusercontent.com/assets/991632/5651640/0f5ea792-965e-11e4-9c00-56a6d774bff0.png)
