### ISSUE TITLE
Apps using oracle connector will fail remote deploy to pm server

### ISSUE THREAD

**Issue by cgole** [strongloop/strong-arc#662]
Before you run the application, we need to configure the environment variable and make sure the dynamic libraries from Oracle Instant Client will be available for the Node process.
When you deploy an app to a remote pm server there is no easy way to set the env variable before starting the app

**Comment by cgole** [comment]
This should now work with env-set/get

**Comment by crandmck** [comment]
Updated http://docs.strongloop.com/display/NODE/Known+issues#Knownissues-Build&Deploy.
