### ISSUE TITLE
How to run performance profiler and metrics locally on my machine

### ISSUE THREAD

**Issue by bajtos** [strongloop/strong-arc#687]
It is not clear how to profile a project locally on my machine or how to inspect metrics of my project while running locally. The "Profiler" and "Metrics" UI does not provide any hints. I tried to look at "build and deploy", but I was not able to build a tarball (see #686) and/or deploy to the embedded process manager (#695).

**Comment by altsang** [comment]
when going to profiler and metrics module now - the local application is defaulted now

**Comment by ijroth** [comment]
> My take is that we should make it easier for users to be able to open each
> arc module in a new tab so they can easilly switch between views using the
> browser tabs.

> The quick fix for this is to convert the 'app switcher' menu to <a herf />
> elements so users can quickly right click / open in new tab

+1

**Comment by altsang** [comment]
we can do this, let's review the UX with Stacy, but I thought there was a reason why we didnt' want user trying to run 1 more module at a time?

**Comment by seanbrookes** [comment]
we originally built the component as a collections of <button> elements as it seemed more semantic at the time i.e. a navigation command as opposed to a link to a 'page'.

We have minimized our use/dependence on url for navigation in the UI as a rule but this is a case where it makes sense.
