### ISSUE TITLE
datasources are saved to disc BEFORE "save datasource"

### ISSUE THREAD

**Issue by sam-github** [strongloop/strong-arc#692]
Repro:

1. select any data source icon
2. click in the "Connector" field
3. select any connector type
4. do NOT save the datasource
5. observer that server/datasources.json is modified
6. close new datasource tab (still NOT saved)
7. see that the datasource on left is not present (correct, except its in the datasources.json)
8. repeat above....
9. this time when the secret-save is attempted, you get an error: `Oops! Something is wrong
The `DataSourceDefinition` instance is not valid. Details: `name` is not unique.`. But you can't see the conflicting datasource on the left side, this is a conflict with a datasource you can't see exists, and that shouldn't exist

**Comment by seanbrookes** [comment]
moving this down the priority list as it isn't broken but only potentially confusing.  The users data isn't at any risk here. - bigger fish to fry right now

**Comment by cgole** [comment]
wont fix.
