### ISSUE TITLE
Misleading status message after deploy

### ISSUE THREAD

**Issue by bajtos** [strongloop/strong-arc#693]
After I clicked on "Deploy" button, the UI says almost immediatelly "Successfully deployed using git", but I can see in the console that PM is still running build (`npm rebuild` etc.)

**Comment by anthonyettinger** [comment]
The deploy is not actually done...its only kicked off. We can change the status message to whatever makes sense, but this should indicate that there's nothing left for the user to do.

We didn't get support for the console on MVP, nor do we get any indication when the build is complete.

**Comment by chandadharap** [comment]
Something like: "Successfully being deployed"

**Comment by chandadharap** [comment]
I'll take your word for this, i saw an earlier PR. These small messaging and visual fixes should not be assigned to @cgole. She is a QA department of ONE for all of StrongLoop.
