### ISSUE TITLE
Button for starting the project does not work

### ISSUE THREAD

**Issue by bajtos** [strongloop/strong-arc#699]
![screen shot 2014-12-10 at 19 42 38](https://cloud.githubusercontent.com/assets/1140553/5381769/c5b0c2e8-80a4-11e4-890d-101617c17a01.png)

After figuring out that the settings button is supposed to start/stop the project, I clicked on it and got only some console logs:

```
- tick -
localAppState[stopped]
is app running?: false
```

I was running Arc in a local clone of arc repo (strong-arc@e22c63d4), the behaviour seems to be consistent in all views (Build and Deploy, Metrics, Profiler).

**Comment by bajtos** [comment]
I tested the following two scenarios. In both cases I opened "Profiler" component and clicked on the start/stop button. In both cases the application did nothing :(

 1. `slc arc` inside strong-arc repo. Since `node .` does not work either, I was expecting a startup error.

 2. `slc arc` inside a directory with `index.js` containing a simple loopback-based server:

  ```
  // index.js
  var loopback = require('loopback');
  var app = loopback();

  app.use('/api', loopback.rest());
  app.use('/explorer', require('loopback-explorer')(app));
  app.listen(3000);
  ```

**Comment by bajtos** [comment]
FWIW, here is the new screenshot. Notice the star/stop button is greyed out, I don't know whether it means anything.

![screen shot 2015-01-05 at 12 35 15](https://cloud.githubusercontent.com/assets/1140553/5612570/6a73f23c-94d7-11e4-90ca-8c587ee16cf0.png)

**Comment by bajtos** [comment]
Reassigned back to Sean, let me know if you need any more details.

**Comment by chandadharap** [comment]
@cgole @bajtos Is this still a bug?

**Comment by bajtos** [comment]
It did not work for me 7 days ago per my comment above. I don't know whether that behaviour is intended or not, I need somebody more familiar with the product to confirm.

**Comment by cgole** [comment]
This works for me. The button is  greyed out, but if you click on it you can get to the status, start/stop button.
