### ISSUE TITLE
metrics tab quirks

### ISSUE THREAD

**Issue by sam-github** [strongloop/strong-arc#724]
I'm sure this is somewhere in backlog already, but anyhow.

I tried metrics, nothing was displayed. I updated all my arc and pm, assuming something was broken.

Tried again, still nothing. Then I selected a specific process... metrics!

strongops defaults to showing all the metrics of all the processes summed up, you can then select only a single process if that's what you want.

Maybe this should default to graphing the first PID, rather than nothing, until the option exists to graph all pids at once?

Also, one of the PIDs is the pid of the master. Its worth graphing the master, but I think the pids should be clearly marked as to their roll, I'm not sure how. Either a w/s in front of the PID, or something more obvious.

I'd expect to be able to ctl-click a set of pids, like all the workers, to see a set aggregated together. And that might be common enough that it deserves some UI work to make it possible (all workers [ ], or perhaps [ ] show master, something).

The graphs look quite nice, and the 15second update rate is sooooo much better than strongops, yeah!

I think the graphs are too large, though. On my 1920x1080 monitor, with chrome maximized, the 3 graphs aren't displayed without a scrollbar.... I just have to zoom out a bit and they all display, perhaps something is possible here to make scrollbars not be necessary on normalish laptops.

It wasn't clear to me what the little green sticks were. I suggest it would be better as a clock-like thingy, or explict count-up or down from last seen.

When you change what is selected, graph line go away instantly... but when you select a line to be shown, you have to wait 15 secs, it should query for the historical data (or just have it always in memory) so that it gets drawn right away.

But honestly... given that the most lines on a graph are three, I'm not sure why any need to be configurable.

Of course, when object tracking is enabled, https://github.com/strongloop/strong-arc/issues/723, the ability to select what objects get graphed will be great, so much better than sops as it is, so maybe the selectability of lines is useful to be consistent with this future feature.

**Comment by cgole** [comment]
broken down into smaller issues
