### ISSUE TITLE
Zooming out on the build and deploy page screws up the alignment

### ISSUE THREAD

**Issue by cgole** [strongloop/strong-arc#732]
![screen shot 2014-12-10 at 2 43 03 pm](https://cloud.githubusercontent.com/assets/991632/5385841/fea913fe-807a-11e4-89fd-d3f034e24fda.png)

**Comment by anthonyettinger** [comment]
This will be fixed once we align the components w/ the scalable font and styleguide.

**Comment by cgole** [comment]
much better now.
