### ISSUE TITLE
scaffold app doesn't complete package.json gives warnings

### ISSUE THREAD

**Issue by ijroth** [strongloop/strong-arc#748]
I'm working like a total Node noob. I run slc loopback and it scaffolds for me. In the process it prints these warnings:

npm WARN package.json kento@0.0.0 No description
npm WARN package.json kento@0.0.0 No repository field.
npm WARN package.json kento@0.0.0 No README data

I don't know if this means something is not right? I'm just following the getting-started here and perhaps there is a problem. Leaves me with uncertainty. #weirdinitialexpience

Of course I know these are just warnings, but that's because I know something about Node, package.json, npm, etc. As a noob, I might not be so cavalier.

**Comment by bajtos** [comment]
I believe this was fixed by https://github.com/strongloop/strong-arc/issues/748 as of `loopback-workspace@3.6.4`. @ijroth could you please verify?

**Comment by chandadharap** [comment]
This should go to @cgole , reassigning. But @jroth feel free to verify.

**Comment by cgole** [comment]
verified. I don't see this anymore.
