### ISSUE TITLE
refresh problem in metrics

### ISSUE THREAD

**Issue by sumitha** [strongloop/strong-arc#749]
I see this in today's release too, for both local and demo app metrics. It takes quite a few seconds for the radio button changes to take effect in the graph. So it looks like it's not working ,after waiting around 5/10 secs it looks alright or if you click into another pid and get back it refreshed fine.   
![screen shot 2014-12-11 at 1 54 36 pm](https://cloud.githubusercontent.com/assets/1700743/5402983/a7bf240c-813d-11e4-9a67-1b8dd142012c.png)
Not sure what we can do but wanted to let you know.

**Comment by seanbrookes** [comment]
looks like this got fixed inadvertently along the way

**Comment by cgole** [comment]
verified. I think it works better now
