### ISSUE TITLE
Windows - npm cannot be spawned

### ISSUE THREAD

**Issue by cgole** [strongloop/strong-arc#784]
Deploy returns as successful on arc but crashes the pm server - 

![git](https://cloud.githubusercontent.com/assets/991632/5422657/d8b16d16-8243-11e4-977d-deb4c6d14653.png)

**Comment by sam-github** [comment]
@cgole why reopened?

**Comment by cgole** [comment]
@rmg said he had made enough changes to strong-agent that it might worth trying this out again.

**Comment by sam-github** [comment]
@rmg isn't the problem with strong-pm related to cicada/pushover/git, as well as to how pm does an npm spawn? Do you think pm will run on windows now? It doesn't seem strong-agent is involved in pm's windows difficulties.

**Comment by rmg** [comment]
That was a typo on Chandrika's part, I think. My suggestion was that we have made several changes to strong-pm and other dependencies (such as forks of pushover and cicada, among other changes made for the sake of platform portability) and that it might be worth taking the pulse of the situation to see where we stand on Windows.

**Comment by cgole** [comment]
@rmg yeah,  sorry I meant strong-pm. Anyhow, I just tested this will latest on staging and the bug still exists.

**Comment by rmg** [comment]
Ah, I didn't look at which issue this was soon enough. What _might_ work now is the git portion of the deployment to Windows, but that will still get stopped by the problem spawning `npm`. Sorry for the confusion. It did answer my question, however.

**Comment by cgole** [comment]
closing this
