### ISSUE TITLE
Link in error message needs updating

### ISSUE THREAD

**Issue by crandmck** [strongloop/strong-arc#805]
The link in the connector error message to docs on installing data sources is outdated: http://screencast.com/t/QEDbuBs0Ax9

This is not critical, because there is a redirect in place -- but the redirect doesn't take you directly to the pertinent section (though it's the correct article).

Link is http://docs.strongloop.com/display/LB/Data+sources+and+connectors#Datasourcesandconnectors-Installingaconnector

Should be
http://docs.strongloop.com/display/LB/Connecting+models+to+data+sources#Connectingmodelstodatasources-Installingaconnector

**Comment by cgole** [comment]
verified
