### ISSUE TITLE
app controler: when running Node app with no port or URL - hangs

### ISSUE THREAD

**Issue by altsang** [strongloop/strong-arc#843]
run any Node application that does not have a URL or port returned
on the app controller it hangs on "retrieving port"

**Comment by altsang** [comment]
still hanging if  I remove the port info from the app

**Comment by chandadharap** [comment]
Why is this assigned to @cgole? Should it be re-assigned to someone for fixing?

**Comment by cgole** [comment]
verified. For an app without port, it starts the app , runs it and then stops the app.
