### ISSUE TITLE
Update Arc Docs

### ISSUE THREAD

**Issue by chandadharap** [strongloop/strong-arc#848]

**Comment by chandadharap** [comment]
moving to Sprint 62

**Comment by altsang** [comment]
@crandmck here you go, will also send to you via Slack
![loopback-modules_rev1lj](https://cloud.githubusercontent.com/assets/2261105/5725845/60d0d044-9b0b-11e4-9262-9b393f5c60bb.png)

**Comment by crandmck** [comment]
Image updated in http://docs.strongloop.com/display/LB/LoopBack.  I think we can finally close this.
