### ISSUE TITLE
Handler failure in ProfilerServices.downloadFile

### ISSUE THREAD

**Issue by bajtos** [strongloop/strong-arc#851]
At the moment, Profiler does not work in Safari due to #850. When user clicks on `stop` and the backend responds with profile data, the frontend fails. The error is silently discarded and the UI remains in "waiting for response" state.

We should fix that.

**Comment by cgole** [comment]
still an issue

**Comment by cgole** [comment]
still an issue

**Comment by cgole** [comment]
verified fix. I can now see the profiles, but the UI on profiler tab is messed up. - https://github.com/strongloop-internal/scrum-arc/issues/19
