### ISSUE TITLE
Fix  broken Arc e2e tests due to polling

### ISSUE THREAD

**Issue by seanbrookes** [strongloop/strong-arc#856]
looks like there are issues with protractor and $timeouts where the page is never synchronized so Protractor can't hook into it.

Sounds like there may be some work-arounds to be investigated: https://github.com/angular/protractor/issues/49

**Comment by seanbrookes** [comment]
this story should be about repairing the existing e2e tests within a 'polling' style application.
- will look to identify the areas of the app that can be reliably set up for testing
- outline strategy for migrating to a more 'testable' architecture

**Comment by cgole** [comment]
e2e plan is ready. Will break out into individual stories once polling is fixed.
