### ISSUE TITLE
validation message is too light

### ISSUE THREAD

**Issue by seanbrookes** [strongloop/strong-arc#872]
it's hard to read the validation message around model, datasource, and property names.

Should be more visible

**Comment by altsang** [comment]
@anthonyettinger - need to check with Stacy to make sure that this is componentized as part of the live style guide

**Comment by seanbrookes** [comment]
What does 'componentized as part of the live style guide' mean?

**Comment by anthonyettinger** [comment]
Error messages are handled on default form fields in the styleguide. But we'll need to rework most of the strong-arc components once the styleguide is in a good state.

**Comment by chandadharap** [comment]
@cgole does not hve bandwidth to verify this level of detail. Assigning back. Please move to done if you think this is done or assign to @altsang
