### ISSUE TITLE
can't add 'url' as ui property on mongodb datasource form

### ISSUE THREAD

**Issue by seanbrookes** [strongloop/strong-arc#887]
Users will will need to be able to save just a url as a connection string for mongodb (heroku):

eg: mongodb://heroku_app32860495:30n2j6i9lfgc28or9qs18u7ih6@ds047950.mongolab.com:47950/heroku_app32860495

**Comment by cgole** [comment]
This has introduced a regression - Test Connection button is gone. Cannot scroll down.

**Comment by seanbrookes** [comment]
to be honest I don't think that is a regression, this fix just made the problem more serious.  there may even be a ticket for it somewhere.

I think the fix is pretty simple, will take a look

**Comment by seanbrookes** [comment]
created issue #994

**Comment by seanbrookes** [comment]
pending PR#905
