### ISSUE TITLE
update LB docs for getting started

### ISSUE THREAD

**Issue by seanbrookes** [strongloop/strong-arc#890]
the docs appear to be out of sync with the latest LB project setup.

I just ran slc loopback 'project' and it generated a LB project with a server/server.js file but there is no mention (in comments) where to put a pointer to a static 'client' directory anymore.

Going to the LB docs give instructions that don't match the code so it is confusing how to set up static client folders.  

Steps to reproduce:
1) create a project using slc loopback
2) go to server/server.js to configure static directory reference - it isn't there.
3) start Arc
4) click on the help icon in the header - takes you to SL dox
5) click on LoopBack 
6) click on 'getting started'
7) click on 'add static html page' - read instructions and notice it doesn't match the actual code

**Comment by seanbrookes** [comment]
I'm posting this in Arc b/c I'm not sure which LB repo the issue should be assigned to

**Comment by crandmck** [comment]
This is a result of adding middleware phases.  Doc work for that is covered by #950.
