### ISSUE TITLE
arc VD: Live Style Guide

### ISSUE THREAD

**Issue by altsang** [strongloop/strong-arc#899]
Close this story when Stacy and Anythony finish initial iteration of style guide.

**Comment by chandadharap** [comment]
Catchall- removing the estimate.

**Comment by anthonyettinger** [comment]
most of these components in that document have not gone through design process yet. The current styleguide efforts are based on Gareth's visual comp of the styleguide (.sketch file).

**Comment by chandadharap** [comment]
Close this story when Stacy and Anthony finish initial iteration of style guide.

**Comment by altsang** [comment]
verified on master
