### ISSUE TITLE
Spec for Mini-mesh (changed from UX for Mini-Mesh)

### ISSUE THREAD

**Issue by chandadharap** [strongloop/strong-arc#903]

**Comment by altsang** [comment]
https://strongloop.atlassian.net/wiki/display/SL/2015/01/06/SL+Mini-Mesh+UX

can schedule for team review

**Comment by chandadharap** [comment]
The reference above is work in progress. Is there a final UX flow somewhere?

**Comment by altsang** [comment]
there are two different stories - this story is intended to outline the big picture user scenario e2e, I believe we can consider this done, there is a separate story for the Arc Manager module screen UX  - #906

**Comment by chandadharap** [comment]
updated title to coincide with actual work done. closing.
