### ISSUE TITLE
Manager: build Arc backend API for Manager

### ISSUE THREAD

**Issue by altsang** [strongloop/strong-arc#909]

**Comment by chandadharap** [comment]
Add reference to the wiki blogpost

**Comment by ritch** [comment]
Assigning this to sean for integration. Assign it back if you run into issues.

**Comment by seanbrookes** [comment]
I am not able to run the backend code without it crashing regardless of valid pm host or not

**Comment by chandadharap** [comment]
@seanbrooks The last comment was three days ago, please update with current status, since this is in Verify.

**Comment by seanbrookes** [comment]
things seem pretty stable now so this can be closed afaic
