### ISSUE TITLE
Renaming datasource causes errors 

### ISSUE THREAD

**Issue by cgole** [strongloop/strong-arc#911]
I have a datasource in arc. I try to rename it. It throws me an error - 
Oops! Something is wrong
The DataSourceDefinition instance is not valid. Details: name is not unique.
Show/hide details
Name: ValidationError
Message: The DataSourceDefinition instance is not valid. Details: name is not unique.
Details: DataSourceDefinitionuniquenessis not unique
Request: /workspace/api/DataSourceDefinitions
Staus: 422

For every new name I try to save an entry is created in the datasources.json

**Comment by seanbrookes** [comment]
I'm having trouble reproducing on latest master.  Can you verify this is still happening and outline some explicit steps (ds names) to reproduce?

**Comment by seanbrookes** [comment]
we managed to reproduce and narrowed it down to the update from loopback 2.8.6 to  2.8.7  - for some reason that update triggers the issue: - UI error: 'data source name not unique'

if you roll back to 2.8.6 in Arc it works fine but when you move to 2.8.7 (npm install loopback@2.8.7) it fails

steps to reprouduce:
- create and save new data source (don't test)
- rename the new data source to a new unique name
- click save

you should see the exception message

exception trace:
ValidationError: The `DataSourceDefinition` instance is not valid. Details: `name` is not unique.
   at /Users/seanbrookes/_stacks/projects/strongloop/strong-arc/node_modules/loopback-datasource-juggler/lib/dao.js:211:16
   at ModelConstructor.<anonymous> (/Users/seanbrookes/_stacks/projects/strongloop/strong-arc/node_modules/loopback-datasource-juggler/lib/validations.js:473:13)
   at ModelConstructor.next (/Users/seanbrookes/_stacks/projects/strongloop/strong-arc/node_modules/loopback-datasource-juggler/lib/hooks.js:66:12)
   at done (/Users/seanbrookes/_stacks/projects/strongloop/strong-arc/node_modules/loopback-datasource-juggler/lib/validations.js:470:25)
   at /Users/seanbrookes/_stacks/projects/strongloop/strong-arc/node_modules/loopback-datasource-juggler/lib/validations.js:544:7
   at ModelConstructor.<anonymous> (/Users/seanbrookes/_stacks/projects/strongloop/strong-arc/node_modules/loopback-datasource-juggler/lib/validations.js:356:5)
   at /Users/seanbrookes/_stacks/projects/strongloop/strong-arc/node_modules/loopback-datasource-juggler/lib/dao.js:833:7
   at /Users/seanbrookes/_stacks/projects/strongloop/strong-arc/node_modules/loopback-datasource-juggler/lib/connectors/memory.js:345:7
   at /Users/seanbrookes/_stacks/projects/strongloop/strong-arc/node_modules/loopback/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:188:31
   at process._tickCallback (node.js:415:13)

**Comment by bajtos** [comment]
Here are the steps that work for me using strong-arc master:

 1. Inside arc, update to `loopback@2.10.0`
 2. Somewhere else, run `slc loopback` to create a new project This installs `loopback@2.10.0` in the new project too.
 3. Run arc in the new project
 4. Create and save new data source (don't test)
 5. Rename the new data source to a new unique name, click save

**Comment by bajtos** [comment]
@cgole Please check if you can still reproduce the problem. If you can, then please update the instructions to help me with reproducing it on my machine too, and reassign the issue back to me.

**Comment by cgole** [comment]
@bajtos
Steps to repro -

1. Create a new app using slc loopback
2. cd  testapp
3. slc arc
4. Click on Composer
5. Create a new datasource
6. Enter all details and save
7. Edit the name and try to save again. 

This will throw an error -


Oops! Something is wrong
The `DataSourceDefinition` instance is not valid. Details: `name` is not unique.
Show/hide details
Name: ValidationError
Message: The `DataSourceDefinition` instance is not valid. Details: `name` is not unique.
Details: DataSourceDefinitionuniquenessis not unique
Request: /workspace/api/DataSourceDefinitions
Staus: 422
ValidationError: The `DataSourceDefinition` instance is not valid. Details: `name` is not unique.
    at /usr/local/lib/node_modules/strongloop/node_modules/strong-arc/node_modules/loopback-datasource-juggler/lib/dao.js:211:16
    at ModelConstructor.<anonymous> (/usr/local/lib/node_modules/strongloop/node_modules/strong-arc/node_modules/loopback-datasource-juggler/lib/validations.js:473:13)
    at ModelConstructor.next (/usr/local/lib/node_modules/strongloop/node_modules/strong-arc/node_modules/loopback-datasource-juggler/lib/hooks.js:66:12)
    at done (/usr/local/lib/node_modules/strongloop/node_modules/strong-arc/node_modules/loopback-datasource-juggler/lib/validations.js:470:25)
    at /usr/local/lib/node_modules/strongloop/node_modules/strong-arc/node_modules/loopback-datasource-juggler/lib/validations.js:544:7
    at ModelConstructor.<anonymous> (/usr/local/lib/node_modules/strongloop/node_modules/strong-arc/node_modules/loopback-datasource-juggler/lib/validations.js:356

**Comment by bajtos** [comment]
Hmm, as I mentioned in [my comment above](https://github.com/strongloop/strong-arc/issues/911#issuecomment-69921749), I did exactly the same steps and I was not able to reproduce the problem.

Is there anything special about your local machine? What is your version of `strongloop` and `strong-arc`?

Also note that the most recent versions of loopback-datasource-juggler include the value of the invalid property in the error message (see #562), while the error message posted in your comment does not include that. I am almost certain some of your dependencies are not up to date, either inside strongloop/strong-arc or in your scaffolded app.

**Comment by cgole** [comment]
@bajtos   I have the latest slc installed from staging. I created a new app with slc loopback. so there shouldn't be any outdated dependencies there. @seanbrookes, you were able to repro this on your machine, right?

slc -v
strongloop v2.10.7 (node v0.10.35)
├── strong-arc@1.0.33 (98c95e9)
├── strong-build@1.0.4 (2e6d0b3)
├─┬ strong-supervisor@1.4.1 (79c6e49)
│ └── strong-agent@1.2.7
├── node-inspector@0.7.4
├── strong-deploy@1.1.6 (1e61bad)
├── strong-pm@1.6.0 (687644f)
├── strong-registry@1.1.5 (6283ba9)
├── nodefly-register@0.3.3
└── generator-loopback@1.7.3 (b5069c5)

**Comment by bajtos** [comment]
What is the version loopback-datasource-juggler in `strong-arc`? And what is the version in your scaffolded project?

**Comment by cgole** [comment]
$ slc runctl ls | grep loopback
 ├─┬loopback-boot@2.6.5
 ├─┬loopback-connector-mysql@1.5.5
 │ ├─┬loopback-connector@1.2.1
 ├─┬loopback-datasource-juggler@2.14.4
 │ ├─┬loopback-connector@1.2.1
 ├─┬loopback-explorer@1.6.6
 ├─┬loopback@2.10.7
 │ ├─┬loopback-connector-remote@1.0.3
 │ │ ├─┬loopback-datasource-juggler@2.14.4
 │ │ │ ├─┬loopback-connector@1.2.1
 │ ├─┬loopback-phase@1.2.2

**Comment by bajtos** [comment]
The output of `slc runctl ls` shows correct dependency versions in the scaffolded project. It looks like your `strongloop` install may have outdated juggler then. 

I'll take a look myself.

**Comment by cgole** [comment]
You are right @bajtos. I have 1.7.1 of juggler in my strongloop install.  @rmg any idea how this would happen?  slc install from staging has an old version of loopback-datasource-juggler.

**Comment by rmg** [comment]
strongloop depends on loopback-workspace@2.x, which depends on loopback-datasource-juggler@1.x. That is not the copy of loopback-datasource-juggler that strong-arc would use, though. @cgole you should see multiple copies of loopback-datasource-juggler in your dependency tree.

**Comment by bajtos** [comment]
I have landed https://github.com/strongloop/strong-arc/pull/931, the problem should be fixed now. @cgole please verify.

**Comment by cgole** [comment]
Test connection not working as expected anymore -  https://github.com/strongloop/strong-arc/issues/936

**Comment by bajtos** [comment]
Cross-posting from #936:

> > How can I reproduce the problem? What connector did you use? Was there anything special about your app?

> Cannot repro anymore

I believe this item can be closed as verified?

**Comment by cgole** [comment]
Can close this. I cannot repro anymore. I think I made a mistake in my earlier comment. Sorry for the confusion.
