### ISSUE TITLE
Docs for Arc Manager (Mini Mesh)

### ISSUE THREAD

**Issue by chandadharap** [strongloop/strong-arc#913]
Dependent on work to be started in Sprint 62. 
Some context here, but it is not a final spec. 

https://strongloop.atlassian.net/wiki/display/SL/2015/01/06/SL+Mini-Mesh+UX

**Comment by crandmck** [comment]
Current "in progress" docs: http://docs.strongloop.com/display/~admin/Mesh+docs - not published - must be logged in to Confluence to view.

**Comment by altsang** [comment]
added edits and some comments, will need to re-take screenshots after @anthonyettinger PR for VD fixes goes into master

**Comment by crandmck** [comment]
Will retake screenshots tonight.

**Comment by chandadharap** [comment]
closed.
