### ISSUE TITLE
docs: need to call out app controller into its own section or put into the Using Arc section

### ISSUE THREAD

**Issue by altsang** [strongloop/strong-arc#916]
The app controller is still in the Composer section, it should be called out because it's a more general function now that may be utilized across Arc modules.

**Comment by crandmck** [comment]
Oops.  Moved to be under "Using Arc" - http://docs.strongloop.com/display/ARC/Running+your+application.  
Can this be closed now?

**Comment by altsang** [comment]
@crandmck - think this is good, but I think we need to add that a preface section in general that this functionality along with the PID selector having a local application is only available if you start Arc in a Node app directory with a runnable JS file, pls confirm with @ritch

**Comment by crandmck** [comment]
Added a note to http://docs.strongloop.com/display/ARC/Running+your+application.  

When I run Arc outside an app directory, Composer and Build&Deploy are disabled on the splash page, which makes sense.  But App Controller is still enabled, which is a bug.  Opened #925.

Now can we close this? :-)

**Comment by altsang** [comment]
yep - looks good and thx for filing #925!
