### ISSUE TITLE
Create proxy backend for remote strong-pms and proxy-router

### ISSUE THREAD

**Issue by kraman** [strongloop/strong-arc#921]
Strong PM and Proxy-router authentication requires Arc to establish an ssh tunnel and perform basic auth before issuing REST API calls. 

The Arc backend will need to assist the UI by establishing the tunnel and proxy UI commands to the remote servers

**Comment by chandadharap** [comment]
Added Epic

**Comment by ritch** [comment]
Looks like tunneling has some design issues... I think we are going to move forward with SSL for securing the connection.

@kraman @altsang @rmg

**Comment by ritch** [comment]
@kraman can we close this issue? We still have https://github.com/strongloop/strong-arc/issues/909.

**Comment by chandadharap** [comment]
We switched back to ssh, but decision made to not include this in Arc. I will close. But to summarize:
1) pm, pm-install and slc pmctl will support http basic auth. manager won't support the ability to enter username and password, not before node-summit, but will eventually

2) We won't do ssh OR https/x.509 by node-summit, either, its to much perturbation of the UI, and al and issac are also concerned its too much to give away for free.

3) So basic auth will be free, CLI only for the next couple weeks, and the heavy-duty security will come later, probably a paid add on. and ssh will come first, https will focus on real x.509, not self-signed, for companies that are used to provisioning x.509 certs into their infrastructure
