### ISSUE TITLE
"arc" is not an slc command.

### ISSUE THREAD

**Issue by Morriz** [strongloop/strong-arc#922]
It's not listed with "slc --help" either. I just installed with "npm install -g loopback" and now have:

loopback-datasource-juggler@2.14.1
loopback@2.10.1

**Comment by Morriz** [comment]
Sorry, didn't uninstall studio first...

**Comment by Morriz** [comment]
Hmmmm...still same error after uninstall and fresh install

**Comment by crandmck** [comment]
You need to do `npm install -g strongloop` to get `slc`.  See http://docs.strongloop.com/display/LB/Installing+StrongLoop.

**Comment by hagen** [comment]
I've install strongloop (npm install -g strongloop), running on AWS AMI, and I'm getting 'arc is not an slc command'...

**Comment by crandmck** [comment]
What do you get from `slc -v` ?

**Comment by hagen** [comment]
[ec2-user@ip-172-31-XXX-XXX ~]$ slc -v
strongloop v5.0.0 (node v0.10.30)
├── strong-arc@1.8.1 (15814c0)
├── strong-build@2.0.5 (70e7f5b)
├── strong-deploy@3.1.0 (72dbb7c)
├── strong-mesh-models@8.0.0 (1b220f7)
├── strong-pm@5.0.0 (dbaa1a5)
├── strong-registry@1.1.5 (f46e58f)
├── strong-start@1.3.1 (b17cbc0)
├─┬ strong-supervisor@3.2.0 (5f85e41)
│ └── strong-agent@2.0.1 (8554cb3)
├── generator-loopback@1.12.0 (01a38d5)
├── node-inspector@0.7.4
└── nodefly-register@0.3.3

**Comment by crandmck** [comment]
OK, that looks fine.  The problem might be due to using Node 0.10, though I'm not entirely sure.
Are you able to run 

When I switch to Node 0.10.29, running `slc arc` gives me this error:
```
dyld: lazy symbol binding failed: Symbol not found: _node_module_register
  Referenced from: /usr/local/lib/node_modules/strongloop/node_modules/strong-arc/node_modules/ws/node_modules/bufferutil/build/Release/bufferutil.node
  Expected in: dynamic lookup

dyld: Symbol not found: _node_module_register
  Referenced from: /usr/local/lib/node_modules/strongloop/node_modules/strong-arc/node_modules/ws/node_modules/bufferutil/build/Release/bufferutil.node
  Expected in: dynamic lookup

Trace/BPT trap: 5
```

Can you install Node 0.12 or later?

@cgole @Joesimonsen Do you have any ideas?

**Comment by cgole** [comment]
Theres a lot of info in slc --help. Can you try  "slc --help | grep arc"

this should return - 

$ slc --help | grep arc
  arc: StrongLoop GUI, an alternative to the CLI

**Comment by hagen** [comment]
Please close. I stopped and started the instance, and all of a sudden the command now works. Go figure. Thanks for the comments. Peace out.
