### ISSUE TITLE
Marking Strict on models does not mark the model strict

### ISSUE THREAD

**Issue by drewdotpro** [strongloop/strong-arc#924]
connect to strongloop/strong-arc#1199

Action:
Using Arc, open a model and mark it as "strict", save the model.
Expected:
The model is saved and the json contains "strict": true
Actual:
The model is saved and the json does not contain the "strict" property.

Note: Setting "strict": true manually on the model and then performing the above steps will also remove the "strict" property.

**Comment by seanbrookes** [comment]
need to verify

**Comment by cgole** [comment]
This is an issue. When I mark as 'strict and save, the model is saved and the json contains "strict": false

**Comment by seanbrookes** [comment]
See Arc PR #1200

**Comment by cgole** [comment]
verified
