### ISSUE TITLE
Some metrics charts don't load at all

### ISSUE THREAD

**Issue by cgole** [strongloop/strong-arc#938]
I have the loadtest app running on cluster with 5 workers. As I switch between the processes, some charts dont load at all. As I scroll down the charts are missing all together. I refreshed the page and try re-loading and saw the missing charts, but switching between pid's again led to the same issue.  Extremely flaky

**Comment by altsang** [comment]
even with 1 PID selected, leaving the metrics chart running to gather data points results in a crash OR a blank page where I'm forced to do a browser hard refresh

**Comment by seanbrookes** [comment]
Ref #1050 specifically for the crashing

**Comment by cgole** [comment]
closing this.

**Comment by cgole** [comment]
metrics not loading for me at all on staging -

$ slc --version
strongloop v3.0.10 (node v0.10.38)
├── strong-arc@1.1.104 (8e3582a)
├── strong-build@1.0.7 (2e6d0b3)
├── strong-deploy@1.1.29 (771309d)
├── strong-pm@3.1.37 (e6bb4a2)
├── strong-registry@1.1.6 (6283ba9)
├── strong-start@1.0.14 (a90857d)
├─┬ strong-supervisor@1.4.53 (2c388d9)
│ └── strong-agent@1.3.19
├── generator-loopback@1.9.1 (b90e9cd)
├── node-inspector@0.7.4
└── nodefly-register@0.3.3

**Comment by cgole** [comment]
As I scroll down I only see "pending data" These charts dont load at all

**Comment by cgole** [comment]
verified. Looks much better now!!!
