### ISSUE TITLE
renaming datasource and saving shows duplicate datasource in composer

### ISSUE THREAD

**Issue by cgole** [strongloop/strong-arc#945]
Create a datasource named x
Rename it and save
On the backend, it works as expected. The new datasource name shows up.
In the composer 2 datasources with the same name show up

**Comment by cgole** [comment]
![screen shot 2015-02-03 at 3 08 19 pm](https://cloud.githubusercontent.com/assets/991632/6031767/017f0284-abb7-11e4-8e22-0acbabf91589.png)

**Comment by cgole** [comment]
Canceling the duplicate datasource and refreshing makes it go away

**Comment by seanbrookes** [comment]
I'm not able to reproduce this.   I followed the steps above and tried some other paths but didn't see a duplicate tab when renaming datasource

**Comment by cgole** [comment]
cannnot repro anymore
