### ISSUE TITLE
Metrics: strong-pm PID not showing up

### ISSUE THREAD

**Issue by altsang** [strongloop/strong-arc#946]

**Comment by altsang** [comment]
steps to reproduce:

1. run strong-pm locally
2. get license key via `slc strongops`
2. take loopback-example-app and deploy to local instance
3. load Arc Metrics module and specify local URL
4. repeatedly get error that metrics key is not available
5. get back metrics in the graphs - but no PID, get error that PID values are not valid

**Comment by cgole** [comment]
not a bug anymore
