### ISSUE TITLE
arc manager : host name got reset to default 

### ISSUE THREAD

**Issue by cgole** [strongloop/strong-arc#952]
In screenshot below, my app is deployed to pm server at localhost. I set the host to localhost, port to 7777 and as expected, it showed me the running processes. But when I checked back after a while, the host name was reset to default. The processes are still showing correctly 
![screen shot 2015-02-04 at 3 08 26 pm](https://cloud.githubusercontent.com/assets/991632/6051768/da20698e-ac7f-11e4-95e6-0db342a5840f.png)

**Comment by ritch** [comment]
Can you test this again with the latest `strong-mesh-client`?

**Comment by seanbrookes** [comment]
agreed, this should be fixed

**Comment by cgole** [comment]
cannot repro anymore
