### ISSUE TITLE
arc manager : processes dont load for 'local application'

### ISSUE THREAD

**Issue by cgole** [strongloop/strong-arc#954]
App is started through the arc app controller. Processes dont load. Cant click on the activate button., 
![screen shot 2015-02-04 at 3 21 18 pm](https://cloud.githubusercontent.com/assets/991632/6051932/7ee95132-ac81-11e4-9d4e-ac488a6c463f.png)

**Comment by cgole** [comment]
#961  needs to be fixed too

**Comment by seanbrookes** [comment]
as per my understanding this issue will go away when we filter out access to the local pm instance

**Comment by cgole** [comment]
not an issue
