### ISSUE TITLE
arc manager : cluster restart not working

### ISSUE THREAD

**Issue by cgole** [strongloop/strong-arc#955]
I can get this working use pmclt on command line, but not through arc manager

**Comment by ritch** [comment]
This is an issue in the UI. It should be calling `action()` with:

```js
{
  cmd: 'current',
  sub: 'restart'
}
```

**Comment by cgole** [comment]
still doesnt work for me. I tried cluster restart. It doesnt the right thing when I check the cluster status from the command line using pmclt. But arc manager doesnt show the correct pid's.

**Comment by cgole** [comment]
refer to https://github.com/strongloop/strong-arc/issues/978
