### ISSUE TITLE
arc manager : load balancer does not always get updated with all pm hosts endpoints

### ISSUE THREAD

**Issue by cgole** [strongloop/strong-arc#957]

**Comment by ritch** [comment]
Pushed a fix for this to `strong-mesh-client`. Please `npm update` and test again.

**Comment by cgole** [comment]
This still very much exists.  I tried creating a LB and then adding pm hosts, but still doesnt show up in the routes.json endpoint.

**Comment by ritch** [comment]
I can't reproduce this... Can we walk through your setup in a hangout?

Here is what I am seeing:

![screen shot 2015-02-05 at 3 59 38 pm](https://cloud.githubusercontent.com/assets/462228/6071910/1733905a-ad50-11e4-8492-08de505f8f0f.png)

![screen shot 2015-02-05 at 3 59 46 pm](https://cloud.githubusercontent.com/assets/462228/6071916/2d659f1c-ad50-11e4-8a8d-aa6c466203f0.png)

**Comment by ritch** [comment]
@cgole

**Comment by cgole** [comment]
I am going to keep a watch on this on. Closing it for now since I couldnt repro on hangout
