### ISSUE TITLE
arc manager :  Long host names appear to be cut off in text box

### ISSUE THREAD

**Issue by cgole** [strongloop/strong-arc#960]
![screen shot 2015-02-05 at 11 31 11 am](https://cloud.githubusercontent.com/assets/991632/6067599/999eee48-ad2a-11e4-8e88-200fd4be769e.png)

**Comment by anthonyettinger** [comment]
can't reproduce @cgole

**Comment by cgole** [comment]
canot repro anymore

**Comment by chandadharap** [comment]
moving to close then.
