### ISSUE TITLE
Process Manager: landing page icon needs to be changed from "Manager" to "Process Manager"

### ISSUE THREAD

**Issue by altsang** [strongloop/strong-arc#966]

**Comment by ritch** [comment]
Fixed in https://github.com/strongloop/strong-arc/pull/970

**Comment by altsang** [comment]
also URL needs to be changed to /processmanager

**Comment by ritch** [comment]
> also URL needs to be changed to /processmanager

updated the url as well

**Comment by cgole** [comment]
verified

**Comment by altsang** [comment]
verified on master
