### ISSUE TITLE
Process Manager: order of hosts added not right

### ISSUE THREAD

**Issue by altsang** [strongloop/strong-arc#972]
when adding hosts the record entry should not be stacking new rows on top of old rows, see screencap:

![image](https://cloud.githubusercontent.com/assets/2261105/6074520/4e99ff82-ad75-11e4-826d-b89081c8257d.png)

the first record entered was the host with port 7001, the second record entered was 7002 and third was 7003 with 7003 listed first now

**Comment by seanbrookes** [comment]
this might depend on how the backend is doing the file writes.

the front-end is just iterating on the response from the api.

We could add sorting capabilities but even then I don't think we have a 'last update' field

**Comment by altsang** [comment]
@ritch can you see above?

**Comment by ritch** [comment]
Here is the fix for this:

https://github.com/strongloop/strong-mesh-client/pull/11

No UI changes needed due to a clever default in the client.

**Comment by chandadharap** [comment]
waiting for strongloop/strong-mesh-client#11 before closing

**Comment by chandadharap** [comment]
@cgole, possibly could be verified?

**Comment by cgole** [comment]
done
