### ISSUE TITLE
Process Manager: app link doesn't work

### ISSUE THREAD

**Issue by altsang** [strongloop/strong-arc#973]
when clicking the app link on the header - It goes to the landing page within Arc, not the application URL

**Comment by seanbrookes** [comment]
about that...

There is an issue.  I assumed all the apps would be running on the same host/port and with the requests farmed out by the lb.

But each app can/will have a unique url - so we can't really support 1 unified link.

we could do a link per row (as was in an early wireframe)

**Comment by altsang** [comment]
yes the app would be running on different ports on strong-pm but what we would need to surface is the main entry point URL fronted by nginx

@kraman - can you see above?

**Comment by altsang** [comment]
disabling the app link feature in the table title for the first release, we need to re-think the UX around this

**Comment by altsang** [comment]
@stacy-hunt we need to revisit this, this can be potentially confusing

**Comment by stacy-hunt** [comment]
OK - I'll need some requirements. Can you elaborate them yet?

**Comment by seanbrookes** [comment]
Turns out each host can a different url/port so we can't count on a single url for all the hosts to point to.

At one point we had the concept of the app name as a linke per row in the grid -  but that was before we narrowed it down to a single app

**Comment by cgole** [comment]
not a bug anymore
