### ISSUE TITLE
Process Manager: stopping the app on strong-pm should not result in a problem icon

### ISSUE THREAD

**Issue by altsang** [strongloop/strong-arc#974]
I clicked stop on first record - strong-pm localhost:7003 from the host action menu:

![image](https://cloud.githubusercontent.com/assets/2261105/6074692/0aee5f9a-ad79-11e4-8d4a-9ee051f07caa.png)

if the app was stopped the state should revert back to Activate link with the socket plug icon unplugged, the drop down menu should have Start - which it does, no problem icon should be displayed

**Comment by seanbrookes** [comment]
I guess there was some lingering confusion then.  My understanding was that the only 'active' state was a running app.  That's why I proposed Active/Inactive in the first place - as opposed to 'Problem'.

**Comment by cgole** [comment]
now it changes to Inactive state. verified
