### ISSUE TITLE
arc manager : UI -  load balancer details overlaps and hides part of process manager

### ISSUE THREAD

**Issue by cgole** [strongloop/strong-arc#976]
workaround is to click on Load Balancer. But this should defn be fixed. 
![screen shot 2015-02-05 at 9 29 22 pm](https://cloud.githubusercontent.com/assets/991632/6074981/bf269ec8-ad7e-11e4-88e0-bf1a20fb90c5.png)

**Comment by chandadharap** [comment]
I saw this and experienced this confusion myself. The usability is fairly bad.  I had to click around to try and figure out what to do. Fro someone just trying it out (like most of the initial folk) its confusing.

**Comment by altsang** [comment]
agreed, closing this issue - please see #988, we have a wireframe for what it should roughly look like
