### ISSUE TITLE
arc manager  : Using  auto complete for host name doesnt work

### ISSUE THREAD

**Issue by cgole** [strongloop/strong-arc#977]
To repro - 

I have 2 pm servers on localhost at diff ports.
Add the first pm server  - localhost  7777
While adding the 2nd host, I get 'localhost' in autocomplete so I click on it. 
This doesnt work 
![screen shot 2015-02-05 at 9 45 01 pm](https://cloud.githubusercontent.com/assets/991632/6075094/946ad6a2-ad80-11e4-96f3-572b2be10928.png)

**Comment by seanbrookes** [comment]
type-ahead has some resource locking issues so may not make initial release

**Comment by cgole** [comment]
verified
