### ISSUE TITLE
arc manager :  arc pm fails to get correct app status after stop, start and cluster restart.   

### ISSUE THREAD

**Issue by cgole** [strongloop/strong-arc#978]
App is back up and running, but arc doesnt seem to find it.

![screen shot 2015-02-05 at 10 00 05 pm](https://cloud.githubusercontent.com/assets/991632/6075182/7778bad0-ad82-11e4-9e3d-c2b24ec1ffc6.png)

**Comment by ritch** [comment]
This is actually an issue in `strong-pm`.

**Comment by ritch** [comment]
`strong-pm` is incorrectly setting the `stopTime` field even though the process is running.

/cc @kraman @sam-github 

![screen shot 2015-02-06 at 11 18 23 am](https://cloud.githubusercontent.com/assets/462228/6085832/f2ce42ee-adf1-11e4-91bb-acdd9b9674bb.png)

![screen shot 2015-02-06 at 11 18 11 am](https://cloud.githubusercontent.com/assets/462228/6085835/f7fba964-adf1-11e4-9592-fdf19a46ea72.png)

**Comment by ritch** [comment]
FWIW I tested @kraman's fix for this and it worked.

**Comment by kraman** [comment]
Requires new version of strong-pm@1.7.3

**Comment by cgole** [comment]
verified
