### ISSUE TITLE
Process Manager: URL needs to be /process-manager

### ISSUE THREAD

**Issue by altsang** [strongloop/strong-arc#979]
I should've checked earlier.

Please change from /processmanager to /process-manager to be consistent with /build-deploy

**Comment by chandadharap** [comment]
Is this a critical/blocker for release by Sunday?

**Comment by ritch** [comment]
@altsang what are you referring to?

**Comment by ritch** [comment]
The URL is already `/process-manager`... Please re-open with additional details.

**Comment by altsang** [comment]
nvm we're good here if it's `/process-manager`
