### ISSUE TITLE
arc manager : Set cluster size doesnt resize the cluster

### ISSUE THREAD

**Issue by cgole** [strongloop/strong-arc#982]
I set cluster size to 2 but that dint do anything. 

![screen shot 2015-02-06 at 11 25 29 am](https://cloud.githubusercontent.com/assets/991632/6085978/f7031bf4-adf2-11e4-894a-2f1e91495f12.png)

**Comment by chandadharap** [comment]
Needs a progress indicator

**Comment by altsang** [comment]
should conflate the button presses to a single input, i.e. wait for button presses before the action takes place

**Comment by seanbrookes** [comment]
this one is a bit tricky and may not make the initial release

**Comment by chandadharap** [comment]
Ive verified several times. It works.
