### ISSUE TITLE
Live Style Guide Review Items #2

### ISSUE THREAD

**Issue by stacy-hunt** [strongloop/strong-arc#986]
- [ ] Search Box icons (Mag glass and "X") should be aligned vertically with the centre of the box (Note that the attached image is a composite of 2 different states to show both icons at once)
![image](https://cloud.githubusercontent.com/assets/1924932/6088759/ce1ff140-aebe-11e4-8581-3f372b99972b.png)

- [ ] Search Box prompt text should be aligned vertically with input field text and the same size and weight (also a composite image)
![image](https://cloud.githubusercontent.com/assets/1924932/6088774/ff307d7c-aebe-11e4-8ada-c3342ab58cc1.png)

- [ ] Preload hover and mousedown state images. Currently assets (most notably checkboxes and radio buttons) blink when you first interact with them

**Comment by stacy-hunt** [comment]
Next round of review items for the Live Style Guide

**Comment by anthonyettinger** [comment]
@stacy-hunt -- this is only used on styleguide right now?

**Comment by anthonyettinger** [comment]
@stacy-hunt can you verify this on the styleguide? I believe its been fixed already.
