### ISSUE TITLE
Size shows resized +1 worker

### ISSUE THREAD

**Issue by chandadharap** [strongloop/strong-arc#992]
With 8 workers, the size showed 9. Then I resized the cluster to 4 (down from 8). It shows as 5. See attached screen capture below.

>2015-02-07T06:05:32.927Z pid:42897 worker:0 INFO supervisor resized to 4

**Comment by chandadharap** [comment]
![resized](https://cloud.githubusercontent.com/assets/4267700/6091053/d963aa5a-ae4c-11e4-8f3d-563017ae5f12.jpg)

**Comment by chandadharap** [comment]
@ritch for FYI, wasn't sure where the issue might be.

**Comment by ritch** [comment]
The extra pid is the supervisor.

**Comment by chandadharap** [comment]
@ritch @kraman @seanbrookes This needs fixing.

**Comment by chandadharap** [comment]
worker=0 is supervisor. (the pids on pm api with worker id = 0 is the supervisor )

**Comment by chandadharap** [comment]
Verified. closing.
