### ISSUE TITLE
LB box, font text is way too light

### ISSUE THREAD

**Issue by chandadharap** [strongloop/strong-arc#993]
It seems to indicate "unavailable" input box. Too light to read.

**Comment by chandadharap** [comment]
@altsang Not sure if this is part of a list that Anthony has, so I'll leave it in Planning. Please prioritize if not already. Font is quite unreadable and light.

**Comment by chandadharap** [comment]
![light](https://cloud.githubusercontent.com/assets/4267700/6091188/be07e860-ae52-11e4-992a-292870b5f107.jpg)

**Comment by anthonyettinger** [comment]
that is the design. its placeholder text. its meant to be muted. I will double check though to be sure something isn't conflicting.

**Comment by altsang** [comment]
this is by design as placeholder text as noted by @anthonyettinger, closing
