### ISSUE TITLE
Process Manager: Load Balancer setting needs contextual help

### ISSUE THREAD

**Issue by altsang** [strongloop/strong-arc#999]
@crandmck and @anthonyettinger - please have URL link to docs and put in a paragraph in the contextual help drop down box explaining this setting:

'If using Nginx controller integration - see docs <link>, enter in the host and port of the controller"

**Comment by crandmck** [comment]
Helpp page draft: http://docs.strongloop.com/display/ARC/Load+balancer+settings.

See http://docs.strongloop.com/display/ARC/User+assistance+pages - very bottom - for the page ID, etc.

**Comment by crandmck** [comment]
@anthonyettinger Is this on a branch?  If so, which one?

**Comment by anthonyettinger** [comment]
@crandmck its on the gateway branch

**Comment by crandmck** [comment]
Confirmed on `feature/initial-gateway-module-create` branch.
